### ISSUE TITLE
biblatex unusable on upLaTeX

### ISSUE THREAD

**Issue by aminophen** [plk/biblatex#659] opened 2017-11-24 14:37 UTC
The change introduced in #506 is causing an error on uplatex (Japanese LaTeX); it seems that current biblatex is completely unusable on uplatex. An example in

https://en.wikibooks.org/wiki/LaTeX/Bibliographies_with_biblatex_and_biber#A_simple_example

can reproduce the issue by executing

~~~~
$ uplatex doc.tex
$ biber --bblencoding=utf8 -u -U --output_safechars doc
$ uplatex doc.tex
~~~~

~~~~
! Bad character code (8217).
~~~~

The list \DeclarePrefChars{'’-} contains ’ (U+2019), but (u)pTeX complains when the character is out of range of ASCII code in <code>\sfcode`(char)=(number)</code>. A workaround for Japanese users is to add \DeclarePrefChars{'-} to the preamble, but the situation is uncomfortable enough...

**Comment by moewew** [comment] 2017-11-25 10:51
Thank you very much for reporting this. And thank you also for pointing out the problematic bit of code as well.

@plk I think this means that at least the `.sty` files should be ASCII-only. At the moment the only problematic character is the `’` introduced in https://github.com/plk/biblatex/commit/aeb48bffe4dbb6f7cc80ba23952fb88cc7d461d1. We probably need to revert that change. This has implications also for #366. I suggest we restrict the defaults to ASCII-only and mention in the docs that non-ASCII chars need to be set by users (and that they can only expect those to work with a completetly UTF-8-aware engine).

**Comment by josephwright** [comment] 2017-11-25 11:12
You can go for a conditional: we have that in `expl3` for example for similar reasons. Test for the pTeX engines and skip over the 'unsafe' tokens?

**Comment by aminophen** [comment] 2017-11-25 11:16
> Test for the pTeX engines and skip over the 'unsafe' tokens?

I think it's good. However I'm not sure pdfTeX is really ok. Of course it is not causing an error, but is it UTF-8-aware and working as expected?

**Comment by moewew** [comment] 2017-11-25 11:39
Of course a conditional would be a nice idea. But is it safe to assume that (u)pLaTeX is the only engine that can't deal with this? And how do we safely test for pLaTeX (and upLaTeX?)? With `\kanjiskip`?

**Comment by josephwright** [comment] 2017-11-25 13:19
@moewew Testing for pTeX is easy: use `\kanjiskip`. For upTeX alone gets a bit more 'fun': see `l3sys.dtx`. Probably the safest approach is to have any skipped content at the end of a file (so you can `\endinput` for pTeX), or use a separate file.

**Comment by moewew** [comment] 2017-11-25 13:33
OK, 'fortunately', both pLaTeX and upLaTeX don't like `\sfcode`s for non-ASCII chars. So it seems to be enough to check for `\kanjiskip` (similar to https://github.com/latex3/latex3/blob/2961aa0e38aa46d735b1004784c0f00e5cbb0554/l3kernel/l3tl-analysis.dtx#L384?)

I like the idea of a separate non-ASCII/UTF-8 file.
Should we then use that file for all engines, except for (u)pLaTeX, or only for the unicode engines XeLaTeX and LuaLaTeX? What about pdfLaTeX?

**Comment by moewew** [comment] 2017-11-25 15:04
@josephwright Does setting `\sfcode` for non-ASCII chars in pdfLaTeX work?
I tried
```
\sfcode`\’=1000
```
but got nowhere. I'm beginning to think that the code did not throw an error in pdfLaTeX by accident (because it did not process Unicode chars as intended) and not because it is unproblematic.

**Comment by moewew** [comment] 2017-11-28 18:55
An attempt to fix this can be found in #665. All Unicode characters were moved to a new file that is only opened by fully Unicode-aware engines.

**Comment by moewew** [comment] 2017-11-29 13:54
#665 Has been merged and the changes are in `dev` now. Testing and comments are still appreciated. I would like to wait to release a new version for a week or two in case something else turns up.

**Comment by moewew** [comment] 2017-12-18 12:48
We are planning to release the next version with a fix for this shortly.

Testing would be appreciated. You can either pull and install from `dev` or get the development version from https://sourceforge.net/projects/biblatex/files/development/.

**Comment by aminophen** [comment] 2017-12-18 12:55
> get the development version from https://sourceforge.net/projects/biblatex/files/development/

Tested; it works as expected on upLaTeX. Thank!

**Comment by moewew** [comment] 2017-12-18 12:58
@aminophen Thank you very much for the testing and swift feedback. We're hoping to start the release sequence tomorrow evening (UTC), but because Biber and `biblatex` need to be released at the same time (normally, I think this time it is not that crucial) it might take a few days until things are up on CTAN. But things should be done around Christmas.

**Comment by moewew** [comment] 2018-01-04 20:01
`biblatex` 3.10 with the fix is on CTAN and in MikTeX and TeX live now.

**Closed by moewew** 2018-01-04 20:01 UTC
Labels: bug
