### ISSUE TITLE
error with lualatex-dev

### ISSUE THREAD

**Issue by ralessi** [plk/biblatex#1040] opened 2020-08-25 06:12 UTC
Hello,

With the latest `biblatex` that I just got this morning (v3.15), compiling this document with `lualatex-dev`:

```
\documentclass{article}

\usepackage{biblatex}

\begin{document}
Hi there.
\end{document}
```
produces the following error:
````
! Undefined control sequence.
<write> ...g \abx@aux@refcontext {\blx@refcontext@context 
                                                  }
````
although lualatex does not show the error.

Many thanks for looking into this!

Robert

**Comment by clason** [comment] 2020-08-25 06:45
I have the same problem with `pdflatex-dev` (on macOS); `pdflatex` works fine. (As did `pdflatex-dev` on Linux yesterday, I think, but I can't test this at the moment.)

**Comment by moewew** [comment] 2020-08-25 06:47
Thank you very much for reporting this.

My MikTeX system is a bit behind TeX live and doesn't have the newest updates, so I don't get this error yet.

Can you please add `\listfiles` to the top of the preamble and post the relevant list from the `.log` file? (You can also attach the full `.log` file if you want.)

My first guess would be that the problem is with the new hook management system (possibly in connection with `etoolbox`).

**Comment by clason** [comment] 2020-08-25 06:53
Sure: M(N)WE:
```tex
\listfiles
\documentclass{article}
\usepackage{biblatex}

\begin{document}

\printbibliography

\end{document}
```
Output is attached. 
[test.zip](https://github.com/plk/biblatex/files/5121816/test.zip)

**Comment by moewew** [comment] 2020-08-25 06:54
@josephwright Tentative research suggests tonight's `etoolbox` update might be the culprit. I just reran my `biblatex-ext` CI suite (https://travis-ci.com/github/moewew/biblatex-ext/jobs/376443714), the only package that was updated was `etoolbox` and now indeed the `latex-dev` tests fail.

I won't have time to investigate this in more depth until tonight (and even then it's going to be a pain, since my MikTeX isn't quite up to date at the moment).

**Comment by josephwright** [comment] 2020-08-25 06:55
Hmm, OK: @FrankMittelbach asked me to adjust a hook emulation, which I did - perhaps I got the wrong one.

**Comment by clason** [comment] 2020-08-25 06:56
Thanks! It's not critical since it only happens with the prerelease LaTeX format (`-dev`, where there be dragons anyway), so it's easy to work around in the interim.

**Comment by moewew** [comment] 2020-08-25 06:57
If you can find the time could you please test the MWE with the previous version of `etoolbox.sty` from https://github.com/josephwright/etoolbox/blob/ebc1aa3cc770c85103daedac1e4d8cae90d8edaa/etoolbox.sty. Download it (from https://raw.githubusercontent.com/josephwright/etoolbox/ebc1aa3cc770c85103daedac1e4d8cae90d8edaa/etoolbox.sty) and drop it in the same directory as your test `.tex` file, then try again.

**Comment by clason** [comment] 2020-08-25 06:58
You might have missed this commit: https://github.com/josephwright/etoolbox/commit/29abc29ef202966abe777f2dc8dd023de90cb375

**Comment by clason** [comment] 2020-08-25 07:00
Indeed, no errors with the old `etoolbox.sty`.

**Comment by ralessi** [comment] 2020-08-25 07:01
> Can you please add `\listfiles` to the top of the preamble and post the relevant list from the `.log` file? (You can also attach the full `.log` file if you want.)

Here you go (but I think that @clason already posted his):
````
 article.cls    2020/04/10 v1.4m Standard LaTeX document class
  size10.clo    2020/04/10 v1.4m Standard LaTeX file (size option)
biblatex.sty    2020/08/23 v3.15a programmable bibliographies (PK/MW)
pdftexcmds.sty    2020-06-27 v0.33 Utility functions of pdfTeX for LuaTeX (HO)
infwarerr.sty    2019/12/03 v1.5 Providing info/warning/error messages (HO)
   iftex.sty    2020/03/06 v1.0d TeX engine tests
 ltxcmds.sty    2019/12/15 v1.24 LaTeX kernel commands for general use (HO)
etoolbox.sty    2020/08/24 v2.5j e-TeX tools for LaTeX (JAW)
  keyval.sty    2014/10/28 v1.15 key=value parser (DPC)
kvoptions.sty    2019/11/29 v3.13 Key value format for package options (HO)
kvsetkeys.sty    2019/12/15 v1.18 Key value parser (HO)
  logreq.sty    2010/08/04 v1.0 xml request logger
  logreq.def    2010/08/04 v1.0 logreq spec v1.0
  ifthen.sty    2014/09/29 v1.1c Standard LaTeX ifthen package (DPC)
     url.sty    2013/09/16  ver 3.4  Verb mode for urls, etc.
  blx-dm.def    2020/08/23 v3.15a biblatex localization (PK/MW)
blx-unicode.def
blx-compat.def    2020/08/23 v3.15a biblatex compatibility (PK/MW)
   expl3.sty    2020-08-07 L3 programming layer (loader) 
l3backend-pdfmode.def    2020-08-07 L3 backend support: PDF mode
  xparse.sty    2020-05-15 L3 Experimental document command parser
xparse-generic.tex
blx-case-expl3.def
biblatex.def    2020/08/23 v3.15a biblatex compatibility (PK/MW)
standard.bbx    2020/08/23 v3.15a biblatex bibliography style (PK/MW)
 numeric.bbx    2020/08/23 v3.15a biblatex bibliography style (PK/MW)
 numeric.cbx    2020/08/23 v3.15a biblatex citation style (PK/MW)
biblatex.cfg    
  ts1cmr.fd    2019/12/16 v2.5j Standard LaTeX font definitions
 english.lbx    2020/08/23 v3.15a biblatex localization (PK/MW)
````

**Comment by moewew** [comment] 2020-08-25 07:01
And what about the one with the changes you linked? https://github.com/josephwright/etoolbox/blob/29abc29ef202966abe777f2dc8dd023de90cb375/etoolbox.sty

**Comment by clason** [comment] 2020-08-25 07:02
That errors out again.

**Comment by moewew** [comment] 2020-08-25 07:08
`biblatex` uses several different document hooks `\AtBeginDocument`, `\AtEndPreamble`, `\AtEndOfPackage`, `\AtEndDocument`, it is possible that the combinations don't play well with the new hook management system. I'd be OK with cleaning up some of that, but first I'd need to understand why the error appears and how the new hooks are supposed to be used.

**Comment by clason** [comment] 2020-08-25 07:11
Not sure the problem is strictly on `biblatex`'s end, since the `-dev` format worked fine with the old `etoolbox`?

(for reference: https://github.com/josephwright/etoolbox/issues/27)

**Comment by moewew** [comment] 2020-08-25 07:20
@josephwright https://github.com/latex3/latex2e/blame/lthooks2/base/lthooks.dtx suggests `begindocument/before` might have been added on 14 Aug., but the `-dev` versions people report here identifies as being from 8 Aug. Maybe the new hook isn't in the format yet? I also can't find it in https://github.com/latex3/latex2e/blob/develop/base/lthooks.dtx, but I don't really understand what `latex-dev` is based on.

**Comment by FrankMittelbach** [comment] 2020-08-25 07:41
This is precisely the problem (and my mistake). I thought it was already there for a while and so only told Joseph that theetoolbox code needs updating because of another issue using the env/document/before hook.

So it will sort itself out in a couple of days when we release the next dev release. For now

```
\usepackage{etoolbox}
\renewrobustcmd*{\AtEndPreamble}{\AddToHook{env/document/before}}%

\DebugHookOn

\usepackage{biblatex}
```
will revert it.

**Comment by FrankMittelbach** [comment] 2020-08-25 07:46
or if you like to play with the wonders of the hook system :-)
```
\AddToHook{package/after/etoolbox}{%
   \renewrobustcmd*{\AtEndPreamble}{\AddToHook{env/document/before}}}
```

**Comment by FrankMittelbach** [comment] 2020-08-25 07:57
Am 25.08.20 um 09:08 schrieb moewew:
> |biblatex| uses several different document hooks |\AtBeginDocument|, 
> |\AtEndPreamble|, |\AtEndOfPackage|, |\AtEndDocument|, it is possible 
> that the combinations don't play well with the new hook management 
> system. I'd be OK with cleaning up some of that, but first I'd need to 
> understand why the error appears and how the new hooks are supposed to 
> be used.

to summarize: the hooks work well as used in biblatex, the problem is 
that with the etoolbox update \AtEndPreamble installs into an undefined 
hook which is allowed assuming that it becomes defined later on (e.g. 
when it is from a package not yet loaded - therefore no error).

You can see it when you do \DebugHooksOn. As I said, with the upcoming 
new -dev release the hook will be there. Mea culpa for the mixup.

**Comment by ralessi** [comment] 2020-08-25 08:25
> to summarize: the hooks work well as used in biblatex, the problem is that with the etoolbox update \AtEndPreamble installs into an undefined hook which is allowed assuming that it becomes defined later on (e.g.  when it is from a package not yet loaded - therefore no error).
> 
> You can see it when you do \DebugHooksOn. As I said, with the upcoming new -dev release the hook will be there. Mea culpa for the mixup.

Now I can understand.  Thank you very much for the clarification!

**Comment by moewew** [comment] 2020-08-25 15:03
> the hooks work well as used in biblatex, the problem is that with the etoolbox update \AtEndPreamble installs into an undefined hook which is allowed assuming that it becomes defined later on (e.g. when it is from a package not yet loaded - therefore no error).

Phew, that's a relief. Thanks for the confirmation, @FrankMittelbach.

So I guess we (`biblatex`) can just wait this one out until the new `latex-dev` version is released.

I'm suprised by the number of people who actually run the `-dev` versions. That seems to suggest the plan to have people test changes earlier is working.

**Comment by FrankMittelbach** [comment] 2020-08-25 15:12
Am 25.08.20 um 17:03 schrieb moewew:
> So I guess we (|biblatex|) can just wait this one out until the new 
> |latex-dev| version is released.

yes you can

> I'm suprised by the number of people who actually run the |-dev| 
> versions. That seems to suggest the plan to have people test changes 
> earlier is working.

yeah,  and I'm grateful for that it helps a lot making things go 
smoothly. I guess the key to success is that it is dead easy to do so, 
no installation and at least with some of the major editors you have it 
even directly on the menu

**Comment by ralessi** [comment] 2020-08-25 16:21
> > I'm suprised by the number of people who actually run the |-dev| versions. That seems to suggest the plan to have people test changes earlier is working.
>
> yeah, and I'm grateful for that it helps a lot making things go smoothly. I guess the key to success is that it is dead easy to do so, no installation and at least with some of the major editors you have it even directly on the menu

Quite right.  At least as far as I am concerned, all my makefiles are
connected to `-dev`.  This is why I opened this report today in the
early morning ;)

**Comment by clason** [comment] 2020-09-01 07:34
@moewew Today's texlive update pulled in a new version of `latex-dev`, which (for me at least) fixed this issue.

**Comment by ralessi** [comment] 2020-09-01 08:06
> @moewew Today's texlive update pulled in a new version of `latex-dev`, which (for me at least) fixed this issue.

Same on my side, many thanks again!

**Comment by moewew** [comment] 2020-09-01 12:52
OK, thanks for the heads-up. Closing this.

**Closed by moewew** 2020-09-01 12:52 UTC
Labels: external
