### ISSUE TITLE
Problem with \DeclareNameFormat in v. 3.3: number of arguments have changed.

### ISSUE THREAD

**Issue by u-fischer** [plk/biblatex#372] opened 2016-03-09 17:43 UTC
The following `\DeclareNameFormat` definition (shorten from a longer version) works fine with older biblatex versions (v3.2) but fails with error in the newest version (v3.3). 

~~~~~
! Illegal parameter number in definition of \blx@defformat@d.
<to be read again> 
                   3
l.12       \usebibmacro{name:last}{#1}{#3
                                         }{#5}{#7}%
? x
~~~~~

~~~~~
\documentclass{article}
\usepackage[style=authoryear]{biblatex}

\DeclareNameFormat{sortname}{%
      \usebibmacro{name:last}{#1}{#3}{#5}{#7}%
     }
\begin{document}


\end{document}
~~~~~

From the code and the documentation I can see that the cause is a quite dramatic change in the interface of \DeclareNameFormat. It now accepts only one argument. This adaption seems to work:

~~~~~
\documentclass{article}
\usepackage[style=authoryear]{biblatex}

\DeclareNameFormat{sortname}{%
    \nameparts{#1}
     \usebibmacro{name:family}
      {\namepartfamily}
      {\namepartgiven}
      {\namepartprefix}
      {\namepartsuffix}%
     }
\begin{document}

\end{document}
~~~~~~

But how can one in this case write a suitable name format that works in the new **and** in older versions?

**Comment by plk** [comment] 2016-03-09 19:37
I am honestly not sure. I tried several ways but the internals of name formats was a major problem stopping generalisation of name handling and so I had to chose an incompatible change. If you can devise something which will provide compatibility, I can put it into 3.4 but I think it's quite hard. For biblatex-apa, I just make a requirement for biblatex 3.3+ - I think this is reasonable given how easy upgrading is with TeXLive and MikTeX etc.

**Comment by u-fischer** [comment] 2016-03-09 20:57
There are really a lot of people around which uses older system, and you can't write a biblatex style for e.g.  a journal and require that all authors use the newest version. Is/was \abx@version always a (decimal) number so that one can safely test it? Then I will implement two versions depending on the value. (But I think that they should be some examples in the docu that show how to convert one definition in the new form).

**Comment by plk** [comment] 2016-03-09 21:06
I realise it’s a bit painful but I honestly think there have to be jumps like this to get functionality in place for future expansion, otherwise, development of the system is just too slow. It’s also a matter of time - I have to put the major work into biblatex when I can and this means some releases have to be like this. I’m trying to get it to a state where things have been generalised to the point where this won’t happen again.

Anyway, \abx@version has been an integer for the last ten version or so, yes. I will keep it an integer going forward. Did you look at the RELEASE file in the documentation directory? That has a complete explanation of this change plus an example of how to change formats.

PK


> On 9 Mar 2016, at 9:57 pm, u-fischer <notifications@github.com> wrote:
> 
> There are really a lot of people around which uses older system, and you can't write a biblatex style for e.g. a journal and require that all authors use the newest version. Is/was \abx@version always a (decimal) number so that one can safely test it? Then I will implement two versions depending on the value. (But I think that they should be some examples in the docu that show how to convert one definition in the new form).
> 
> —
> Reply to this email directly or view it on GitHub.
> 

--
Dr Philip Kime

**Comment by u-fischer** [comment] 2016-03-09 22:00
I don't mind jumps, and sometimes incompatible changes are inevitable, but it would be useful to know some time before about them so that one can prepare workarounds.

**Comment by plk** [comment] 2016-03-09 22:02
That's a fair point - I did leave the DEV version for testing for many weeks and then waited a couple of weeks after SourceForge upload before TeXLive but I would like to have a mailing list or something for style authors to announce these things - any ideas?

**Comment by u-fischer** [comment] 2016-03-09 22:14
Hm, I would naturally read comp.text.tex, but probably a message based on the github account would be better. There could be here an "major change announcement" issue where the interested could comment and so get notifications. (One should probably once write the authors of the style so that they know where to look).

**Comment by josephwright** [comment] 2016-03-10 08:37
@plk  Could you elaborate on why the underlying change was needed? BibTeX has always had names as 'first part', 'last part', _etc._? (I'm trying to work out how I fix my styles, and as @u-fischer  says this becomes tricky if there are entirely incompatible formats.)

**Comment by josephwright** [comment] 2016-03-10 09:18
Re-reading the docs, I'm a bit confused. The new version has exactly the same data available as the old version that I can see (family, given, prefix, suffix), just accessed in a different way.

**Comment by u-fischer** [comment] 2016-03-10 09:45
@josephwright but the structure is obviously now extensible. Also now one no longer has to ponder if #1 or #2 is the first name. Ignoring the problem with the incompatible change I would say it is much cleaner in this way. (But I don't quite understand the \namepart command. I wonder why it isn't executed by default. Also I would problably have named  it "\getnameparts" or "\retrievenameparts").

**Comment by josephwright** [comment] 2016-03-10 09:47
@u-fischer  Sure, but that's a 'with hindsight the code should have been ....' reason, which isn't in itself enough to force a breaking change.

**Comment by u-fischer** [comment] 2016-03-10 10:34
Yes, I see problems comming from this change - quite a number of my customers are affected and I found also a number of external biblatex styles which will need to be adapted. Probably it would have been better to introduce a `\DeclareExpandedNameFormat`.

**Comment by hvoss49** [comment] 2016-03-10 11:01
It would have been very nice if such major changes had been announced weeks before in one of the main TeX newsgroups or mailing lists.

**Comment by plk** [comment] 2016-03-10 11:03
The point of this is part of the general move to use the datamodel as the source for everything. Too much was hard-coded from old bibtex defaults. The new name stuff allows for arbitrary name parts like patronymics (see the 93-nameparts example file). I know it's pain at the moment but the old bame format code was really a legacy of the ancient idea of names fron 1970s bibtex. This was really hard-coded in the structure of the code and beyond my abilty to make backwards compatible.

**Comment by plk** [comment] 2016-03-10 11:05
I did want to announce this and probably should have done - I pondered some sort of mailing list for style authors. The problem is that when I asked for feedback for the biblatex 2.0 release on these forums, I got basically no response and so assumed this wouldn't help much.

**Comment by u-fischer** [comment] 2016-03-10 11:18
93-nameparts looks interesting and I think one could (in a better way) solve some problems with japanese and transcriptions I had some time ago. Is there a way to build the name parts with a sourcemap from a bib-file? e.g. from a field "authorpatronymics={XXx and {} and YYY}". (so that one doesn't have to convert everything to xml).

**Comment by plk** [comment] 2016-03-10 11:38
That's something I'm thinking about - it is quite tricky because the btparse library parses names in the old bibtex way which is rather inflexible and will never understand anything other than the standard four bibtex name parts.

**Comment by hvoss49** [comment] 2016-03-10 13:34
If every \DeclareNameFormat needs a following \nameparts{#1} the question is why I have to do it manuallly and it is not done by the macro itself?

**Comment by plk** [comment] 2016-03-10 13:35
I am looking at this - there was some technical reason and also user reason that there were some cases when I though this would not be wanted but if this is not really the case, I'll fix it and put in a backwards compatible fix.

**Comment by hvoss49** [comment] 2016-03-10 13:46
By the way: I stopped the printing of the second edition of  "Bibliografien mit LaTeX" which is already at the printing house. I have 14 days to upload a new pdf. It would be nice that you didn't make other major changes ... ;-)

**Comment by plk** [comment] 2016-03-10 13:49
Ok, I'm sorry about this - 3.4 will have some changes too but not as major. I hope the major changes are nearly all done. We really need to think about this going forward, it's the usual OSS problem that when it gets used enough, people (not unreasonably in some respects) expect enterprise-grade release management. With a one-person, completely unpaid development/management team, that's not so easy ...

**Comment by josephwright** [comment] 2016-03-10 13:54
@plk I guess what we should do in that regard is the same as the team have in the past: ask people to write good test cases (we can use `l3build` to run them). Would a blog post be a good plan for that? I can soon write something, perhaps with a demo of how to write.

**Comment by hvoss49** [comment] 2016-03-10 13:57
I agree and I know what you are talking about ;-)  However, an annoucement, if possible long time before the official release, is a good idea!

**Comment by plk** [comment] 2016-03-10 13:57
Yes - and I would really like to create a comprehensive l3build test suite for biblatex too. I have played with it a bit and we’ve corresponded on it but it isn’t currently ideally suited to biblatex testing. I think l3build is a really good thing which we need. The reason why biber is quite stable is because I have a comprehensive test suite setup using one of the many good test modules for Perl and I’ve long wished there were something equivalent for latex.

PK

> On 10 Mar 2016, at 2:54 pm, Joseph Wright <notifications@github.com> wrote:
> 
> @plk I guess what we should do in that regard is the same as the team have in the past: ask people to write good test cases (we can use l3build to run them). Would a blog post be a good plan for that? I can soon write something, perhaps with a demo of how to write.
> 
> —
> Reply to this email directly or view it on GitHub.
> 

--
Dr Philip Kime

**Comment by plk** [comment] 2016-03-10 14:02
Don't underestimate what "a full set of tests" means though - that's a huge amount of work for all the biblatex functionality ... I have a hacked "full test" at the moment which generates all of the example files for both backends and then runs a perl program to do a character-compare on the resulting PDFs. It is somewhat useful but doesn't tell you anything about what component caused a problem.

**Comment by josephwright** [comment] 2016-03-10 14:07
@plk  Oh, certainly. The team asked for help with some LaTeX testing in ~1992 and new tests are still needed for things today :-)

**Comment by plk** [comment] 2016-03-10 20:43
In biblatex 3.4, the call to `\nameparts{#1}` in name formats is no longer required. I can think of some reasons to keep this around for the style-scope ability to inject name parts for non-western names in some use-cases but by default for now, it will be ignored if found.

**Comment by hvoss49** [comment] 2016-03-10 21:17
@plk: that's good. I just compile all of my more than 100 examples and it looks like that the changes of \DeclareFormatName is the only problem.

**Comment by plk** [comment] 2016-03-10 21:48
I posted to comp.text.tex and put the CHANGES file which details any major changes for style authors at the top-level of the SF DEV download area. I plan to also announce DEV releases on Github and put the CHANGES file in the announcement. This is done for verison 3.4.

**Comment by moewew** [comment] 2016-03-11 08:11
I just noticed that in biblatex >= 3.3 the macros `\mkbibnamelast` etc. are still defined as legacy commands and their use doesn't cause an error or warning, but redefining them doesn't do anything to the name formats. So the compilation will go through, but the output will be unexpected. That situation is a bit unfortunate. 

Not defining these quite common macros would leave users with errors. Defining them but not actually using them leaves them with wrong output.

The best solution would of course be to alias the old names to the new ones so that a change to `\mkbibnamelast` actually redefines `\mkbibnamefamily`, but I'm not sure that is possible.

**Comment by plk** [comment] 2016-03-11 09:07
This is corrected in 3.4. The old commands will issue a warning and run themselves (if already (re)defined) or the new ones (if old ones not (re)defined).

**Comment by moewew** [comment] 2016-03-11 09:15
That sounds like a very good solution. Thank you for the swift response.

**Comment by plk** [comment] 2016-03-11 09:15
Maybe you can get 3.4 and try it?

**Comment by moewew** [comment] 2016-03-11 09:28
Maybe I misunderstood, I was thinking about situations such as

```
\documentclass{article}
\usepackage{biblatex}

\renewcommand{\mkbibnamelast}[1]{\textsc{#1}}

\begin{document}
\cite{sigfridsson}
\printbibliography
\end{document} 
```

which with the new changes throws an error.

And using `\newcommand{\mkbibnamelast}[1]{\textsc{#1}}` changes nothing in the actual output.

**Comment by u-fischer** [comment] 2016-03-11 09:40
> The best solution would of course be to alias the old names to the new ones so that a change to 
> \mkbibnamelast actually redefines \mkbibnamefamily, but I'm not sure that is possible.

If you mean that `\renewcommand\mkbibnamelast{..}` should somehow affect \mkbibnamefamily: \mkbibnamefamily could tests the definition of \mkbibnamelast and do something depending in its status (e.g. if is not empty). Imho not a bad idea, but it shouldn't try to use the redefinition but simply throw an error and tell people to redefine \mkbibnamefamily instead or you will never get rid of the older commands.

**Comment by moewew** [comment] 2016-03-11 09:51
The best solution would be to throw an error, absolutely. People should use the new commands. But that will break even more styles than the `\DeclareNameFormat` change since `\mkbibname...` was a higher lever command that is used quite often.

**Comment by hvoss49** [comment] 2016-03-11 09:55
It is obvious that _all_ `last`, `first`, ... have to be changed to `family`, `given`.

**Comment by plk** [comment] 2016-03-11 10:02
Try 3.4 now. It should now only generate warnings on redefinition or use of the old macros. We just have to agree what should happen in addition.

**Comment by moewew** [comment] 2016-03-11 10:21
Works as advertised now.

The user friendly approach would be to redefine the new commands appropriately, I believe, but I can see that this could lead to people never using the new names.

**Comment by hvoss49** [comment] 2016-03-11 10:23
As you already pointed out the Perl module btparse has a hardcoded name structure. This is the reason why I think that it may be useful in this case (which is the most used one) the macros should simply be copied. Datamodel `bibtex`-> `\let\mkbibnamelast\mkbibnamefamily...`

**Comment by hvoss49** [comment] 2016-03-11 14:30
In the following example everything is fine, but with `\mkbibnamelast`, but with `\mkbibnamefamily` I get a problem with `family_i` (underscore)  from the bcf file. What's wrong?

```
\documentclass{article}
\usepackage[T1]{fontenc}
\usepackage[utf8]{inputenc}
\usepackage[ngerman]{babel}
\usepackage[autostyle]{csquotes}

\usepackage{biblatex}

\DeclareNameFormat{sortname+1stcaps}{%
 \nameparts{#1}%
 \expandafter\ifnum\value{listcount}=1\relax
   \let\mkbibnamefamily\textsc
   \usebibmacro{name:family-given}{\namepartfamily}{\namepartgiven}{\namepartprefix}{\namepartsuffix}%
   \ifblank{\namepartgiven\namepartprefix}{}{\usebibmacro{name:revsdelim}}%
 \else
   \renewcommand*\mkbibnamelast[1]{#1}%
  % \renewcommand*\mkbibnamefamily[1]{#1}%
   \usebibmacro{name:given-family}{\namepartfamily}{\namepartgiven}{\namepartprefix}{\namepartsuffix}%
 \fi
 \usebibmacro{name:andothers}
}
\DeclareNameAlias{author}{sortname+1stcaps}
\DeclareNameAlias{editor}{sortname+1stcaps}
\addbibresource{biblatex-examples.bib}

\begin{document}
foo~\cite{kastenholz} 
\printbibliography
\end{document}
```

pdflatex - biber -pdflatex 

```
(./04-10-12.aux) (./04-10-12.bbl)
! Missing $ inserted.
<inserted text> 
                $
l.30 \end
         {document}

```

**Comment by u-fischer** [comment] 2016-03-11 14:44
#1 is not a simple name, it contains the complete name info in a special format. You probably want 

      `\renewcommand*\mkbibnamefamily[1]{\namepartfamily}`

**Comment by hvoss49** [comment] 2016-03-11 14:47
ah yes ... thanks

**Comment by moewew** [comment] 2016-03-11 14:48
Or you could go with `\renewcommand*\mkbibnamefamily[1]{##1}`

**Comment by plk** [comment] 2016-03-11 14:54
@moewew - I suggest that useage or redef of the legacy `\mkbibname*`commands give the warnings and uses/redefs the new command, telling the user that's what's happening.

**Comment by moewew** [comment] 2016-03-11 15:10
That sounds great, I just pulled the latest commits from github and it works almost as I expected. It is just that `\renewcommand*\mkbibnamelast[1]{\textsc{#1}}` doesn't change `\mkbibnamefamily` as I thought it would.

```
\documentclass[10pt,a4paper]{article}
\usepackage[utf8]{inputenc}
\usepackage[T1]{fontenc}
\usepackage[style=authortitle,backend=biber]{biblatex}

\addbibresource{biblatex-examples.bib}

\renewcommand*\mkbibnamelast[1]{\textsc{#1}}

\begin{document}
\cite{sigfridsson}

\printbibliography
\end{document}
```

**Comment by plk** [comment] 2016-03-11 16:05
That's up for discussion - we can do that too.

**Comment by moewew** [comment] 2016-03-11 16:12
Oh, I'm sorry, I thought it would already do that. That would be even more user friendly in my opinion.

I would prefer a way where there is (1) either a fatal error when using `\mkbibnamelast` or (2) the user is warned but, the right thing is done in the background.

Issuing a warning and then not changing the macros to achieve the expected format is a bit dangerous in that warnings are often ignored (and not even read).

In the current warning message, the "Using `\mkbibnamefamily`." made me think I would actually be redefining `\mkbibnamefamily` when I renewed `\mkbibnamelast`.

**Comment by plk** [comment] 2016-03-11 18:08
That's what it does now - can you check? It should warn and redefine `\mkbibnamefamily` to the original definiton of `\mkbibnamelast` and also issue a warning when `\mkbibnamelast` is used (in addition to the warning at end of preamble when it is detected that it's been redefined).

**Comment by moewew** [comment] 2016-03-11 18:16
I noticed that you had committed a change to that respect. Things work as advertised now, and I think the solution you have implemented is the most user friendly in that situation.

**Comment by u-fischer** [comment] 2016-03-12 13:15
Btw: The current documentation (in texlive) has typos. It writes `\makebibnamefamily` instead of `\mkbibnamefamily`.

**Comment by plk** [comment] 2016-03-12 13:18
Typos corrected in DEV.

**Comment by simifilm** [comment] 2016-03-13 15:48
Although it's not really the subject of this issue, I wanted to chime in on the transition problem we encountered. Only speaking for myself, I find using dev builds of biblatex quite challengig. I am always up to date when it comes to biber. Updating biber works quite well. But I find updating biblatex a hassle. There are several build scripts (build.lua, build.sh), and obviously you must do something with version numbers to succeed. I just build a new version, and this won't run because there are problems with the version numbers. I rarely tested biblatex versions in the past because I was simply unable to build them myself. Making this process easier would at least make me test changes to biblatex.

**Comment by josephwright** [comment] 2016-03-13 15:51
@simifilm Suggest you open a new issue for that :-)

**Comment by plk** [comment] 2016-03-13 15:51
That's a really good point. It's actually quite easy as long as you have bash installed. Checkout the dev branch and in the root do:

```
./obuild/build.sh install <version> <texmfroot where you want to install>
```

for example, currently for the 3.4 dev version I am using (a lot at the moment ...):

```
./obuild/build.sh install 3.4 ~/texmf
```

**Comment by u-fischer** [comment] 2016-03-13 19:48
@simifilm Can't you use the tds at https://sourceforge.net/projects/biblatex/files/development/ ?

**Comment by simifilm** [comment] 2016-03-13 22:29
@u-fischer I wasn't even aware they existed. Are they always up to date?

**Comment by plk** [comment] 2016-03-13 22:31
They are generally very up to date. Pulling from github is more risky as it's really bleeding edge. I upload a "stable" dev version to SF quite often and this automatically creates TDS and flat distributions

**Comment by hvoss49** [comment] 2016-03-13 22:38
`./obuild/build.sh install 3.4 `kpsewhich -var-value TEXMFLOCAL` 

for an installtion into TEXMFLOCAL of TeXLive

**Comment by moewew** [comment] 2016-03-14 11:56
Is `\ifblx@load@version@legacy` the "official" way to check for the back-end? It would probably be more comfortable for styles authors to have a documented (and future-proof) way to check if Biber/BibTeX is used. I'm also asking because of http://tex.stackexchange.com/q/298398/ where `biblatex-chicago` was a bit thrown because `\ifblx@load@version@one` was renamed and I noted that josephwright uses `\@ifpackageloaded{biblatex_legacy} ` in his styles.

**Comment by hvoss49** [comment] 2016-03-14 12:01
From my point of view the support for the _program_  bibtex should be dropped ...

**Comment by josephwright** [comment] 2016-03-14 12:17
@moewew  I've gone for `biblatex_legacy` as this uses no internals and will cope with a re-merger of the code paths

**Comment by josephwright** [comment] 2016-03-14 12:19
@hvoss49 That would be a massive issue in terms of stability but also would put a lot of people (including me) off the entire project. BibTeX is _much_ faster than Biber and is _rock solid_ stable: for those of us not needing clever sorting, new features, _etc._, BibTeX is ideal.  (As a _user_, I want `biblatex` for the stuff that works fine with both back-ends.)

**Comment by hvoss49** [comment] 2016-03-14 12:21
Oh, I suppose you _never_ had a bibliography with czech or japanese or ... names.

**Comment by josephwright** [comment] 2016-03-14 12:25
@hvoss49 Like many LaTeX users, I'm in the physical sciences (and using pdfTeX): any accents or whatever are covered by the `inputenc` mechanisms/LICR and all names are given in Latin characters (it's not been so long that we've even been allowed accents in publications). Moreover, there's no sorting to do in chemistry: we use numbered styles. Other physical sciences do do sorting but pretty 'easy' versions, which are readily covered using BibTeX.

I don't see my use (as a 'user') as atypical, though of course I'm well aware that there are lots fo things that BibTeX can't do.

**Comment by plk** [comment] 2016-03-14 12:37
I have some sympathy for both @hvoss49 and @josephwright here. bibtex isn't really being used by biblatex in any real sense, it's being used just for it's incidental sorting capability which is behind the times. It is faster but for a batch program, I'm not sure that matters too much. As far as solodity goes, in the simpler backend use cases which @josephwright mentions, biber is also solid - I have a large test suite of regression tests going back over five years of features which are run before every dev upload. Bugs are fairly rare, especially in core features. It would be nice to have some data on backend use but that's hard to obtain.

**Comment by hvoss49** [comment] 2016-03-14 12:42
every 7-Bit program ist fast, so it is not really surprising that bibtex is fast. It is the same for tex->pdftex->xetex->luatex (from fast to slow, or better from fast to not-so-fast ;-)

**Comment by plk** [comment] 2016-03-14 12:43
How about a thread on comp.text.tex asking for opinions about dropping bibtex as a backend?

**Comment by u-fischer** [comment] 2016-03-14 12:44
@josephwright I'm wouldn't say that you are atypical, but you aren't typical either. In german *every* bib has to use accented chars in names and other places, and authoryear citations are quite common, so you need reliable utf8-sorting and -handling. Beside this I don't think that speed matter so much in this case. bibtex/biber don't need to run at every compilation. And biber gives better messages when entries are wrong ;-).

**Comment by johannesbottcher** [comment] 2016-03-14 13:45
A quite possible example for german. Of course some programs will export pure ascii, but some will have utf8-databases. 

```lang=latex 
\begin{filecontents}{\jobname.bib}
	@book{wombat,
		author = {Bodo Bäcker},
		title = {the wombat stories},
		date = {2016},
	}
	@book{capybara,
		author = {Bernd Bolle},
		title = {capybara},
		date = {2016},
	}
\end{filecontents}
\documentclass{article}
\usepackage[utf8]{inputenc}
\usepackage[T1]{fontenc}
\usepackage[
	backend=bibtex,
%	backend=biber,
%	sortlocale=de_DE_phonebook,
style=authoryear]{biblatex}
\addbibresource{\jobname.bib}
\nocite{*}
\begin{document}
\printbibliography
\end{document}
```


Concerning speed: My machine is so slow that biber sometimes needs several seconds till any terminal output can be seen. Would it be possible to instantly give feedback, for example *this is biber*? This is the wrong repo though, but it seems to fit right now.

**Comment by plk** [comment] 2016-03-14 14:13
I could add a rapid output line but have you tried the `--fastsort` option?

**Comment by johannesbottcher** [comment] 2016-03-14 14:31
Marginal difference 

with `--fastsort`
```
real	0m3.390s
user	0m3.176s
sys	0m0.148s
```
without `--fastsort`
```
real	0m3.445s
user	0m3.268s
sys	0m0.112s
```



Maybe it really is time for a faster machine or at least a fresh installation.

**Comment by josephwright** [comment] 2016-03-14 14:39
@plk  On 'stability' I was not meaning to be critical of Biber. BibTeX is stable in the sense that in the time I've been involved in LaTeX at all there has been _one_ update  (v0.99c to v0.99d, for long URLs). There are unlikely to be any further code changes at all, so a file which uses BibTeX today will be processed _the same_ in say 20 years time. 

@hvoss49 Sure, and one can argue that by historical standards the issue here is trivial. However, people do mention performance not only of Biber but of other engines vs. pdfTeX, and even of DVI vs. PDF mode, _etc._

@u-fischer  My BibTeX database does have accents :-) It's notable that _a lot_ of classical BibTeX styles exist and work 'well enough' not only in English but also for other western European languages. I'm not arguing at all that Biber isn't better-able to cope with the complexities here, only that for many uses BibTeX is OK.

The key point for me here is stability. Existing documents using BibTeX as their back-end should continue to process successfully. Biber doesn't _always_ do exactly the same thing as BibTeX for cases that the two can both handle. For example, it will choke on some database entries that BibTeX handles despite syntax issues. Dropping the back-end entirely would mean breaking that, which really should force a new name for the package, _etc._: I don't think that is at all desirable (style file sharing would become very complex). Simply 'freezing' the BibTeX code was the original plan to do this, but that then runs into issues when breaking syntax changes are needed from the Biber side.

**Comment by johannesbottcher** [comment] 2016-03-14 14:53
I am agreeing with the last paragraph above. If support for BibTeX is frozen, it should be moved into a new package, so that it can be dealt with easily. 
Completely dropping BibTeX ... not so good, i think.

**Comment by josephwright** [comment] 2016-03-14 15:06
I note @plk  has raised the discussion issue on c.t.t.: suggest everyone takes a look (https://groups.google.com/forum/#!topic/comp.text.tex/3tR5B7vDr-w for those people without a Usenet reader).

**Comment by u-fischer** [comment] 2016-03-14 15:17
@josephwright I'm not trying to convince you (or someone else) to drop bibtex. I'm only saying that for us german biber is the better choice.  Btw: I remember quite well the discussion 3 years ago when it was me who fighted for the bibtex users: e.g. http://newsgroups.derkeiler.com/Archive/Comp/comp.text.tex/2012-04/msg00109.html

**Comment by josephwright** [comment] 2016-03-14 15:20
@johannesbottcher It's tricky, though, as sometimes you do have to change things (which is where we came in with this question!). Certainly if I were starting today I'd need a _lot_ of convincing to use BibTeX, in the same way for my LaTeX3 work I'm still very unsure about what to do with pdfTeX (8-bit but again fast and stable) vs. XeTeX/LuaTeX (Unicode, being developed, both not entirely without things to concern the team).

@u-fischer Sure :-) I find myself of course arguing for more work for me: dropping BibTeX entirely would be a much easier path, and there is an argument for it, while keeping it working clearly needs some significant effort if the main development is to continue being able to extend the approach.

**Comment by johannesbottcher** [comment] 2016-03-14 15:55
@plk Do you have an estimate on the time lapse till something serious changes? I guess this will not happen within the next month, but half a year? One year? I am just asking out of curiosity.

**Comment by plk** [comment] 2016-03-14 16:17
Well, given @josephwright's estimate of about two months work to bring the bibtex backend up to date with internal changes etc, this is the time to have the discussion. It all depends on the user feedback really.

**Comment by josephwright** [comment] 2016-03-14 16:54
@johannesbottcher As @plk notes, I think I need at least a couple of months to realign the two backend paths: the bulk is easy (unchanged) but getting BibTeX 'right' (enough) needs effort. Certainly if there's a change of status to come I think a long lead would be needed.

**Comment by plk** [comment] 2016-03-16 21:21
I'm closing this for now - the issue is known and the thread is a bit general now.

**Closed by plk** 2016-03-16 21:21 UTC
