### ISSUE TITLE
Polyglossia, autolang and language

### ISSUE THREAD

**Issue by maieul** [plk/biblatex#698] opened 2018-01-28 17:19 UTC
Consider this MWE
```
\documentclass{article}
\usepackage{filecontents}
\begin{filecontents}{\jobname.bib}
@book{toto,
  title={toto}
}
\end{filecontents}
\usepackage{polyglossia}
\setmainlanguage{french}
\usepackage[autolang=hyphen,language=french]{biblatex}
\addbibresource{\jobname.bib}
\begin{document}
\cite{toto}
\end{document}

```

With biblatex 3.9, at the run after the biber run, we get undefined command erro.

If we dont ONE of this following thins
- switch to babel
- suppresse language option
- suppression autolang option

We don't get the problem anymore.

**Comment by moewew** [comment] 2018-01-28 17:29
Not our fault (well partly my fault, but this has nothing to do with `biblatex`).

```
\documentclass{article}
\usepackage{polyglossia}
\setmainlanguage{french}
\begin{document}
\begin{hyphenrules}{french}toto\end{hypnerules}
\end{document}
```

reproduces the same problem.

See https://tex.stackexchange.com/q/400986/35864.

This error came about because of https://tex.stackexchange.com/a/396614/35864 and https://github.com/latex3/latex2e/commit/8b0b10baea14df33e76db82b89ebdb11f8cfc145. `hyphenrules` now uses certain private macros instead of kernel commands. Apparently `polyglossia` doesn't like that.

You could try to complain to the `polyglossia` people (https://github.com/reutenauer/polyglossia/issues), but I'm not sure how quickly things will be fixed then. Or to the `babel` people: https://github.com/latex3/latex2e/issues

**Comment by maieul** [comment] 2018-01-28 17:34
Unfortunaly, @reutenaeur seems to have forgetten polyglossia
maintenance.

I have asked to him to send on CTAN a bugfix (that I made) since 6 month
ago, and I didn't get any answer. I think we could considerer
polyglossia is unmaintened. I will look on babel feature, which seems to
be more powerful, now, than polyglossia.

Best regards

**Comment by moewew** [comment] 2018-01-28 17:36
Yes I know this is an annoyance for some `polyglossia` users.

Since `babel`'s `hyphenrules` definitions are taken from the format directly by `polyglossia` you could raise this with Javier https://github.com/latex3/latex2e/issues. Ulrike told me she thinks that `hyphenrules` should not us internal commands.

**Comment by maieul** [comment] 2018-01-28 17:38
Unfortunatly, I have now time now to look on the relationship between
all package  for hyphen rules.

**Comment by moewew** [comment] 2018-01-28 17:50
OK. Since this is not a `biblatex` problem, I'm closing this here.

**Closed by moewew** 2018-01-28 17:50 UTC

**Comment by moewew** [comment] 2018-02-02 10:33
I complained to the `babel` developer, but I'm not sure if the report will be considered valid.

**Comment by moewew** [comment] 2018-02-16 09:51
`babel` 3.18 fixes this problem. `polyglossia` can again use `hyphenrules`. See https://github.com/latex3/latex2e/issues/17
