### ISSUE TITLE
replacing literal type

### ISSUE THREAD

**Issue by 2011** [plk/biblatex#884] opened 2019-04-24 15:23 UTC
Hi,

I am struggling to find (and format) the biblatex replacement for the bibtex literal type of bibliography entry that I was using for the odd legal citation. I need:

(_Alice v. Bob,_ 2000)

and / or

_Alice v. Bob_ (2000)

in the text, and in the reference entry, I need:

Alice v. Bob, 500 U.S. 123 (2000).

Can anyone help? Thank you in advance.

**Comment by 2011** [comment] 2019-04-24 15:24
Forgot to mention (if it matters), I am using style=apa.

**Comment by moewew** [comment] 2019-04-24 15:30
What do you mean by 'literal type' of BibTeX? Do you have a working example of this type in action?

Anyway, standard `biblatex` knows the types `@jurisdiction`, `@legal` and `@legislation`, but it treats them as it would treat `@misc` and has no special features set up for legal citations.

Some contributed styles have more support for legal citations. You may be interested in https://tex.stackexchange.com/q/437824/35864. https://tex.stackexchange.com/q/438759/35864 shows how you could get manual 'freeform' citations.

Please note that issues about `biblatex-apa` should be logged at https://github.com/plk/biblatex-apa/issues. It should be noted though that in general the issues logged here on GitHub should be about feature suggestions/requests and bug reports. If you need advice or general help, then one of the many LaTeX forums like https://latex.org/, https://tex.stackexchange.com/ or https://groups.google.com/forum/#!forum/comp.text.tex is more appropriate.

**Comment by 2011** [comment] 2019-04-24 22:55
Thank you (again) for the prompt reply. :)

BibTeX has a "literal" type the I could make a bibliography entry such as:

    @literal{Alice:2000,
    firstkey = {\textit{Alice v. Bob}},
    key = {\textit{Alice v. Bob}},
    text = {Alice v. Bob, 500 U.S. 123 (2000).},
    year = {2000},
    }

Basic, but perfect for any type of unusual cases. The text field becomes the entire reference in the reference list. The firstkey field is the author for the first citation, and the key field is the author for subsequent citations.

Again, I am all new to this, so I basically don't know what I am doing. I am trying to figure out how to replicate that in biblatex. I am getting the following warning (just changing literal to jurisdiction (I am using overleaf for now, but will do a local install with a new computer in a couple of months).

> Package biblatex Warning: No driver for entry type 'jurisdiction'.
(biblatex)                Using fallback driver on input line 89.

I assume that is the expected behavior.

I looked at that page, but it is not clear to me how to do just a couple of citations in another style (in the middle of about thirty total citations).

Thanks again for your help.

**Comment by moewew** [comment] 2019-04-25 05:32
As far as I can see, only `apacite`'s BibTeX styles support an `@literal` type as you used it, so that is far from a general BibTeX feature. Standard `biblatex` does not have such a feature. The question on TeX.SX that I already linked (https://tex.stackexchange.com/q/438759/35864) shows how you could go about getting it. Since those 'free-form' citations go against the spirit of `biblatex` and its semantic data model, I'm not too excited about adding such a type to the standard styles. They also bring about new implementational challenges and I fear that supporting them would mean larger changes in many styles, which could break people's documents, styles and customisations.

Yes, the warning you get is expected behaviour. The standard styles 'know' the type `@jurisdiction`, but they have nothing specific set up for it and will use the `@misc` driver.

**Comment by 2011** [comment] 2019-04-25 15:02
Sorry, I have literally spent hours trying to get this to work. :(

Remember that I am using style=apa (absolutely required).

For the first method, I tried a added this to the .bib file (did not create a new or inline file):

    @misc{Alice:2000,
    shorthand = {\textit{Alice v. Bob, 2000)},
    note = {\ifcitation{\textit{Alice v. Bob, 2000}}{Alice v. Bob, 500 U.S. 123 (2000)}},
    }

This line got a warning:

    \renewbibmacro*{shorthandintro}{}
    Package biblatex Warning: Macro 'shorthandintro*' undefined.
    (biblatex)                Using \newbibmacro on input line 27.

I can almost get it, but there are two problems:
1. There are brackets around the text (shorthand) citation.
2. The reference entry begins with "(n.d.)." (or the year - at the beginning of the reference, which is the problem, if I put it in).

So I added the whole @freeform definition with:

    @freeform{Alice:2000,
    bibliography = {Alice v. Bob, 500 U.S. 123 (2000).},
    cite = {\textit{Alice v. Bob}},
    firstcite = {\textit{Alice v. Bob}},
    }

Again, I get warnings (I assume this has something to do with "style=apa" and not "style=verbose").

    Package biblatex Warning: Macro 'cite:full' undefined.
    (biblatex)                Using \newbibmacro on input line 59.
    
    Package biblatex Warning: Macro 'cite:short' undefined.
    (biblatex)                Using \newbibmacro on input line 71.

That seems much farther away. The text citation is nothing but "n.d." and the reference entry is nothing but "(Cit. on p. 10).

**Comment by moewew** [comment] 2019-04-25 15:18
Yes, the implementation I linked is style specific. For `apa` you could try something like.

```latex
\documentclass[british]{article}
\usepackage[T1]{fontenc}
\usepackage[utf8]{inputenc}
\usepackage{babel}
\usepackage{csquotes}

\usepackage{filecontents}
\begin{filecontents}{freeform.dbx}
\DeclareDatamodelEntrytypes{freeform}
\DeclareDatamodelFields[type=field,datatype=literal]{
  bibliography,
  cite,
  firstcite,
}
\DeclareDatamodelEntryfields[freeform]{
  bibliography,
  cite,
  firstcite,
  sortkey,
}
\end{filecontents}

\usepackage[style=apa, backend=biber, datamodel=freeform]{biblatex}

\DeclareBibliographyDriver{freeform}{%
  \usebibmacro{bibindex}%
  \usebibmacro{begentry}%
  \printfield{bibliography}%
  \newunit\newblock
  \iftoggle{bbx:related}
    {\usebibmacro{related:init}%
     \usebibmacro{related}}
    {}%
  \usebibmacro{apa:finpunct}%
  \usebibmacro{apa:pageref}%
  \usebibmacro{finentry}}


\letbibmacro{cite:standard}{cite}
\letbibmacro{textcite:standard}{textcite}

\renewbibmacro*{cite}{%
  \ifentrytype{freeform}
    {\iffieldundef{firstcite}
       {\printfield{cite}}
       {\printfield{firstcite}}}
    {\usebibmacro{cite:standard}}}

\renewbibmacro*{texcite}{%
  \ifentrytype{freeform}
    {\iffieldundef{firstcite}
       {\printfield{cite}}
       {\printfield{firstcite}}}
    {\usebibmacro{texcite:standard}}}

\DeclareSourcemap{
  \maps[datatype=bibtex,overwrite=false]{
    \map{
      \pertype{freeform}
      \step[fieldsource=bibliography]
      \step[fieldset=sortkey, origfieldval]
    }
  }
}

\begin{filecontents}{\jobname.bib}
@freeform{Alice:2000,
  bibliography = {Alice v. Bob, 500 U.S. 123 (2000).},
  cite         = {\textit{Alice v. Bob}, 2000},
}
\end{filecontents}

\addbibresource{\jobname.bib}


\begin{document}
Lorem \autocite{Alice:2000} ipsum \autocite{Alice:2000}
\printbibliography
\end{document}
```

**Comment by 2011** [comment] 2019-04-25 15:53
Wow! Getting much closer. Actually, the freeforms are fine, but the \parencite(Smith:2010) have all disappeared (the \textcite(Smith:2010) still work).

Oops, it is actually worse after your edit. Now \textcite no longer works.

This is the error I am getting:

    ! Undefined control sequence.
    l.64 \letbibmacro
                     {cite:standard}{cite}
    The control sequence at the end of the top line
    of your error message was never \def'ed. If you have
    misspelled it (e.g., `\hobx'), type `I' and the correct
    spelling (e.g., `I\hbox'). Otherwise just continue,
    and I'll forget about whatever was undefined.
    
    ! LaTeX Error: Missing \begin{document}.
    
    See the LaTeX manual or LaTeX Companion for explanation.
    Type  H <return>  for immediate help.
     ...                                              
                                                      
    l.64 \letbibmacro{c
                       ite:standard}{cite}
    You're in trouble here.  Try typing  <return>  to proceed.
    If that doesn't work, type  X <return>  to quit.
    
    ! Undefined control sequence.
    l.65 \letbibmacro
                     {textcite:standard}{textcite}
    The control sequence at the end of the top line
    of your error message was never \def'ed. If you have
    misspelled it (e.g., `\hobx'), type `I' and the correct
    spelling (e.g., `I\hbox'). Otherwise just continue,
    and I'll forget about whatever was undefined.

**Comment by 2011** [comment] 2019-04-25 16:26
I am absolutely amazed that you could throw down that block of code in just a few minutes that pretty much fixed absolutely everything. I have a lot to learn. :)

It wasn't quite perfect - I had to correct "v. " to "v.\ " (if I recall, the old BibTex knew that a period in an in-text citation was not the end of a sentence), but I spotted that right away, and it was a trivial fix.

Thank you **SO** much.

**Comment by moewew** [comment] 2019-04-25 17:28
Yes, `biblatex` does not change the space factor in citations, it only does that for the bibliography. That's why I used `v.~` in the edit.

**Comment by 2011** [comment] 2019-04-27 00:29
Okay, I thought I had everything absolutely perfect, and on a final proofread, I noticed that (in the references section) that this is getting sorted between "United States" and "Wu" (there are about 30 references all together), and I have no idea why. I will put the exact .bib entry here (and ask why here in the off chance that some of the other changes I made, such as the freeform type, _might_ be causing it).

    @article{ChaosComputerClub:2017,
    doi = {10.1016/S0969-4765(17)30102-9},
    journal = {Biometric Technology Today},
    number = {6},
    pages = {1 - 2},
    title = {{Chaos Computer Club} spoofs {Samsung Galaxy S8} iris recognition system},
    volume = {2017},
    year = {2017},
    }

**Comment by moewew** [comment] 2019-04-27 04:51
Ah yes, we need to copy the entire data model of `biblatex-apa` so the sorting does not go pear-shaped.

```latex
\documentclass[british]{article}
\usepackage[T1]{fontenc}
\usepackage[utf8]{inputenc}
\usepackage{babel}
\usepackage{csquotes}

\usepackage{filecontents}
\begin{filecontents}{freeform-apa.dbx}
\ProvidesFile{freeform-apa.dbx}[2019/04/27 v0.1 Freeform citations for APA]
\DeclareDatamodelEntrytypes{
  letters,
  data,
  freeform,
  newsarticle}

\DeclareDatamodelFields[type=list, datatype=name]{
  with,
  writer,
  producer,
  execproducer,
  director}

\DeclareDatamodelFields[type=field, datatype=literal]{
  bibliography,
  cite,
  firstcite,
  abstractloc,
  titleisdescription,
  newspaper,
  urldescription}

\DeclareDatamodelFields[type=field, datatype=verbatim]{
  abstracturl}

\DeclareDatamodelEntryfields{
  titleisdescription,
  with,
  abstractloc,
  abstracturl,
  urldescription}

\DeclareDatamodelEntryfields[video]{
  writer,
  producer,
  execproducer,
  director}

\DeclareDatamodelEntryfields[newsarticle]{
  author,
  newspaper,
  title,
  day,
  endday,
  endmonth,
  endyear,
  month,
  year,
  addendum,
  doi,
  editor,
  editora,
  editorb,
  editorc,
  editoratype,
  editorbtype,
  editorctype,
  eid,
  eprint,
  eprintclass,
  eprinttype,
  issn,
  issue,
  issuetitle,
  issuesubtitle,
  language,
  note,
  number,
  origlanguage,
  pages,
  series,
  subtitle,
  titleaddon,
  translator,
  url,
  urlday,
  urlendday,
  urlendmonth,
  urlendyear,
  urlmonth,
  urlyear,
  volume}

\DeclareDatamodelEntryfields[data]{
  title,
  day,
  endday,
  endmonth,
  endyear,
  day,
  endday,
  endmonth,
  endyear,
  month,
  year,
  addendum,
  author,
  language,
  location,
  note,
  organization,
  pubstate,
  subtitle,
  titleaddon,
  type,
  url,
  urlday,
  urlendday,
  urlendmonth,
  urlendyear,
  urlmonth,
  urlyear,
  version}

\DeclareDatamodelEntryfields[freeform]{
  bibliography,
  cite,
  firstcite,
  sortkey}
\end{filecontents}

\usepackage[style=apa, backend=biber, datamodel=freeform-apa]{biblatex}

\DeclareBibliographyDriver{freeform}{%
  \usebibmacro{bibindex}%
  \usebibmacro{begentry}%
  \printfield{bibliography}%
  \newunit\newblock
  \iftoggle{bbx:related}
    {\usebibmacro{related:init}%
     \usebibmacro{related}}
    {}%
  \usebibmacro{apa:finpunct}%
  \usebibmacro{apa:pageref}%
  \usebibmacro{finentry}}


\letbibmacro{cite:standard}{cite}
\letbibmacro{textcite:standard}{textcite}

\renewbibmacro*{cite}{%
  \ifentrytype{freeform}
    {\ifboolexpr{    not test {\ifciteseen}
                 and not test {\iffieldundef{firstcite}}}
       {\printfield{firstcite}}
       {\printfield{cite}}%
     \setunit{\multicitedelim}}
    {\usebibmacro{cite:standard}}}

\renewbibmacro*{textcite}{%
  \ifentrytype{freeform}
    {\ifboolexpr{    not test {\ifciteseen}
                 and not test {\iffieldundef{firstcite}}}
       {\printfield{firstcite}}
       {\printfield{cite}}}
    {\usebibmacro{textcite:standard}}}


\DeclareSourcemap{
  \maps[datatype=bibtex,overwrite=false]{
    \map{
      \pertype{freeform}
      \step[fieldsource=bibliography, final]
      \step[fieldset=sortkey, origfieldval]
    }
  }
}

\begin{filecontents}{\jobname.bib}
@article{ChaosComputerClub:2017,
  doi     = {10.1016/S0969-4765(17)30102-9},
  journal = {Biometric Technology Today},
  number  = {6},
  pages   = {1 - 2},
  title   = {{Chaos Computer Club} spoofs {Samsung Galaxy S8} iris recognition system},
  volume  = {2017},
  year    = {2017},
}
\end{filecontents}

\addbibresource{\jobname.bib}
\addbibresource{biblatex-examples.bib}


\begin{document}
\cite{sigfridsson,ChaosComputerClub:2017}
\nocite{*}
\printbibliography
\end{document}
```

**Comment by 2011** [comment] 2019-04-27 06:13
That worked, of course (thank you one more time). A few questions just to help me understand things (and I did look at plk/biber#262).

1. Do you have any idea why that entry was being sorted as it was (I just don't see anything in the entire entry in the [uvw] range)?

2. Why was just that one entry out of place?

3. In you fix, why did you just include a few types (and not things such a book or report)?

4. Is there a distinction between newsarticle and article?

**Comment by moewew** [comment] 2019-04-27 06:29
I'm not entirely sure if I'm right but my hunch is as follows

`apa`'s sorting scheme is
```latex
\DeclareSortingTemplate{apa}{
  \sort{
    \field{presort}
  }
  \sort[final]{
    \field{sortkey}
  }
  \sort{
    \field{sortname}
    \field{author}
    \field{editor}
    \field{translator}
    \field{writer}
    \field{director}
    \field{producer}
    \field{execproducer}
    \field{sorttitle}
    \field{title}
  }
  \sort{
    \field{pubstate}
  }
  \sort{
    \field{sortyear}
    \field{year}
    \literal{-2000000000}% APA has "nodates" coming first
  }
  \sort{
    \field{sorttitle}
    \field{title}
  }
  \sort{
    \field{volume}
    \literal{0}
  }
}
```
You will note that the third `\sort` group contains `\field{writer}`. Note that all `\field`s before `writer` are standard `biblatex` fields. But `writer`, `director`, `producer` and `execproducer` are specific to `biblatex-apa`.

If I understand what happens correctly Biber will try to resolve the argument of `\field` as a field *value* (i.e. it will take the author name for `\field{author}`), but if the argument is not a known field name it will treat it as a *literal string*. That means that if we use a field name that has not been declared as a field to Biber in the data model, Biber will treat it as a string (that is why I opened https://github.com/plk/biber/issues/262).

Since `writer` is not known to the standard data model `\field{writer}` has the same effect as `\literal{writer}`. That is to say an entry without `sortname`, `author`, `editor` and `translator` will be treated as if it had a `sortname = {writer},` in its `.bib` entry. Entries with `sortname`, `author`, `editor` or `translator` don't really notice the problem since those fields take precedence over `\field{writer}`. If we want `\field{writer}` to work as expected and take the contents of the `writer` name field, we need to make sure that Biber knows that `writer` is a valid field. That happens via the data model file (`.dbx`).

1. This should explain point 1.
2. This should also explain point 2 since this entry is quite probably the only entry in your bibliography that has neither `sortname`, nor `author`, `editor` or `translator`.
3. The new data model only needs to include the stuff *additional* to the standard data model. So I just copied https://github.com/plk/biblatex-apa/blob/master/tex/latex/biblatex-apa/dbx/apa.dbx and added the `@freeform` stuff.
4. This is specific to `biblatex-apa`. Yes, there is. Roughly `@newsarticle` is for articles in daily or weekly (say) newspaper or magazine publications, while `@article` is supposed to be used for articles in academic journals.

**Comment by 2011** [comment] 2019-04-27 11:10
It sure sounds like you have it right. :)

This is the first time I have used LaTeX for anything (didn't really know about it before), and although I have struggle with a few things, I have become a fan. I will use it again (several times in the very near future).

You can probably close both of these questions now. I really can't thank you enough for everything (both fixing the immediate problems, and helping me learn more).

**Comment by moewew** [comment] 2019-04-27 13:32
Very well, closing this for now since it got a bit lengthy.

In case anyone thinks that freeform citations should be added to core `biblatex`, please open a new issue where this can be discussed.

Dicussions about freeform citations in `biblatex-apa` should be had at https://github.com/plk/biblatex-apa/issues.

**Closed by moewew** 2019-04-27 13:32 UTC
Labels: question

**Comment by 2011** [comment] 2019-05-25 05:17
Hi,

I am asking this here rather than opening a new issue, since all of your code is here. :)

Either I didn't notice this at the time or something on Overleaf has changed, but my freeform citations get sorted to the very top of the bibliography.

As an example, I have:

````
@freeform{UnitedStates:2000,
bibliography = {United States v.\ Doe, 500 U.S. 123 (2000).},
cite = {\textit{United States v.\ Doe}},
firstcite = {\textit{United States v.\ Doe}},
}
````
It appears before any of the entries with the last name beginning with 'A'.

Do you have any idea why? Thank you again.

**Comment by moewew** [comment] 2019-05-25 06:08
The LaTeX installation on Overleaf is seriously outdated. I double checked the code and it works for me on an up-to-date LaTeX installation and the `@freeform` entries sort as expected (the one you show sorts under "U".)

There are several issues that one would have to deal with to get my suggestion to work on Overleaf. Firstly `\letbibmacro` is not yet known, so it would have to be defined. Secondly, the older version of `biblatex-apa` on Overleaf still needs `\DeclareLanguageMapping{british}{british-apa}`.

But even when that is fixed I still can not get things to sort correctly. I checked out some obvious sources of errors, but those all seemed fine. I can't tell you exactly why things don't work, my guess is a resolved bug in Biber, but here is a workaround that compiles on Overlaf.

**Do not use this code with a recent version of `biblatex`. It is specifically tailored to the outdated Overleaf version. Use the code from https://github.com/plk/biblatex/issues/884#issuecomment-487254845 if you have a current LaTeX installation.**
```latex
\documentclass[british]{article}
\usepackage[T1]{fontenc}
\usepackage[utf8]{inputenc}
\usepackage{babel}
\usepackage{csquotes}

\usepackage{filecontents}
\begin{filecontents}{freeform-apa.dbx}
\ProvidesFile{freeform-apa.dbx}[2019/04/27 v0.1 Freeform citations for APA]
\DeclareDatamodelEntrytypes{
  letters,
  data,
  freeform,
  newsarticle}

\DeclareDatamodelFields[type=list, datatype=name]{
  with,
  writer,
  producer,
  execproducer,
  director}

\DeclareDatamodelFields[type=field, datatype=literal]{
  bibliography,
  cite,
  firstcite,
  abstractloc,
  titleisdescription,
  newspaper,
  urldescription}

\DeclareDatamodelFields[type=field, datatype=verbatim]{
  abstracturl}

\DeclareDatamodelEntryfields{
  titleisdescription,
  with,
  abstractloc,
  abstracturl,
  urldescription}

\DeclareDatamodelEntryfields[video]{
  writer,
  producer,
  execproducer,
  director}

\DeclareDatamodelEntryfields[newsarticle]{
  author,
  newspaper,
  title,
  day,
  endday,
  endmonth,
  endyear,
  month,
  year,
  addendum,
  doi,
  editor,
  editora,
  editorb,
  editorc,
  editoratype,
  editorbtype,
  editorctype,
  eid,
  eprint,
  eprintclass,
  eprinttype,
  issn,
  issue,
  issuetitle,
  issuesubtitle,
  language,
  note,
  number,
  origlanguage,
  pages,
  series,
  subtitle,
  titleaddon,
  translator,
  url,
  urlday,
  urlendday,
  urlendmonth,
  urlendyear,
  urlmonth,
  urlyear,
  volume}

\DeclareDatamodelEntryfields[data]{
  title,
  day,
  endday,
  endmonth,
  endyear,
  day,
  endday,
  endmonth,
  endyear,
  month,
  year,
  addendum,
  author,
  language,
  location,
  note,
  organization,
  pubstate,
  subtitle,
  titleaddon,
  type,
  url,
  urlday,
  urlendday,
  urlendmonth,
  urlendyear,
  urlmonth,
  urlyear,
  version}

\DeclareDatamodelEntryfields[freeform]{
  bibliography,
  cite,
  firstcite,
  sortkey}
\end{filecontents}

\usepackage[style=apa, backend=biber, datamodel=freeform-apa]{biblatex}
\DeclareLanguageMapping{british}{british-apa}

\DeclareBibliographyDriver{freeform}{%
  \usebibmacro{bibindex}%
  \usebibmacro{begentry}%
  \printfield{bibliography}%
  \newunit\newblock
  \iftoggle{bbx:related}
    {\usebibmacro{related:init}%
     \usebibmacro{related}}
    {}%
  \usebibmacro{apa:finpunct}%
  \usebibmacro{apa:pageref}%
  \usebibmacro{finentry}}

\makeatletter
% {<alias>}{<name>}
\newrobustcmd*{\letbibmacro}{%
  \@ifstar
    {\blx@letbibmacro@i}
    {\blx@letbibmacro}}

\def\blx@letbibmacro#1#2{%
  \blx@letbibmacro@i{\detokenize{#1}}{\detokenize{#2}}}

\def\blx@letbibmacro@i#1#2{%
  \ifcsundef{abx@macro@#2}
    {\blx@error
       {Bibliography macro '#2' undefined}
       {Use '\string\newbibmacro' to define this macro}}
    {\csletcs{abx@macro@#1}{abx@macro@#2}}}
\makeatother

\letbibmacro{cite:standard}{cite}
\letbibmacro{textcite:standard}{textcite}

\renewbibmacro*{cite}{%
  \ifentrytype{freeform}
    {\ifboolexpr{    not test {\ifciteseen}
                 and not test {\iffieldundef{firstcite}}}
       {\printfield{firstcite}}
       {\printfield{cite}}%
     \setunit{\multicitedelim}}
    {\usebibmacro{cite:standard}}}

\renewbibmacro*{textcite}{%
  \ifentrytype{freeform}
    {\ifboolexpr{    not test {\ifciteseen}
                 and not test {\iffieldundef{firstcite}}}
       {\printfield{firstcite}}
       {\printfield{cite}}}
    {\usebibmacro{textcite:standard}}}



\DeclareSortingScheme{apa}{
  \sort{
    \field{presort}
  }
  \sort[final]{
    \field{sortkey}
  }
  \sort{
    \field{bibliography}
    \field{sortname}
    \field{author}
    \field{editor}
    \field{translator}
    \field{writer}
    \field{director}
    \field{producer}
    \field{execproducer}
    \field{sorttitle}
    \field{title}
  }
  \sort{
    \field{pubstate}
  }
  \sort{
    \field{sortyear}
    \field{year}
    \literal{-2000000000}% APA has "nodates" coming first
  }
  \sort{
    \field{sorttitle}
    \field{title}
  }
  \sort{
    \field{volume}
    \literal{0}
  }
}

\begin{filecontents}{\jobname.bib}
@article{ChaosComputerClub:2017,
  doi     = {10.1016/S0969-4765(17)30102-9},
  journal = {Biometric Technology Today},
  number  = {6},
  pages   = {1 - 2},
  title   = {{Chaos Computer Club} spoofs {Samsung Galaxy S8} iris recognition system},
  volume  = {2017},
  year    = {2017},
}
@freeform{UnitedStates:2000,
  bibliography = {United States v.\ Doe, 500 U.S. 123 (2000).},
  cite         = {\textit{United States v.\ Doe}},
  firstcite    = {\textit{United States v.\ Doe}},
}
\end{filecontents}

\addbibresource{\jobname.bib}
\addbibresource{biblatex-examples.bib}


\begin{document}
\cite{sigfridsson,ChaosComputerClub:2017,UnitedStates:2000}
\nocite{*}
\printbibliography
\end{document}
```

**Comment by 2011** [comment] 2019-05-25 08:08
Hmmm. It times out (one minute). I can't think of any reason why it should. The paper comes to less than ten pages, and has no images or diagrams. It usually take about twenty seconds to compile.

**Comment by 2011** [comment] 2019-05-25 08:30
I didn't get all of the old stuff commented out before (sorry). Now it compiles, but there are a lot (42) errors, like this:

````
<argument> \datecircaprint \mkbibdateapalongextra 
                                                  {labelyear}{labelmonth}{la...
l.365 ...of the password \parencite{Everett:2016},
                                                   claiming that passwords c...
The control sequence at the end of the top line
of your error message was never \def'ed. If you have
misspelled it (e.g., `\hobx'), type `I' and the correct
spelling (e.g., `I\hbox'). Otherwise just continue,
and I'll forget about whatever was undefined.

! Undefined control sequence.
<argument> \datecircaprint \mkbibdateapalongextra 
                                                  {labelyear}{labelmonth}{la...
l.365 ... authentication \parencite{Polleit:2018} 
                                                  uses TOTPs (usually six di...
The control sequence at the end of the top line
of your error message was never \def'ed. If you have
misspelled it (e.g., `\hobx'), type `I' and the correct
spelling (e.g., `I\hbox'). Otherwise just continue,
and I'll forget about whatever was undefined
````

And most of the bibliography entries look like:

Smith, J. (labelyearlabelmonthlabelday)....

**Comment by moewew** [comment] 2019-05-25 08:44
As I said, you need a language mapping for each active language. That's why my code example has
```latex
\DeclareLanguageMapping{british}{british-apa}
```
You will need a similar line for all languages your document loads.

But this has nothing to do with the code for freeform citations, that's only due to the outdated `biblatex` and `biblatex-apa` version on Overleaf. See also https://tex.stackexchange.com/q/474557/35864

**Comment by 2011** [comment] 2019-05-25 09:14
I thought I had everything correct, but apparently I didn't (or maybe something in Overleaf's cache just expired), but it is working now (and I didn't change anything). Thank you again.

Will get my new machine in a few weeks, and will install LaTeX directly to that (and keep it up to date, too).

I have bookmarked this page, and will likely use it as a reference for a long time to come.
