### ISSUE TITLE
reversenumbering starts with -1

### ISSUE THREAD

**Issue by phwuil** [plk/biblatex#1100] opened 2021-01-28 17:33 UTC
Hi all,

Using 

```latex
\usepackage[style=alphabetic,
            bibstyle=publist,
            boldyear=true,
            marginyear=true,
            backend=biber,
            texencoding=utf8,
            bibencoding=utf8,
            url=false,
            isbn=false,
            doi=true,
            plnumbered=true,
            reversenumbering=false]
{biblatex}
```

everything's fine : 

![image](https://user-images.githubusercontent.com/5980636/106175418-64427e00-6196-11eb-80cb-7158019a02b0.png)

However, when trying to use `reversenumbering` : 

```latex

\usepackage[style=alphabetic,
            bibstyle=publist,
            boldyear=true,
            marginyear=true,
            backend=biber,
            texencoding=utf8,
            bibencoding=utf8,
            url=false,
            isbn=false,
            doi=true,
            plnumbered=true,
            reversenumbering=true] % <-- the only change here
{biblatex}
```
the counter is wrong : 

![image](https://user-images.githubusercontent.com/5980636/106175196-1fb6e280-6196-11eb-9db1-2a915dd5a911.png)

Thank you for any clue about this weird behavior ...

**Comment by moewew** [comment] 2021-01-28 21:08
As far as I can see, `reversenumbering` is not a standard `biblatex` option. It is implemented by `biblatex-publist`, so this is probably something you should report at https://github.com/jspitz/biblatex-publist/issues.

Note that you can make it much, much easier for people to understand what is going on and help you if you include a short but compilable example document that people can use to reproduce the behaviour you are describing (a so-called MWE: https://tex.meta.stackexchange.com/q/228/35864)

**Comment by moewew** [comment] 2021-02-06 07:17
I'm closing this since it appears to be related to a feature of a contributed `biblatex` style, which we do not maintain. Please report issues with `biblatex-publist` at https://github.com/jspitz/biblatex-publist/issues.

Maybe the issue is related to https://github.com/jspitz/biblatex-publist/issues/28. With an example document that reproduces the issue it would be easier to tell what is going on.

**Closed by moewew** 2021-02-06 07:17 UTC

**Comment by moewew** [comment] 2021-02-06 07:18
If it does turn out that this is a (core) `biblatex` issue, please do not hesitate to open a new issue with an MWE that ideally only uses standard styles or at least makes it clearer why this is a `biblatex` issue and not a `biblatex-publist` issue.
