### ISSUE TITLE
missing { in bbl file produced with biblatex 3.11/biber 2.11 in TL2018 Pretest.

### ISSUE THREAD

**Issue by herbs** [plk/biblatex#727] opened 2018-03-09 16:28 UTC
The latest biblatex 3.11/biber 2.11 in TeXLive 2018 Pretest seems to produce a bbl file for the document I typeset that is missing an open brace ({) in three locations and then the file fails to typeset. The biblatex 3.10/biber 2.10, in the now frozen TeXLive 2017, produces a bbl file that seems to be correct. I enclose the bbl files. They differ at lines 108, 141 and 173.
[bbl files.zip](https://github.com/plk/biblatex/files/1797565/bbl.files.zip)

**Comment by moewew** [comment] 2018-03-09 16:35
Thank you for the bug report.

Can you also show us the files/an MWE that produce the problem? The `\texttt{freedesktop.org}` and `\WikipediA` entry seem to be the culprits. 

At the moment I assume this is a duplicate of https://github.com/plk/biber/issues/215 caused by the fix for https://github.com/plk/biber/issues/210

**Comment by herbs** [comment] 2018-03-09 16:47
> On Mar 9, 2018, at 10:35 AM, moewew <notifications@github.com> wrote:
> 
> Thank you for the bug report.
> 
> Can you also show us the files/an MWE that produce the problem? The \texttt{freedesktop.org} and \WikipediA entry seem to be the culprits.
> 
> At the moment I assume this is a duplicate of plk/biber#215 caused by the fix for plk/biber#210

Howdy,

The original file is a slightly modified version of the documentation for the lucida-otf package (not yet part of TeXLive). The only modification was for a missing font. It was compiled using xelatex via latexmk.

I enclose the original file and all files produced by the first run of xelatex and biber.

 


Good Luck,

Herb Schulz
(herbs at wideopenwest dot com)

**Comment by moewew** [comment] 2018-03-09 16:52
I'm afraid GitHub's mail reply has swallowed the attachment. (I don't think it can cope with them.) Can you upload the files like you did in your initial post, please?

Alternatively a short TeX MWE using `filecontents`  that we can just copy and paste would also be appreciated. The intermediate files are not that much of a concern. We only need to see the offending `.bib` entries (and the bibliography set-up, but I believe the `.bib` entries will be enough here).

**Comment by herbs** [comment] 2018-03-09 17:01
Enclosed is the .bib file used by the document. I'll try to turn the document into a MWE and send it if you need it.
[lucida-otf-doc.bib.zip](https://github.com/plk/biblatex/files/1797704/lucida-otf-doc.bib.zip)

**Comment by moewew** [comment] 2018-03-09 17:53
The following MWE shows the problematic entries
```latex
\documentclass[british]{article}
\usepackage[T1]{fontenc}
\usepackage[utf8]{inputenc}
\usepackage{babel}
\usepackage{csquotes}

\usepackage[style=authoryear, backend=biber]{biblatex}

\usepackage{filecontents}
\begin{filecontents}{\jobname.bib}
@online{fontconfig,
  author ={{\texttt{freedesktop.org}}},
  sortname = {freedesktop},
  title = {Fontconfig},
  subtitle = {A library for configuring and customizing font access},
  date = {2016-06-15},
  urldate={2017-03-18},
  url = {https://www.freedesktop.org/wiki/Software/fontconfig/}
}
@online{wikipedia,
  author    = {{\WikipediA}},
  sortlabel = {Wikipedia},
  sortname  = {Wikipedia},
  title     = {Lucida},
  date      = {2016-10-19},
  urldate   = {2017-04-03},
  url       = {https://en.wikipedia.org/wiki/Lucida},
}

@online{features,
  author    = {{\WikipediA}},
  sortlabel = {Wikipedia},
  sortname  = {Wikipedia},
  title     = {List of typographic features},
  date      = {2017-02-21},
  urldate   = {2017-03-24},
  url       = {https://en.wikipedia.org/wiki/List_of_typographic_features},
}
\end{filecontents}

\def\WikipediA{wikipedia}

\addbibresource{\jobname.bib}

\begin{document}
\nocite{*}
\printbibliography
\end{document}
```

@plk The issue does indeed seem to be https://github.com/plk/biber/issues/215

**Comment by herbs** [comment] 2018-03-09 18:01
> On Mar 9, 2018, at 11:53 AM, moewew <notifications@github.com> wrote:
> 
> The following MWE shows the problematic entries
> 
> \documentclass
> [british]{article}
> 
> \usepackage
> [T1]{fontenc}
> 
> \usepackage
> [utf8]{inputenc}
> 
> \usepackage
> {babel}
> 
> \usepackage
> {csquotes}
> 
> 
> \usepackage
> [style=authoryear, backend=biber]{biblatex}
> 
> 
> \usepackage
> {filecontents}
> 
> \begin{filecontents}{\jobname
> .bib}
> @online{fontconfig,
>   author ={{
> \texttt
> {freedesktop.org}}},
>   sortname = {freedesktop},
>   title = {Fontconfig},
>   subtitle = {A library for configuring and customizing font access},
>   date = {2016-06-15},
>   urldate={2017-03-18},
>   url = {https://www.freedesktop.org/wiki/Software/fontconfig/}
> }
> @online{wikipedia,
>   author    = {{
> \WikipediA
> }},
>   sortlabel = {Wikipedia},
>   sortname  = {Wikipedia},
>   title     = {Lucida},
>   date      = {2016-10-19},
>   urldate   = {2017-04-03},
>   url       = {https://en.wikipedia.org/wiki/Lucida},
> }
> 
> @online{features,
>   author    = {{
> \WikipediA
> }},
>   sortlabel = {Wikipedia},
>   sortname  = {Wikipedia},
>   title     = {List of typographic features},
>   date      = {2017-02-21},
>   urldate   = {2017-03-24},
>   url       = {https://en.wikipedia.org/wiki/List_of_typographic_features},
> }
> 
> \end
> {filecontents}
> 
> 
> \def\WikipediA
> {wikipedia}
> 
> 
> \addbibresource{\jobname
> .bib}
> 
> 
> \begin
> {document}
> 
> \nocite
> {*}
> 
> \printbibliography
> \end{document}
> @plk The issue does indeed seem to be plk/biber#215

Howdy,

Thank you for the quick work in isolating the problem. Will there be a fix for this or do I need a workaround in the .bib file?

Good Luck,

Herb Schulz
(herbs at wideopenwest dot com)

**Comment by plk** [comment] 2018-03-10 10:13
It would be better to remove the double braces - because latex macros are decoded into UTF8 on reading the .bbl (otherwise sorting doesn't work properly) and because this is done syntactically, it's a messy process in certain edge cases and when I fix one, sometimes others break. It's impossible to get it 100% correct. `sortname` and `sortlabel` etc. are being used here to get around the fact that the actual sorting fields required are unuseable due to macros but things like one-off casing and changing fonts are better done with the data annotation feature of biber than hard-coding such things in the .bib.

**Comment by herbs** [comment] 2018-03-10 13:54
> On Mar 10, 2018, at 4:13 AM, plk <notifications@github.com> wrote:
> 
> It would be better to remove the double braces - because latex macros are decoded into UTF8 on reading the .bbl (otherwise sorting doesn't work properly) and because this is done syntactically, it's a messy process in certain edge cases and when I fix one, sometimes others break. It's impossible to get it 100% correct. sortname and sortlabel etc. are being used here to get around the fact that the actual sorting fields required are unuseable due to macros but things like one-off casing and changing fonts are better done with the data annotation feature of biber than hard-coding such things in the .bib.

Howdy,

Thank you for the information. It typesets fine now. I'll get in touch with the author of the lucida-otf package and inform him too.

Good Luck,

Herb Schulz
(herbs at wideopenwest dot com)

**Closed** 2018-03-10 13:56 UTC
