### ISSUE TITLE
Small caps not available, still tries to execute `\textsc`

### ISSUE THREAD

**Issue by albinahlback** [plk/biblatex#1264] opened 2023-01-24 15:36 UTC
Loading the packages `lmodern`, `fourier`, `fontenc` in Beamer, and executing `\printbibliography` with some URLs generates the warning
```
LaTeX Font Warning: Font shape `T1/lmss/m/sc' in size <10> not available
(Font)              Font shape `T1/lmr/m/sc' tried instead on input line 192.
```
due to `\mkbibacro`. However, this should never happen as it does try to check whether small caps is available:
```latex
\newcommand*{\mkbibacro}[1]{%
  \ifcsundef{\f@encoding/\f@family/\f@series/sc}
    {#1}
    {\textsc{\MakeLowercase{#1}}}}
```

Why does it think that small caps exists?

**Comment by moewew** [comment] 2023-03-15 07:27
I think I'd like to close this as a duplicate of https://github.com/plk/biblatex/issues/1093.

If you can provide a suitable example document, we could verify if that is the case. Otherwise I will probably just close this here in a few days and if it later turns out, it's something else, we can reopen.

**Closed** 2023-03-15 12:26 UTC
Labels: needs-feedback
