### ISSUE TITLE
Backref not right when there is a title page

### ISSUE THREAD

**Issue by jiewuza** [plk/biblatex#826] opened 2018-10-14 13:37 UTC
Here is a MWE:
```
\documentclass{article}
\usepackage[sorting=none,backend=biber,autocite=superscript,style=numeric-comp,hyperref=true,backref=true]{biblatex}
\usepackage{hyperref}
\addbibresource{test.bib}
\title{test}
\begin{document}
\maketitle
\clearpage
\pagenumbering{arabic}

Just to test backref \autocite{testkey}

\printbibliography
\end{document}
```

And this is test.bib:
```
@article{testkey,
author = {Author},
title = {A Test},
journal = {Journal Name},
volume = {1},
number = {2},
pages = {3 - 4},
year = {2018}
}
```

The bib in the references refers back to page 1, and when you click it, it goes to the title page.

**Comment by moewew** [comment] 2018-10-14 13:47
Mhhh, `pageref` just links to the page and in your document both the title page and the other page are page "1" because you restarted the numbering with `\pagenumbering{arabic}`. So I'd say this is unfortunate, but not a bug in `biblatex` per se.

If you use a different numbering scheme for the title page (say `alph`, so that the title page is "A" and not "1") things work just fine
```
\documentclass{article}
\usepackage[sorting=none,backend=biber,autocite=superscript,style=numeric-comp,hyperref=true,backref=true]{biblatex}
\usepackage{hyperref}
\addbibresource{biblatex-examples.bib}
\title{test}
\begin{document}
\pagenumbering{alph}
\maketitle
\clearpage
\pagenumbering{arabic}

Just to test backref \autocite{sigfridsson}

\printbibliography
\end{document}
```

Note that the option `hyperref=true` to `biblatex` is usually no better than the default `hyperref=auto`. I therefore recommend not to use it. The only difference is that `hyperref=true` will warn you if you fail to load `hyperref`. Both `hyperref=true` and `hyperref=auto` enable linking if and only if `hyperref` is loaded.

**Comment by moewew** [comment] 2018-10-14 13:57
The same issue can be reproduced with `backref` of the `hyperref` package after which `biblatex`'s `backref` is modelled

```
\documentclass{article}
\usepackage[backref=page]{hyperref}

\usepackage{filecontents}
\begin{filecontents}{\jobname.bib}
@book{appleby,
  author  = {Humphrey Appleby},
  title   = {On the Importance of the Civil Service},
  year    = {1980},
}
\end{filecontents}

\title{test}
\begin{document}
\maketitle
\clearpage
\pagenumbering{arabic}

Just to test backref \cite{appleby}

\bibliographystyle{plain}
\bibliography{\jobname}
\end{document}
```
The solution is the same.

Note the warning you get from the page numbering setup
```
pdfTeX warning (ext4): destination with the same
 identifier (name{page.1}) has been already used, duplicate ignored
<to be read again> 
                   \relax 
l.23 \end{document}
                    [1] (sljslkjsl.aux) )
```

**Comment by jiewuza** [comment] 2018-10-15 01:53
Got it!

**Comment by moewew** [comment] 2018-10-15 05:30
Good. Closing this since it works as intended.

**Closed by moewew** 2018-10-15 05:30 UTC
