### ISSUE TITLE
maxalphanames ignored by backend=bibtex

### ISSUE THREAD

**Issue by kno10** [plk/biblatex#762] opened 2018-06-14 14:16 UTC
The `maxalphanames` setting for `style=alphabetic` works fine with `backend=biber`, but is ignored by `backend=bibtex`.

I.e., bibtex generates keys such as `[HGKSSW16]`, where biber generates `[HGK+16]` as desired.

**Comment by moewew** [comment] 2018-06-14 14:22
Thank you for reporting this.

In the old days `(max|min)alphanames` would have been marked as *Biber only* in the manual. Since the manual nowadays assumes that Biber is used and BibTeX should only be considered a legacy backend, these markers don't appear any more.

This is what

>```
>Package biblatex Warning: Using fall-back BibTeX(8) backend:
>(biblatex)                functionality may be reduced/unavailable.
>```

in the `.log` file is trying to tell you.

So this is known and intended behaviour. I will have a short look if `(max|min)alphanames`  can be implemented for BibTeX, but I assume if it was easy it would have been done already.

**Comment by moewew** [comment] 2018-06-14 14:30
@josephwright Well, `.bst` files are still a bit of a mystery for me, so I'll gladly leave these things to you. From a very brief look at the code this should be possible *if* we can pass the `(min|max)alphanames` value to BibTeX. And I have no idea how to do that at the moment.

**Comment by kno10** [comment] 2018-06-14 14:30
I personally prefer biber in my projects for many reasons. But when preparing a template for others to use, you sometimes have to be happy if they at least get bibtex running... so I'd appreciate good backward support.
The traditional bibtex "alpha" style has this behavior - it would use `[HGK$^{+}$16]`. So it shouldn't be a bibtex limitation?

**Comment by josephwright** [comment] 2018-06-14 14:31
@moewew OK, I'll take this: I do know BibTeX's language. Passing stuff to BibTeX is easy enough: one uses a special citation for a control entry (same trick is used by several packages).

**Comment by moewew** [comment] 2018-06-14 14:37
@josephwright  Great. I know you have a lot of other things on your plate, so if there is anything I can do to help I'll be happy to have a look

**Comment by moewew** [comment] 2018-06-14 14:48
@kno10 Indeed BibTeX can truncate the label at any point. The current situation is just that that number is hard-coded in `biblatex.bst` and the option would have to be passed from `biblatex` to BibTeX. As Joseph points out there are ways to do that, we just have none set up at the moment.

There are some other things that we just can't reasonably implement with BibTeX (RegExp sourcemapping; the reason why Biber exists in the first place: full Unicode support; an extensible data model that doesn't require modification of the `.bst` file; ...), so I would urge you to use Biber even in your template. On modern systems it should normally be possible to get Biber running without too much of a headache, but if your users are stuck with a TeX live version from 2010 with no way to update or install anything, all bets are off...

**Comment by kno10** [comment] 2018-06-14 14:51
I agree that on Linux it's often even already installed.
Windows users may not yet have Perl installed, and as I do not have Windows, I do not know how easy it is for them to install it. Or if it will be automatically installed on OSX. So I was a bit reluctant to require biber by default.

**Comment by moewew** [comment] 2018-06-14 14:54
Biber doesn't need a Perl installation. The Biber version that all great TeX distributions (MikTeX and TeX live) install by default are pre-built binaries that can be used as stand-alone programmes (at the first run they unpack the necessary modules and use those).

**Comment by josephwright** [comment] 2018-06-14 14:58
The BibTeX support limitations are in two parts, really: some stuff is more-or-less impossible, more generally it's a question of effort. For the types of bibliography that BibTeX works well, the support is already there (_e.g._ simple unsorted numerical ones).

I've done the 'pass the data' part, just need to adjust the `.bst` a little.

**Comment by josephwright** [comment] 2018-06-14 15:00
BTW, could I have a nice simple example of the `.tex` and `.bib` data (for example, one that gives the labels in the first line)?

**Comment by moewew** [comment] 2018-06-14 15:02
I guess
```latex
\documentclass[british]{article}
\usepackage[T1]{fontenc}
\usepackage[utf8]{inputenc}
\usepackage{babel}
\usepackage{csquotes}

\usepackage[style=alphabetic, maxnames=99, maxalphanames=3, backend=bibtex]{biblatex}

\addbibresource{biblatex-examples.bib}

\begin{document}
\cite{sigfridsson,aksin,herrmann}
\printbibliography
\end{document}
```
should do.

**Comment by josephwright** [comment] 2018-06-14 15:22
I think things should now work: I just want to look at the `min` equivalent.

**Comment by moewew** [comment] 2018-06-14 18:03
As far as I can see the `ctrl.minnames` in `FUNCTION {makelabel:alpha:format}` can simply be replaced by `ctrl.minalphanames`. The idea of `min...names` is to show at least that number of names (if available). That means that truncated lists go back to displaying `min...names` and then "et al.".

**Comment by moewew** [comment] 2018-06-15 07:43
@josephwright I noticed that the control `.bib` file and BibTeX's additional `.aux` files identify themselves with the `bbl` version (see `\blx@sig@bib` et al.). Since we introduced a new feature that version would have to be stepped up. My feeling is that strictly speaking this is no `bbl` issue, so stepping up that number is not really appropriate. It feels more like these things should depend on the `.bcf` version, but that is normally Biber-only. Do we need a new version number for BibTeX's control files?

**Comment by josephwright** [comment] 2018-06-15 07:44
@moewew Would need a version number for the control file: I'll sort one out later today.

**Comment by moewew** [comment] 2018-06-15 07:46
Great, thank you? Are you happy with `minalphanames` or did you run into complications?

**Comment by josephwright** [comment] 2018-06-15 07:48
@moewew I need to look at the `.bst` and see where it 'fits in': for max names the swap was easy as there was already a maximum, but for the minimum that's not the case. The actual coding will be easy enough. I've got a train journey later this morning: hopefully I'll sort it then.

**Comment by moewew** [comment] 2018-06-15 07:51
Mhhh, on a quick first look I thought we could simply replace the one instance of `ctrl.minnames` in

https://github.com/plk/biblatex/blob/8d925e4e3128fe82ea714ffa901ba07079d52ba6/bibtex/bst/biblatex/biblatex.bst#L2167-L2211

with `ctrl.minalphanames`. If I'm not completely mistaken that should give us what we want. It worked in the very short MWE from above...

**Comment by josephwright** [comment] 2018-06-15 07:53
@moewew Oops, missed that: you are absolutely right. So we just need a version string: give me a couple of minutes!

**Comment by josephwright** [comment] 2018-06-15 08:15
@moewew Looking over the code, there is already a check for the `.bbl` version. That is being stepped in the upcoming release (2.9 to 3.0) anyway, so the change for passing the data will be picked up. We could add a second version number for the control citation, but I think it's almost certainly overkill: we end up having to track a lot of version numbers. If you are happy, I'd rather just leave as-is.

**Comment by moewew** [comment] 2018-06-15 08:20
Ah, I hadn't realised we would be stepping up the `.bbl` version anyway. So we can probably get away with not introducing a new number this time... I share the reservations about adding a new version number, but I didn't really want to step up the `.bbl` version for something that is not related to it.
Given all that we probably don't need a new number now.

I had a look at https://github.com/plk/biblatex/issues/601 so you don't get bored on your train journey ;-)

**Comment by moewew** [comment] 2018-11-06 07:53
`biblatex` 3.12 has been released and is available in MikTeX and TeX live 2018.

`maxalphanames` should now work as expected with the BIbTeX backend.

**Closed by moewew** 2018-11-06 07:53 UTC
Labels: enhancement
