### ISSUE TITLE
Bug related to babel - entry with name finishing with an accentuated character

### ISSUE THREAD

**Issue by Julien-T** [plk/biblatex#269] opened 2014-09-14 23:04 UTC
Hi there,
I found what seems to be a bug, here is a minimal example.
The BUG entry causes the following compilation error, while the NOBUG is ok
! Argument of \UTFviii@three@octets has an extra }.

=================================
bug.bib :
=================================
@incollection{BUG,
editor = {nom\'e , Jack},
}

@incollection{nobug,
editor = {nom\'e , Jack},
}
=================================
bug.tex :
=================================
\documentclass{book}
\usepackage[utf8]{inputenc} 
\usepackage[T1]{fontenc}
\usepackage[french]{babel}
\usepackage{biblatex}
\bibliography{bug}
\begin{document}
\nocite{*}
  \printbibliography
\end{document}
=================================

My version of latex is 
 pdfTeX, Version 3.14159265-2.6-1.40.15 (TeX Live 2014/Debian)
And as the compiler do not output biblatex version, here is what is in biblatex.sty :
\def\abx@date{2014/06/25}
\def\abx@version{2.9a}
\def\abx@bbxid{\abx@date\space v\abx@version\space biblatex bibliography style (PK/JW/AB)}
\def\abx@cbxid{\abx@date\space v\abx@version\space biblatex citation style (PK/JW/AB)}
\def\abx@lbxid{\abx@date\space v\abx@version\space biblatex localization (PK/JW/AB)}
\def\abx@cptid{\abx@date\space v\abx@version\space biblatex compatibility (PK/JW/AB)}

biber version 1.9

Cheers,
Julien

**Comment by plk** [comment] 2015-02-23 20:35
@josephwright - did we ever come to any conclusion about this?

**Comment by josephwright** [comment] 2015-02-23 21:49
I'm working on it: it's caused by `smartof` in French. I'll give this a bit of thought: the code is written assuming accents of the `\'{e}` form here.

**Comment by josephwright** [comment] 2015-02-23 22:50
Suggested fix for `french.lbx`:
````
\protected\long\gdef\lbx@fr@smartof@i#1{%
  \global\togglefalse{smartof}%
  \begingroup
  \def\forceD##1{a\relax}%
  \def\forceDE##1{x\relax}%
  \def\do##1{\let##1\@firstofone}%
  \abx@dosingleaccents
  \abx@dodoubleaccents
  \def\i{i}\def\j{j}%
  \def\AE{a}\def\ae{a}%
  \def\OE{o}\def\oe{o}%
  \def\O{o}\def\o{o}%
  \let\IeC\@firstofone
  \let\@tabacckludge\@gobble
  \ifnum\catcode`\"=\active
    \uccode`\~=`\"
    \uppercase{\let~\@empty}%
  \fi
  \ifnum\catcode`\~=\active
    \let~\@empty
  \fi
  \let\protect\noexpand
  \edef\lbx@tempa{#1}%
  \expandafter\futurelet
  \expandafter\lbx@tempa
  \expandafter\lbx@fr@smartof@ii
  \lbx@tempa&}

\gdef\lbx@fr@smartof@ii{%
  \ifcat\bgroup\noexpand\lbx@tempa
    \def\lbx@tempa##1{\futurelet\lbx@tempa\lbx@fr@smartof@ii##1}%
  \else\ifcat\noexpand~\noexpand\lbx@tempa
    \def\lbx@tempa##1{\futurelet\lbx@tempa\lbx@fr@smartof@ii}%
  \else
    \ifnum 0%
      \if a\noexpand\lbx@tempa 1\fi
      \if e\noexpand\lbx@tempa 1\fi
      \if i\noexpand\lbx@tempa 1\fi
      \if o\noexpand\lbx@tempa 1\fi
      \if u\noexpand\lbx@tempa 1\fi
      \if y\noexpand\lbx@tempa 1\fi
      \if A\noexpand\lbx@tempa 1\fi
      \if E\noexpand\lbx@tempa 1\fi
      \if I\noexpand\lbx@tempa 1\fi
      \if O\noexpand\lbx@tempa 1\fi
      \if U\noexpand\lbx@tempa 1\fi
      \if Y\noexpand\lbx@tempa 1\fi
      >0 %
    \let\lbx@tempa\lbx@fr@smartof@d
  \else
    \ifnum 0%
      \if h\noexpand\lbx@tempa 1\fi
      \if H\noexpand\lbx@tempa 1\fi
      >0 %
    \def\lbx@tempa##1{\futurelet\lbx@tempa\lbx@fr@smartof@ii}%
  \else
    \let\lbx@tempa\lbx@fr@smartof@de
  \fi\fi\fi\fi
  \lbx@tempa}
````
Idea: avoid case changing entirely and test for both upper and lower case outcomes. This is slightly more costly in conditionals but avoids the issue entirely.

By the way, `smartof` and the `\forceD(E)` stuff isn't documented that I can find. I'm not sure what the expected behaviour is here with Unicode input and a suitable engine: the test doesn't allow for a 'real' é for example and covering all of those cases is more tricky (though doable).

**Comment by plk** [comment] 2015-02-24 08:04
Ok, thanks - I merged into DEV.

**Closed by plk** 2015-02-24 08:04 UTC
