### ISSUE TITLE
WorldCat / OCLC OCN support

### ISSUE THREAD

**Issue by StevanWhite** [plk/biblatex#1187] opened 2021-10-02 15:43 UTC
I see mention of WorldCat in the TexLive distribution, so I guess some bibliographic system supports it.

And I see places where this is used on the web, for instance, here:
    https://openlibrary.org/books/OL23475181M
which has a link marked "OCLC/WorldCat", with URL
    https://www.worldcat.org/oclc/20794561?tab=details
    
You should consider providing support for such identifiers in the biblatex package.

I don't really know how this works, and I haven't used such identifiers myself.

Unfortunately, the OCLC's website appears to have been overrun by marketers, to the extent that it is very hard to tell what the OCLC is or does  -- except that it's very exciting!  I was unable   I found Wikipedia more enlightening on the subject.

It seems that OCLC runs WorldCat, but it isn't clear to me if they both use the same identifiers.
The number used by the OCLC is called an OCN.  With some difficulty, I found one technical reference:
[WorldCat Metadata API](https://www.oclc.org/developer/develop/web-services/worldcat-metadata-api.en.html)

I don't know how this should be implemented.  Should the eprinttype 'oclc' be an alias for 'worldcat"?  
Or might they be used to refer to different kinds of identifiers?  This might take some research to determine.

**Comment by plk** [comment] 2023-03-12 16:21
Marking as duplicate of the general n2t discussion here: #1183

**Closed** 2023-03-12 16:21 UTC
Labels: duplicate
