### ISSUE TITLE
No comma after editors in first full citatation of @incollection items

### ISSUE THREAD

**Issue by lazzalazza** [plk/biblatex#1030] opened 2020-07-20 16:25 UTC
Hi, 

biblatex-philosophy doesn't put a comma after the first full citation of the original collection in @incollection items.
I would like to insert a comma between the editors and the title in the highlighted position (is the lack of comma intended?) but I wonder how to do that.

(Other possible question: would it be possible to always use the shortened version, only quoting the full collection item in the bibliography as an independent item?).

Thanks in advance for your help,

Andrea

```latex
\documentclass{article}
\usepackage{filecontents}
\usepackage{polyglossia}
\setmainlanguage{italian}
\usepackage[indexing=true,
            backend=biber,
            style=philosophy-verbose,
            classical=true,
            inbeforejournal=false,
            scauthors=all,
            shorthandintro=false,
            publocformat=locpubyear,
            volnumformat=plain,
            sorting=nty,
            language=auto,  
            autolang=langname,]{biblatex} %% MD



\begin{filecontents}{biblio.bib}

@incollection{autore2017a,
  Author =       {Autore, Autor},
  Crossref =     {collection2017a},
  Pages =        {231--245},
  Title =        {Titolo provvisorio},
}

@InCollection{autrice2017a,
  author =       {Autrice, Autora},
  title =        {Altro titolo provvisorio},
  year =      2017,
  crossref =  {collection2017a},
  pages =     {191--209}}

@collection{collection2017a,
	Year = 2017,
	Editor = {Editor, Uno and Editor, Due},
	Location = {Milano},
	Publisher = {Mondadori},
	Title = {Titolo molto molto bello},
  hyphenation = {italian}}

\end{filecontents}

            
\addbibresource{./biblio.bib}

\begin{document}

\cite{autore2017a}

\cite{autrice2017a}

\printbibliography


\end{document}



```
![mwe](https://user-images.githubusercontent.com/60494153/87960712-ffa2ba00-cab4-11ea-97ca-d421b7580812.png)

**Comment by moewew** [comment] 2020-07-20 17:33
Please report issues with styles from `biblatex-philosophy` directly to the author/developer/maintainer. Contact details can be found in the documentation (`texdoc biblatex-philosophy` or on CTAN https://ctan.org/pkg/biblatex-philosophy). The issue tracker here is only for `biblatex` core features and the standard styles.

The last time I wrote an email to the `biblatex-philosophy` maintainer he responded quickly and was eager to help.

On first glance it appears to me that something in the bimacro `usedriver:collection` from `philosophy-verbose.bbx` might be off. Specifically, `\labelnamepunct` is only printed in a `\ifnameundef{editor}` test, which yields true even though the editor is printed, suggesting that the previous code printing the editors also issues `\clearname{editor}` throwing off the test. But that's just a quick guess based on a first investigation. The package maintainer will know more about this.

---

Re your bonus question, please keep in mind that this issue tracker is for bug reports and feature requests for core `biblatex` only. If you want to request features in `biblatex-philosophy`, you need to contact the author. If you just want to ask about the possibility of such a feature, your favourite LaTeX online forum (https://groups.google.com/forum/#!forum/comp.text.tex, https://www.guitex.org/home/it/forum/5-tex-e-latex, https://tex.stackexchange.com/) are a better place to ask.

**Comment by lazzalazza** [comment] 2020-07-25 17:41
Thank you so much for the advice, that eventually lead me to solve both problems: it was in effect an issue that had to do with usedriver:collection and with the failed \ifnameundef{editor} check. I was in a hurry and stupidly posted the question on the biblatex github repository, and I’m kind of ashamed for this: but hey, you were so helpful that I also feel very lucky for this mistake. 

Sorry if I reply so late, but I was on a short vacation. Thank you so much!

**Comment by moewew** [comment] 2020-07-25 18:36
Great that you could solve your problem!

If this did turn out to be a bug (or at least a weird or unexpected behaviour) in `biblatex-philosophy`, please report this also to the `biblatex-philosophy` maintainer, I'm sure he will appreciate the heads-up. (Please ignore this if you have already done this, but it really cannot be stressed enough how important it is to actually *tell* developers about issues with their software.)

Don't worry about posting this 'in the wrong place'. I'd much rather have a few issues reported here that are 'not our fault' or something we can't do anything about, than go issues we *can* do something about undetected. But I hope it doesn't hurt to point out what we can and cannot do here.

**Comment by moewew** [comment] 2020-08-16 11:47
Closing this for now since it is an issue with an external style. Feel free to open a new issue if the style developer identifies an issue in standard `biblatex`.

**Closed by moewew** 2020-08-16 11:47 UTC
Labels: invalid
