### ISSUE TITLE
German - proposed change

### ISSUE THREAD

**Issue by pauloney** [plk/biblatex#254] opened 2014-07-08 13:13 UTC
There are 4 LBX's files related to the German language

<code>
austrian.lbx  german.lbx  naustrian.lbx  ngerman.lbx
</code>

and great source of confusion because `german.lbx` (the most used) stands for the OLD German spelling and not the new and current and same for the Austrian file. 

Since the usage is divided in two geographic regions and two time-frames (the spelling before and after 1996), following BCP47 will require 6 LBX's files:

```
de-1901.lbx  de-DE-1901.lbx  de-AT-1901.lbx  
de.lbx       de-DE.lbx       de-AT.lbx
```

that will contain the particularities of each.

The mappings onto Babel/Polyglossia for now should follow along the lines:

```
de-1901.lbx --> "german"
de-DE-1901.lbx --> "german"
de-AT-1901.lbx --> "austrian"
de.lbx --> "ngerman"
de-DE.lbx --> "ngerman"
de-AT.lbx --> "naustrian"
```

Paulo Ney

**Comment by plk** [comment] 2016-04-03 17:15
Perhaps this can be picked up again at some point - there has been a lot of biblatex development recently and 3.4 will be out soon.

**Comment by jspitz** [comment] 2016-11-06 10:55
I see the rationale here, but I don't think it's a good idea to just rename the German `*.lbx` files, as long as the other `*.lbx` files continue to use the babel names, which are in many other cases as irritating (cf. `portuguese`/`portuges` vs. `brazil` or `english`/`american` vs. `british` etc.).

I propose to either consequently stick with the babel naming (and thus keep `ngerman`, `naustrian`, `nswissgerman` etc.), or rename _all_ *.lbx files according to a standardized scheme.

**Comment by plk** [comment] 2016-11-06 10:57
Yes, if this is to be done, it needs to be a comprehensive change but it would be nice if babel/polyglossia could support standard languge identifiers first ...

**Comment by jspitz** [comment] 2016-11-06 11:05
I doubt that will/can happen for babel, since it is pretty agnostic of language support files nowadays. Babel (the core package) does not know any longer which languages it supports. Whatever is passed as an option will be handled, as long as there is an `<option>.ldf` file. So I can create my own `newspeak.ldf` file locally, and `\usepackage[newspeak]{babel}` will work. More seriously, the babel maintainer has no way to enforce any standardization of naming (as opposed to polyglossia, where the `gloss-*.ldf` files are still bundled in the package).

**Comment by jspitz** [comment] 2016-11-06 11:28
As with regard to a more general change, I think this ticket is a duplicate of the more general #160 (which however has a rather irritating title).

So I propose to close this ticket and rename #160 as "Use standardized language identifiers for lbx files"

**Comment by plk** [comment] 2016-11-06 11:32
Closing this and tracking in #160

**Closed by plk** 2016-11-06 11:32 UTC
