### ISSUE TITLE
current doi display for apa style

### ISSUE THREAD

**Issue by 2011** [plk/biblatex#885] opened 2019-04-24 15:29 UTC
Hi,

More than two years ago, the APA changed their preferred style for doi dsiplay from:

doi:  10.1234/5678abcd

to:

https://doi.org/10.1234/5678abcd

Two questions (both obvious):

1. Is there a way to get the preferred style in the current version of biblatex?

2. Will there there be an update where this becomes a.) easier to obtain and / or b.) the default output?

Thank you again for your assistance.

**Comment by moewew** [comment] 2019-04-24 15:47
Since this is the core-`biblatex` issue tracker I will only speak about `biblatex` and not about `biblatex-apa`, which implements APA style. Issues about `biblatex-apa` should be logged at https://github.com/plk/biblatex-apa.

1. Yes, assuming a standard set-up this should be as easy as
    ```latex
    \DeclareFieldFormat{doi}{%
      \url{https://doi.org/#1}}
    ```
2. The question of whether or not this should be made the default *in the standard styles* is more tricky. I don't think that core `biblatex` is bound by APA decisions, but they can be an indicator. According to §2.6.1 of the DOI handbook (https://www.doi.org/doi_handbook/2_Numbering.html#2.6.1) a DOI should be displayed and printed as 

    > doi:10.1006/jmbi.1998.2354

    But CrossRef have decided that a DOI should only be shown as a link (https://www.crossref.org/display-guidelines/)

    > https://doi.org/10.1006/jmbi.1998.2354

    some organisation followed suit (for example APA: https://blog.apastyle.org/apastyle/digital-object-identifier-doi/) and I guess many people will find the full URL more handy.

    The issue for us is that simply changing the default output from "doi:10.1006/jmbi.1998.2354" to "https://doi.org/10.1006/jmbi.1998.2354" has a potentially large impact on existing documents. The additional letters `https` and `org` as well as the missing space can change line and page breaking quite a bit.



```latex
\documentclass[british]{article}
\usepackage[T1]{fontenc}
\usepackage[utf8]{inputenc}
\usepackage{babel}
\usepackage{csquotes}

\usepackage[style=authoryear, backend=biber]{biblatex}

\DeclareFieldFormat{doi}{%
  \url{https://doi.org/#1}}

\addbibresource{biblatex-examples.bib}


\begin{document}
\cite{sigfridsson}
\printbibliography
\end{document}
```

**Comment by 2011** [comment] 2019-04-24 22:29
First of all, thank you for your prompt reply. :)

> Yes, assuming a standard set-up this should be as easy as

Well, I can't reproduce that in markdown here, but it works. :) Can you (briefly) explain what is going on. I understand #1 as a parameter, but what does the % symbol (normally a comment) do, and why does it have to be at the end of the line?

> The issue for us is that simply changing the default output from "doi:10.1006/jmbi.1998.2354" to "https://doi.org/10.1006/jmbi.1998.2354" has a potentially large impact on existing documents. The additional letters https and org as well as the missing space can change line and page breaking quite a bit.

I understand that. My feeling (certainly not a strong one) is that the url should be the default. Maybe it could be implemented as an option (doistyle=url).

**Comment by moewew** [comment] 2019-04-25 04:46
Yes, you could say `#1` is an implicit parameter (`#1` is the only parameter that `\DeclareFieldFormat` knows and each `\DeclareFieldFormat` should use `#1` at least once). When the format is used it will be replaced with the (field) contents that are going to be printed. In this case that is the DOI. The `%` at the end of the line is there to prevent unwanted white space in the output that would be caused by LaTeX interpreting the end-of-line character(s) as a space. See https://tex.stackexchange.com/q/7453/35864.

I'm not so sure about an option, since
```latex
\DeclareFieldFormat{doi}{%
  \url{https://doi.org/#1}}
```
is a fairly simple way to deal with this. I believe that not everything needs to be solved with an option, especially if a straightforward solution with other commands is possible. There is precedent for an option of this type, though. `arxiv` does something similar, but the involved field formats are arguably more complex...

**Comment by 2011** [comment] 2019-04-25 13:05
Read the linked page (and several more from that page), and I believe I now understand what the % symbol does, but I do have one more question - why not just put everything on one line? For example:

    \DeclareFieldFormat{doi}{\url{https://doi.org/#1}}

Is that just a matter of convention (style), or is there another reason?

**Comment by moewew** [comment] 2019-04-25 13:46
Indeed
```latex
\DeclareFieldFormat{doi}{\url{https://doi.org/#1}}
```
would give the same result. This is purely a matter of coding style. The current definition is

https://github.com/plk/biblatex/blob/476a0dad3146012955b1f1441ffbc8f1d015ef35/tex/latex/biblatex/biblatex.def#L445-L449

which would be a bit long if written in a single line.

**Comment by 2011** [comment] 2019-04-26 06:27
Okay, I am trying to put my new knowledge to use. :)

I have a "report" type, and I would like the number to appear as "(FOO 1234)." in the bibliography (in the .bib file, I have the number field set too "FOO 1234"). Instead it appears as "(No. FOO 1234)."

So of course, I downloaded and unpacked the latest version, and searched the file you referenced (biblatex/tex/latex/biblatex/biblatex.def). I did find:

    \DeclareFieldFormat{number}{#1}% number in a series

I tried to find where the "No. " is being put it (went back to the root directory of the release, and did "grep -r 'No\.'" but I couldn't locate it. I even tried messing around with biblatex/tex/latex/biblatex/lbx/english.lbx (which just made a mess of things). Can you help with that?

**Comment by moewew** [comment] 2019-04-26 06:30
Those definitions can be distributed over several styles. For the standard styles they live in `biblatex.def`. But I remember you saying you are using `apa` and there you will probably find the relevant definition in `apa.bbx`.

The relevant bit is
```latex
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% (APA 6.30) Number for reports with no prefix if not
%            a numeral. Report number is optional and so must be
%            the parens.

\DeclareFieldFormat{number}{\iffieldundef{volume}
                             {\ifinteger{\thefield{number}}
                               {\addspace\mkbibemph{\bibcpstring{number}~\apanum{#1}}\adddot}
                               {\apanum{#1}}}
                             {\mkbibemph{\apanum{#1}}}}

\DeclareFieldFormat[report]{number}{\mkbibparens{\iffieldundef{type}
                                                  {}
                                                  {\printfield{type}\setunit{\addspace}}%
                                                  \bibcpstring{number}~\apanum{#1}}}

\newbibmacro*{apa:reportnum}{%
  \iffieldundef{number}%
    {}%
    {\printfield{number}}}

%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
```

**Comment by 2011** [comment] 2019-04-26 07:01
I saw that you had answered right away (thanks again), but didn't see the bottom part of your reply. So I tried:

    \DeclareFieldFormat[report]{number}{\mkbibparens{\iffieldundef{type}
       {}
       {\printfield{type}\setunit{\addspace}}\apanum{#1}}}

Yes, I guess that is the same as yours. :) I then (after I saw the rest of your post) tried moving FOO to "type = {FOO}," but then then reference comes out "(FOO1234)." (with no space, and I have no idea why that is).

**Comment by moewew** [comment] 2019-04-26 07:04
I can't test for lack of a minimal example, but you might need
```
\DeclareFieldFormat[report]{number}{\mkbibparens{\iffieldundef{type}
   {}
   {\printfield{type}\addspace}\apanum{#1}}}
```
instead. Using the punctuation tracker (`\setunit`) within field formats is always a bit of a gamble...

**Comment by 2011** [comment] 2019-04-26 07:13
That worked, although in this particular case, it ended up with a line break. I did figure out to change \addspace to \addnbspace. I don't know if that is better for the general case (probably not), but it is what **I** want for this one project, which is most of the reason for using LaTeX in the first place. :)

Thanks again.

**Comment by moewew** [comment] 2019-04-27 13:35
Closing this as well since the discussion steered a bit off-course.

If anyone thinks we should seriously consider changing the default DOI output or at least add an option to change it more quickly than the one-liner discussed here, please open a new issue. Please discuss the specific output of `biblatex-apa` in that regard at https://github.com/plk/biblatex-apa/issues.

**Closed by moewew** 2019-04-27 13:35 UTC
Labels: question
