### ISSUE TITLE
EDTF date output: years and “BCE” missing

### ISSUE THREAD

**Issue by njbart** [plk/biblatex#679] opened 2018-01-07 13:01 UTC
As of lately, I have started seeing weird behaviour in connection with ISO 8601/EDTF dates.

MWE, using the examples from the biblatex manual, table 5:

```
\documentclass{article}
\usepackage[style=authoryear,dateera=secular,sorting=nty]{biblatex}

\usepackage{filecontents}
\begin{filecontents}{\jobname.bib}
@book{t5l01, author = {NN}, title = {Table 5, line 01}, date = {0000} }
@book{t5l02, author = {NN}, title = {Table 5, line 02}, date = {-0876} }
@book{t5l03, author = {NN}, title = {Table 5, line 03}, date = {-0877/-0866} }
@book{t5l04, author = {NN}, title = {Table 5, line 04}, date = {0768} }
@book{t5l05, author = {NN}, title = {Table 5, line 05}, date = {-0343-02} }
@book{t5l06, author = {NN}, title = {Table 5, line 06}, date = {0343-02-03} }
@book{t5l07, author = {NN}, title = {Table 5, line 07}, date = {0343-02-03} }
@book{t5l08, author = {NN}, title = {Table 5, line 08}, date = {1723~} }
@book{t5l09, author = {NN}, title = {Table 5, line 09}, date = {1723?} }
@book{t5l10, author = {NN}, title = {Table 5, line 10}, date = {1723?~} }
@book{t5l11, author = {NN}, title = {Table 5, line 11}, date = {2004-22} }
@book{t5l12, author = {NN}, title = {Table 5, line 12}, date = {2004-24} }
\end{filecontents}

\addbibresource{\jobname.bib}
\begin{document}

\nocite{*}

\printbibliography
\end{document}
```

Actual output:

![screen shot 2018-01-07 at 13 40 18](https://user-images.githubusercontent.com/2765811/34649499-5820127c-f3a8-11e7-83f1-8f48162dfb57.png)

Note the missing year in lines 1 (where the year seems to appear after the title) and 10, and the missing “BCE” in lines 1 to 3, and 5.

As to the manual, “0768 CE” in the “Output Format” column seems wrong, shouldn’t it be “768 CE”?

**Comment by moewew** [comment] 2018-01-07 13:09
Thanks for the report.

Line 1 seems to be a Biber problem, apparently if the year is `0` it goes over to `nodate`. This can be seen in the `.bbl` where we have for that entry `\field{labeldatesource}{nodate}`.

Line 10 is because of `WARN - Entry 't5l10' (scetrsulskszs.bib): Invalid format '1723?~' of date field 'date' - ignoring` I guess this is due to the EDTF-ISO transition. The new iso format for `?~` is `%` (see https://github.com/plk/biblatex/wiki#release-notes-for-version-310). This is only a documentation issue.

The missing BCE is a `biblatex` issue. I'll have a look.

**Comment by moewew** [comment] 2018-01-07 13:23
I think the missing 'BCE' is a problem with the definitions of `\lbx@us@mkdaterangetrunc@long` and friends in `english.lbx`. They should not call `\dateeraprint{#2}`, but `\dateeraprint{#2year}` instead. Now it is not clear to me where `\dateeraprint{#2endyear}`  should be used. @plk Any idea?

**Comment by plk** [comment] 2018-01-07 15:08
Please try the latest 3.11/2.11 dev versions. I believe that all of these are now addressed.

The biber issue was a common null/zero test bug, the biblatex part was partly brace scoping issues and partly, as you say, the missing `year` or `endyear` in the calls to `\dateeraprint`. I have also corrected the documentation regarding the change from `?~` to `%`.

**Comment by moewew** [comment] 2018-01-07 17:35
Seems to work for me now. Thank you.

**Comment by moewew** [comment] 2018-01-25 07:22
@PLK Seems as though `extradate` has not gotten the fix for the null test bug.

```
\documentclass{article}
\usepackage[style=authoryear,sorting=nty]{biblatex}

\usepackage{filecontents}
\begin{filecontents}{\jobname.bib}
@book{t5l01, author = {NN}, title = {Table 5, line 01}, date = {0000} }
@book{t5l13, author = {NN}, title = {Table 5, line 13}}
\end{filecontents}

\addbibresource{\jobname.bib}
\begin{document}
\nocite{*}
\printbibliography
\end{document}
```
gives me

> NN (0a). Table 5, line 01.
> — (n.d.[b]). Table 5, line 13.
I would have expected

> NN (0). Table 5, line 01.
> — (n.d.). Table 5, line 13.

**Comment by moewew** [comment] 2018-01-25 07:23
@njbart Further testing of the fix and comments are welcome.

**Comment by njbart** [comment] 2018-01-25 09:45
Unfortunately, I didn’t figure out yet how to run the biber dev version. All I got so far, after cloning the github repo, is:

```
biber $ ./bin/biber 
Can't locate Biber.pm in @INC (you may need to install the Biber module) (@INC contains: /Users/nick/perl5/lib/perl5/darwin-thread-multi-2level /Users/nick/perl5/lib/perl5 /usr/local/Cellar/perl/5.26.1/lib/perl5/site_perl/5.26.1/darwin-thread-multi-2level /usr/local/Cellar/perl/5.26.1/lib/perl5/site_perl/5.26.1 /usr/local/Cellar/perl/5.26.1/lib/perl5/5.26.1/darwin-thread-multi-2level /usr/local/Cellar/perl/5.26.1/lib/perl5/5.26.1 /usr/local/lib/perl5/site_perl/5.26.1) at ./bin/biber line 17.
BEGIN failed--compilation aborted at ./bin/biber line 17.
```

Any hints?

**Comment by moewew** [comment] 2018-01-25 09:46
Since I have no clue when it comes to Perl, I normally get the compiled dev version from sourceforge: https://sourceforge.net/projects/biblatex-biber/files/biblatex-biber/development/binaries/

**Comment by plk** [comment] 2018-01-25 17:32
Should be fixed now with regression test in place. Binaries for 3.11 are updated on SF.

**Comment by njbart** [comment] 2018-01-26 06:52
Ok, got the latest dev binary from SF.

Now, a open ended range like this:

```
\documentclass{article}
\usepackage[style=authoryear]{biblatex}
\usepackage{filecontents}
\begin{filecontents}{\jobname.bib}
@book{item1, author = {NN}, title = {Title}, date = {0000/} }
\end{filecontents}
\addbibresource{\jobname.bib}
\begin{document}
\nocite{*}
\printbibliography
\end{document}
```

fails with this error message:

```
! Package etoolbox Error: Toggle 'abx@bool@enddateunknown' undefined.

See the etoolbox package documentation for explanation.
Type  H <return>  for immediate help.
 ...                                              
                                                  
l.45     \endentry
```

Also, `urldate` being rendered with leading zeros seems inconsistent:

```
\documentclass{article}
\usepackage[style=authoryear]{biblatex}
\usepackage{filecontents}
\begin{filecontents}{\jobname.bib}
@book{item1, author = {NN}, title = {Title}, date = {0000}, urldate = {0000} }
\end{filecontents}
\addbibresource{\jobname.bib}
\begin{document}
\nocite{*}
\printbibliography
\end{document}
```

![screen shot](https://user-images.githubusercontent.com/2765811/35428025-b4ba93c0-0264-11e8-9bbd-9c79b3e0a077.png)

**Comment by moewew** [comment] 2018-01-26 10:55
@Did you get the newest `biblatex` from GitHub `dev` for that? The `abx@bool@enddateunknown` should be fixed there.

The two dates use different date formats. The two (short vs comp) handle leading zeros explicitly differently. I'm not sure if that is a feature or an oversight.

**Comment by njbart** [comment] 2018-01-26 17:51
Right, sorry, didn’t remember to update biblatex as well. So no. 1 is fixed already, and, regarding no. 2, I realize that while the default still looks rather odd to me, it can be modified by setting `datezeros` to false if needed.

**Comment by moewew** [comment] 2018-01-27 11:11
@plk Thank you. The zero issues are fixed now.

**Closed** 2018-01-28 11:28 UTC
Labels: bug
