### ISSUE TITLE
biblatex-3.4beta incompatible with xpatch

### ISSUE THREAD

**Issue by maieul** [plk/biblatex#384] opened 2016-03-19 15:26 UTC
Dear plk,

I have tried the last beta of biblatex3.4 on sourceforge.

It seems to be incompatible with xpatch.

Here a MWE

`````
\documentclass{article}
\usepackage{xpatch}
\usepackage[citestyle=verbose,bibstyle=verbose]{biblatex}
\usepackage{filecontents}
\begin{filecontents}{toto.bib}
@book{Rouquette2012,
	Address = {Tempere},
	Author = {Maïeul Rouquette},
	Publisher = {Atramenta},
	Title = {(Xe)LaTeX appliqué aux sciences humaines},
	Url = {http://www.atramenta.net/books/latex-sciences-humaines/79},
	Year = {2012}
}
\end{filecontents}
\bibliography{toto.bib}
\begin{document}
\cite{Rouquette2012}
\end{document}
`````

After biber (2.5beta) has been run, xelatex fails, without message.  If I comment `\usepackage{xpatch}` all is ok.

**Comment by plk** [comment] 2016-03-19 15:30
I think this may have already been fixed today - can you pull the latest 3.4 biblatex and 2.5 biber and see?

**Comment by maieul** [comment] 2016-03-19 16:01
I have tried now, and it does not work. same problem.

**Comment by plk** [comment] 2016-03-19 16:06
Are you pulling from git or using packaged version? I hadn't pushed git so if so, try again now ...

**Comment by maieul** [comment] 2016-03-19 16:12
I am dowloading from https://sourceforge.net/projects/biblatex/files/?source=navbar
where should I dowload ?

**Comment by plk** [comment] 2016-03-19 16:15
Should be fine - I have uploaded again - make sure the Modified time on the DEV folder says "< 10 Mins ago"

**Comment by maieul** [comment] 2016-03-19 16:22
tried again, with version < 10 mn. Not working.

There was no new biber version (< 20h ago)

**Comment by plk** [comment] 2016-03-19 16:23
Ah, ok, I see, I didn't see you were using xelatex, let me look.

**Comment by maieul** [comment] 2016-03-19 16:26
indeed, with pdflatex is ok.

**Comment by plk** [comment] 2016-03-19 17:18
If you load xpatch after biblatex, also fine. I will ask egreg as he wrote it.

**Comment by maieul** [comment] 2016-03-19 17:21
ok, but unfortunatly, it can happen I need to load it at the begin of some styles

**Comment by plk** [comment] 2016-03-19 17:22
and this worked with 3.3?

**Comment by maieul** [comment] 2016-03-19 17:26
yes ;-)

**Comment by plk** [comment] 2016-03-19 17:30
It's something to do with `citestyle=verbose`

**Comment by maieul** [comment] 2016-03-19 17:34
strange !

**Comment by moewew** [comment] 2016-03-20 07:16
The problem already occurs when only using `xparse`. 

```
\documentclass{article}
\usepackage{xparse}
\usepackage[backend=biber]{biblatex}
\addbibresource{biblatex-examples.bib}

\begin{document}
\cite{sigfridsson}
\printbibliography
\end{document} 
```
When interrupted, the log mentions `\pdf@strcmp`, so I guess the internal tricks `xparse` uses to get `pdfstrcmp` interfere with those used by `pdftexcmds`

Indeed,
```
\documentclass{article}
\usepackage{xparse}
\usepackage{pdftexcmds}

\makeatletter
\let\pdfstrcmp\pdf@strcmp
\makeatother

\begin{document}
\pdfstrcmp{foo}{foo}

\pdfstrcmp{foo}{bar}
\end{document} 
```
also hangs with XeLaTeX on my machine.

Maybe @josephwright  can point out a way to get `strcmp` in a LaTeX3-compatible way? (Or just copy the relevant code from LaTeX3?)

**Comment by plk** [comment] 2016-03-20 11:22
This is fixed in 3.4 now. The issue was the (in fact now unnecessary for biblatex)

```
\let\pdfstrcmp\pdf@strcmp
```
which I was using to fool etextools.
This sends xelatex only into a loop I think when `xpatch` and `pdftexcmds` are both loaded. It's strange as I thought like you that that xelatex used `\strcmp`. `xpatch.sty` makes no mention of these macros but then l3 is hieroglyphics to me ...

**Comment by maieul** [comment] 2016-03-20 12:51
I confirm the problem is fixed. Thank you so much.

**Comment by moewew** [comment] 2016-03-24 08:00
The code still seems to cause some trouble, refer to [Biber 2.4, microtype, and special characters](http://tex.stackexchange.com/q/300395/35864) on TeX.SX or the example below.

```
\documentclass{article}
\usepackage[utf8]{inputenc}
\usepackage{filecontents}
\usepackage{microtype}
\usepackage[backend=biber]{biblatex}

\begin{filecontents}{\jobname.bib}
@book{renyi1970,
  author = {Rényi, Alfréd},
  location = {San Francisco},
  publisher = {Holden-Day},
  title = {Foundations of Probability},
  year = {1970},
}
\end{filecontents}

\addbibresource{\jobname.bib}

\begin{document}
  \cite{renyi1970}
  \printbibliography
\end{document}
```

The problem did not occur with version 2.9a/Biber 1.9.

**Comment by plk** [comment] 2016-03-24 09:01
So you are saying that the issue appeared with 3.0/2.0?

**Comment by moewew** [comment] 2016-03-24 09:10
Not at all! Sorry, I should have been clearer about that. It was just that I tested it with 2.9a/1.9 (which I still had on my machine) to make sure it was not an issue that was there all along.

With `\def\ifcontentempty{}` after `\begin{document}` the error is gone in the dev version. So it probably has to do with that.

**Comment by plk** [comment] 2016-03-24 10:14
@josephwright - I think this is beyond me - a relatively simple macro based on `\pdf@strcmp` from `pdftexcmds` is conflicting with some `microtype` internal. Something to do with `inputenc` and the accents? I imagine you'll work out the issue faster than I will.

**Comment by josephwright** [comment] 2016-03-24 11:48
I'll look at this as soon as can get dev. Biber to build: looks like it will have to be on my Mac as there is an issue building on Windows (not Biber itself, a dependency that is not allowing for the w32 set up correctly).

**Comment by plk** [comment] 2016-03-24 12:39
Avoiding the `pdftexcmds` `\pdf@strcmp` and using normal PDFTeX `\pdfstrcmp` has the same problem.

**Comment by josephwright** [comment] 2016-03-24 12:57
I've not yet been able to test, but my guess is it's exactly the same issue as doing `\edef` on arbitrary input. Doing `\pdfstrcmp{#1}{}` will effectively `\edef` the argument (though without an assignment), so it goes wrong if they are not expandable. You can prevent all expansion using `\unexpanded`, but I think that misses why you wanted this test. Perhaps `\pdfstrctmp{\unexpanded\expandafter{#1}{}}` is what you want: will do exactly one expansion of the first token in `'#1`. (The fact you can't really do 'safe' expansion on arbitrary tokens is a reason I'm not that keen on mixing 'might be a macro' with 'might be literal input'.)

**Comment by plk** [comment] 2016-03-24 13:00
Actually since the bibtex and biber `.def` split in biblatex, the issue isn't between literals and macros (that was part of the motivation for this split) but it's possible for it to be more than one macro - from `biblatex_.def`:

```
\ifcontentempty{\namepartgiven\namepartprefix}
```

I can't rule out with customisable name parts that it wouldn't be more than two either.

**Comment by josephwright** [comment] 2016-03-24 13:03
With LaTeX2e there's not much one can do here, at least if the requirement is that the test is expandable. (Some future format would presumably make everything either fully expandable or engine-protected, and the issue goes away, but at that point there will be a lot more to think about!)

**Comment by plk** [comment] 2016-03-24 13:06
It has to be expandable, yes, mostly to do with indexing requirements and external file writing etc. This macro is just a convenience to prevent people having to write tortuous `\expandafter`s etc. in the higher-level name macros. It was never a problem before when name parts were just hard-coded strings passed in to the name format but that was useless for future development of name support beyond that archaic bibtex `first,last,von,jr` format. Hmm, what to do. Any l3 magic with xparse?

**Comment by josephwright** [comment] 2016-03-24 13:13
The 'natural' way to do this in `expl3` would be to use a generic boolean test; the concept is also available in `etoolbox` as `\ifboolexpre`. I'd therefore consider using that, which will end up with one or more `defvoid` tests and some boolean logic.

**Comment by plk** [comment] 2016-03-24 13:15
I thought I'd tried all that - how would that get round the expanding non-expandable things issue?

**Comment by josephwright** [comment] 2016-03-24 13:18
Using `\ifdefvoid` doesn't do an `\edef` but comes down to a test `\ifx#1\empty`. That doesn't expand anything but does require that `#1` is exactly one token. So if the programmer is always using `\namepartgiven`, _etc._ all is fine with `\ifboolexpre{defvoid\namepartgiven AND defvoid\namepartprefix}` (or something like that: would have to test what PL's syntax was exactly).

**Comment by plk** [comment] 2016-03-24 13:21
Ah, good point. I had a version of 3.4 using only `\ifdefvoid` for exactly this reason for a while but I wanted to be nice to style authors and provide the same sort of "one size fits all" macro solution but I think perhaps this is not a good idea.

**Comment by josephwright** [comment] 2016-03-24 13:40
The only really general solution is to test each part separately, certainly with the restrictions of wanting an expandable test that works safely with pdfTeX.

**Comment by plk** [comment] 2016-03-24 14:13
Ok, I have backed out and used `\ifdefvoid` again with `\ifboolepxe` in the three necessary cases in the `.def`. This isn't very onerous on users and follows standard `etoolbox` macros. The problem goes away with this fix. 3.4 is updated on SF.

**Closed by plk** 2016-03-24 14:13 UTC

**Comment by moewew** [comment] 2016-03-24 14:29
Does this mean one needs to use `\ifdefvoid` with Biber and `\ifempty` with BIbTeX? If so, what do you think of defining `\ifnamepartempty` in the `.sty` and let that default to the correct check so the name format can use the same code with both backends?

**Comment by plk** [comment] 2016-03-24 14:45
Yes. This is part of the reason they `.defs` were split in the first place. It's not just that the macro has to change, it's that the calling semantics also change because of arbitrary namepart support in `biber` now. You can do `\ifblank{#2#3}`, which is done in several places, to check if a prefix+name is blank but you can't do this any more with one macro in the `biber` version because you'd need something expandable which would expand everything then test for emptiness. As @josephwright explains, that's not really possible and I fought with about ten different solutions until I thought the `\pdf@strcmp` thing would do it but there are just too many edge cases. So, `\ifdefvoid` works nicely in the `biber` branch but the calling semantics of this in non-simple cases requires `\ifboolexpe` and so there is no clean way to make it cross-backend compatible. Anyway, this may be a moot point since the overwhelming trend in the current user survey for biblatex is in favour of dropping bibtex as a backend which I suspect may be the conclusion in the medium term.

**Comment by moewew** [comment] 2016-03-24 14:55
The definitions of say, `name:family-given` could be the same safe for the test for emptiness. So if we were to define only the test command backend dependant, then the `name:` macro would be usable with both backends.

But I realise that this is not on top of the priority list, especially if you plan to drop BibTeX support.

**Comment by plk** [comment] 2016-03-24 14:57
Yes, I was going to do this but if bibtex is going away, I'd like to know that first. I hope that the survey will go on the TUG list (thanks to Joseph) and then we'll have some decent data to back up any decision.
