### ISSUE TITLE
fullcite in tabularx: issues with autolang=other

### ISSUE THREAD

**Issue by jendrikw** [plk/biblatex#1056] opened 2020-10-08 12:51 UTC
When compiling the following code with `pdflatex; biber; pdflatex`, I get an error:

```tex
\documentclass{article}
\usepackage[ngerman]{babel}
\usepackage[style=iso-authortitle]{biblatex}
\addbibresource{biblatex-examples.bib}
\usepackage{tabularx}
\begin{document}
\begin{tabularx}{\textwidth}{X}
	\fullcite{baez/article}
\end{tabularx}
\end{document}
```

I get this error:

```
Runaway argument?
ngerman+\unskip \relax \@endpbox \do@row@strut \hskip \col@sep 
! Forbidden control sequence found while scanning use of \bbl@pop@lang.
<inserted text> 
                \par 
l.9 \end{tabularx}
```

Any idea how this happens?

**Comment by moewew** [comment] 2020-10-08 15:40
A structurally similar issue can be reproduced without `biblatex`.
```latex
\documentclass{article}
\usepackage[ngerman]{babel}

\begin{document}
\begin{tabular}{c}
  \begin{otherlanguage}{english}Hello\end{otherlanguage}
\end{tabular}
\end{document}
```
Some additional braces seem to help
```latex
\documentclass{article}
\usepackage[ngerman]{babel}

\begin{document}
\begin{tabular}{c}
  {\begin{otherlanguage}{english}Hello\end{otherlanguage}}
\end{tabular}
\end{document}
```
and so does explicitly pre-loading the language you are going to use
```latex
\documentclass{article}
\usepackage[english,ngerman]{babel}

\begin{document}
\begin{tabular}{c}
  \begin{otherlanguage}{english}Hello\end{otherlanguage}
\end{tabular}
\end{document}
```

So for your MWE both
```latex
\documentclass{article}
\usepackage[ngerman]{babel}
\usepackage[style=iso-authortitle]{biblatex}
\addbibresource{biblatex-examples.bib}
\usepackage{tabularx}
\begin{document}
\begin{tabularx}{\textwidth}{X}
  {\fullcite{baez/article}}
\end{tabularx}
\end{document}
```
and 
```latex
\documentclass{article}
\usepackage[english,ngerman]{babel}
\usepackage[style=iso-authortitle]{biblatex}
\addbibresource{biblatex-examples.bib}
\usepackage{tabularx}
\begin{document}
\begin{tabularx}{\textwidth}{X}
  \fullcite{baez/article}
\end{tabularx}
\end{document}
```
work.

There was a very related bug report for `babel` at https://github.com/latex3/babel/issues/93, see also https://tex.stackexchange.com/q/560876/35864. So you may want to open an issue at the `babel` bugtracker.

**Comment by jendrikw** [comment] 2020-10-08 19:57
I see, thanks for investigating. This is a duplicate of https://github.com/latex3/babel/issues/93 and can be closed.

**Comment by moewew** [comment] 2020-10-09 06:20
Well, it's not a duplicate of https://github.com/latex3/babel/issues/93 since that MWE works fine in `babel` 3.50, but the usage discussed here still fails. I opened https://github.com/latex3/babel/issues/97 to discuss this.

**Comment by moewew** [comment] 2020-11-22 15:03
Closing this since this was an issue with `babel` that was addressed by the `babel` developer (https://github.com/latex3/babel/issues/97). The MWE compiles fine with
```
babel.sty    2020/10/27 3.51 The Babel package
```

**Closed by moewew** 2020-11-22 15:03 UTC
Labels: external
