### ISSUE TITLE
malformed bcf file since recent update of biblatex

### ISSUE THREAD

**Issue by AndrewJHetzel** [plk/biblatex#1236] opened 2022-07-25 02:57 UTC
I want to bring to your attention an issue with the biblatex package creating a malformed bcf file since v.3.18 of biblatex was made available. It appears to be an issue that smacks of tex.stackexchange.com/questions/343856 of 5 years ago (although the patch proposed there does not work for me, even when placed just before the call of the biblatex package). In particular, since I was last able to compile a bibliography a little more than a month ago, I have only updated (not added to) the packages that comprise my custom class file. Those packages are as follows: microtype, babel (with the "american" option), csquotes, ragged2e, amsfonts, amssymb, amsthm, latexsym, mathtools, mathrsfs, interval, bigdelim, colortbl, multirow, centernot, thmtools, enumitem, totcount, cleveref, graphicx, xcolor, tikz, and listings. Furthermore, I call biblatex as my last package with the following options: style=apa, backend=biber, citestyle=numeric-comp, language=american, defernumbers=true (in addition to, of course, \DeclareLanguageMapping{american}{american-apa}).

Curiously enough, my test document's bibliography compiles just fine on Overleaf without any warning or error. However, it fails to compile on my PC (where I use the MikTeX distribution) under both WinEdt 11 and TeXworks.

If you could address this problem at your earliest convenience, it would be greatly appreciated.

**Comment by moewew** [comment] 2022-07-25 04:52
Is your problem with the `quantumarticle` document class or does the linked question just show a behaviour that is similar to what you observed?

Can you please share a small example document that reproduces your issue with as little excess code as possible?

**Comment by AndrewJHetzel** [comment] 2022-07-25 14:51
The linked question just shows a behaviour that is similar to what I have observed.

I am the architect of the class file that my university uses for theses and dissertations created using LaTeX. The class file is named TNTmathTHESIS4.3 and the file that students compile from is named TNTcontrol. I have attached the relevant files from the failed compilation. If you need anything else, let me know.

[failed_bcf.zip](https://github.com/plk/biblatex/files/9182224/failed_bcf.zip)

**Comment by moewew** [comment] 2022-07-25 15:11
That document setup where `\begin{document}...\end{document}` is essentially hidden inside an looks very unusual to me.

Unfortunately, the class is 1800 lines long and it will take me a while to understand what each bit does. So any help you could provide in debugging (make the `.cls` file simpler, remove stuff that is unrelated to the issue) would be very much appreciated.

For now I can note that a more usual document setup like
```latex
\documentclass{TNTmathTHESIS4.3}

\addbibresource{biblatex-examples.bib}

\begin{document}
Lorem \autocite{sigfridsson}

\printbibliography
\end{document}
```
appears to compile fine for me.

**Comment by moewew** [comment] 2022-07-25 15:47
I don't think this is strictly speaking a `biblatex` problem.

## Observation 1
If we comment out `\normalsize` in `\def\tnt@referencessection`, i.e. make it
```latex
\long\def\tnt@referencessection{%
    \cleardoublepage
    \phantomsection
    \addcontentsline{toc}{chapter}{References}
    \@ifundefined{tnt@bibreferences}{%
        \begin{center}
            \textbf{REFERENCES}
        \end{center}
        \LineJump{1}
        \textlangle\textlangle References Not Provided\textrangle\textrangle
    }{%
        \ifcategoryempty{cited}{%
            \begin{center}
                \textbf{REFERENCES}
            \end{center}
            \LineJump{1}
            \textlangle\textlangle References Not Cited\textrangle\textrangle
        }{%
            \begingroup
            \renewcommand*{\addcontentsline}[3]{}
            \bibitemsep\onelineskip
            \begin{SingleSpace}
                \printbibliography[%
                    category={cited},%
                    title={%
                        %\normalsize
                        \LineJump{-0.5}%
                        \centerline{REFERENCES}%
                        \LineJump{0.5}
                    }
                ]
            \end{SingleSpace}
            \endgroup
        }
    }
    \clearpage
}
```
the document compiles.

## Observation 2
Tracking down the settings of the class and interpolating what `biblatex` does with the title we end up with the following example document that also hangs in the same way.
```latex
\documentclass{memoir}

\makechapterstyle{tech}{%
    \renewcommand*{\printchaptertitle}[1]{%
        \MakeTextUppercase{##1}%
    }
}

\begin{document}
Lorem
\chapterstyle{tech}
\chapter{\normalsize foo}
\end{document}
```
Indeed an even smaller example is
```latex
\documentclass{memoir}

\begin{document}
Lorem

\MakeUppercase{\normalsize foo}
\end{document}
```
Curiously, the same idea works fine in the standard `article` class
```latex
\documentclass{article}

\begin{document}
Lorem

\MakeUppercase{\normalsize foo}
\end{document}
```

My theory is that the problem is related to the new implementation of the case changing macros in the new LaTeX kernel (2022-06-01 and above). For some reason that seems to be `memoir`-specific, though.

`\protect`ing the `\normalfont` lets things compile again, but I am not sure if that is really the solution
```latex
\documentclass{memoir}

\begin{document}
Lorem

\MakeUppercase{\protect\normalsize foo}
\end{document}
```

You may want to take this to the `memoir` maintainer, though I must say that I think that formatting commands like `\normalfont`, `\LineJump{-0.5}`, `\centerline` should not be used inside the argument of `\chapter`. That argument should be the title only. Formatting should be applied via the appropriate interface for heading formatting.

**Comment by AndrewJHetzel** [comment] 2022-07-25 17:46
Will do. If you're curious, I paired down TNTmathTHESIS4.3 significantly in the attached zip file. What I'm seeing now is that the document compiles, albeit without the appropriate bibliography. In fact, the reason I thought that this may be a biblatex problem is that everything worked fine with the original TNTmathTHESIS4.3 until I introduced citations in the test document.

[failed_bcf_2.zip](https://github.com/plk/biblatex/files/9183639/failed_bcf_2.zip)

**Comment by moewew** [comment] 2022-07-25 19:39
This is a timing problem with `\AtBeginDocument`.

`\addbibresource` is a command that needs to be executed in the preamble. The class has it in an `\AtBeginDocument`.

In the previous version of the class you sent above earlier invocations of `\AtBeginDocument` in `.cls` ensured that the hooks are executed in the order `TNTmathTHESIS4.3, biblatex`. So first your class sets `\addbibresource`, then `biblatex`'s hook uses it.

In the reduced version of the class the order is `biblatex, TNTmathTHESIS4.3`, which means that `biblatex` first does its bookkeeping and then your class sets `\addbibresource` after that. So you come in too late.

I'd recommend you don't put `\addbibresource` in an `\AtBeginDocument` hook. But if you insist this is what you need, you need to set up hook rules to make sure your `\addbibresource` gets processed before `biblatex`'s `begindocument` hook.

**Comment by u-fischer** [comment] 2022-07-25 21:38
> \protecting the \normalfont lets things compile again, but I am not sure if that is really the solution

It is. It compiles with article, as size10.clo makes \normalsize robust:

~~~~
\ifx\MakeRobust\@undefined \else
    \MakeRobust\normalsize
\fi
~~~~

and memoir destroys that again.

**Comment by moewew** [comment] 2022-07-30 06:39
Closing this since the issues in the MWEs had nothing to do with `biblatex` as such.

**Closed by moewew** 2022-07-30 06:39 UTC
Labels: invalid
