### ISSUE TITLE
biblatex records files not loaded in the filelist

### ISSUE THREAD

**Issue by u-fischer** [plk/biblatex#719] opened 2018-02-24 22:53 UTC
In `\blx@inputonce` biblatex adds files with `\@addtofilelist{#1}}` to the file list regardless if they are actually found and loaded. E.g.

~~~~
\listfiles
\documentclass{article}
\usepackage{biblatex}
\addbibresource{biblatex-examples}

\begin{document}
This is my text
\end{document}
~~~~

says in the log

~~~~
Package biblatex Info: ... file 'biblatex-dm.cfg' not found.
~~~~

and later on the in the file list

~~~~
biblatex-dm.cfg
~~~~

Imho this is confusing and it disturbs the working of packages like snapshot, see https://tex.stackexchange.com/questions/417086/biblatex-dm-cfg-not-found-by-bundledoc

**Comment by moewew** [comment] 2018-02-25 07:10
Thank you very much for the report.

Please have a look at https://github.com/plk/biblatex/compare/dev...moewew:filelist. The problem should be solved there.

**Comment by LukasCBossert** [comment] 2018-02-25 09:57
Great! Thanks for the quick fix! Wouldn’t it be possible to have it fixed in `3.11` (version `3.12` seems so far aways).

**Comment by moewew** [comment] 2018-02-25 10:04
Not sure what @PLK's stance on this is. Release is still blocked because the last Biber binaries have not been built yet. So theoretically we could stuff this into 3.11. The problem is that we have already uploaded 3.11 to SourceForge. While this is not the official CTAN release, this could cause version confusion with people downloading from SourceForge.

I have another branch (https://github.com/plk/biblatex/compare/dev...moewew:saveannotations) that could be merged now as well.

Anyway, I'm hoping to release 3.12 with bug fixes for 3.11 before the TeX live freeze (12 March). But I admit that due to the SourceForge mess and Biber building delay, that might not be possible.

**Comment by LukasCBossert** [comment] 2018-02-25 10:05
I see - a lot of things are connected to it. Until the fixing release I can patch locally. Thanks.

**Comment by moewew** [comment] 2018-02-25 10:09
For your purposes
```latex
\protected\long\def\blx@inputonce#1#2#3#4#5#6{%
  \ifcsundef{blx@file@#1}
    {\blx@info@noline{Trying to load #2..}%
     \IfFileExists{#1}
       {\blx@info@noline{... file '#1' found}%
        #3\@@input\@filef@und#4#5%
        \listxadd\blx@list@req@stat{#1}%
        \@addtofilelist{#1}}
       {\blx@info@noline{... file '#1' not found}#6}%
     \global\cslet{blx@file@#1}\@empty}
    {#5}}
```
should be enough to patch things for now.

**Comment by LukasCBossert** [comment] 2018-02-25 10:11
Perfect. I am fine with this and can wait for `3.12`.

**Comment by plk** [comment] 2018-02-25 10:41
@moewew - I think we can do this all in 3.11 - SF continues to have issues which are delaying things so feel free to merge the new fixes and I'll update 3.11 on SF as and when it comes back up. Still waiting for some biber binary uploads.

**Comment by moewew** [comment] 2018-02-25 10:54
OK. I will merge this to dev then, apply one or two other tweaks and merge to master. Could you please run the test suite once I have merged to master and update the test files? I will also tweak the docs, so they would have to recompiled again.

Have you heard anything back about the missing Biber binaries? I noticed that the FreeBSD binaries could take quite a while in the past.

**Comment by plk** [comment] 2018-02-25 10:57
I haven't heard from them but sometimes they upload without telling me. However, the SF files page for biber is down and I can't check ...

**Comment by LukasCBossert** [comment] 2018-02-25 12:33
@moewew would you mind writing a quick answer at https://tex.stackexchange.com/questions/417086/biblatex-dm-cfg-not-found-by-bundledoc ?

**Comment by plk** [comment] 2018-02-25 13:51
@moewew Tests all pass with latest merges, just had to update the localisation tests.

**Comment by LukasCBossert** [comment] 2018-02-25 22:24
With this (called `test.tex`)

```
\listfiles
\RequirePackage{snapshot}
\documentclass{article}
\usepackage{biblatex}
\addbibresource{biblatex-examples}
\protected\long\def\blx@inputonce#1#2#3#4#5#6{%
  \ifcsundef{blx@file@#1}
    {\blx@info@noline{Trying to load #2..}%
     \IfFileExists{#1}
       {\blx@info@noline{... file '#1' found}%
        #3\@@input\@filef@und#4#5%
        \listxadd\blx@list@req@stat{#1}%
        \@addtofilelist{#1}}
       {\blx@info@noline{... file '#1' not found}#6}%
     \global\cslet{blx@file@#1}\@empty}
    {#5}}
\begin{document}
This is my text
\end{document}
```
I still have `  *{file}   {biblatex-dm.cfg}{0000/00/00 v0.0}` in the `.dep`-file and `bundledoc: "kpsewhich -progname=latex $BDINPUTS" (BDINPUTS="biblatex-dm.cfg") failed to find biblatex-dm.cfg` in my terminal after `bundledoc test.dep`.

**Comment by u-fischer** [comment] 2018-02-25 22:30
Your redefinition is too late. biblatex is looking for the file (and recording it) during the package loading.

**Comment by LukasCBossert** [comment] 2018-02-25 22:37
Could you provide a MWE please. It seems like it doesn’t matter where at which place I insert the patch I always have `biblatex-dm.cfg` in the `.dep`-file:

```
\listfiles
\RequirePackage{snapshot}
\protected\long\def\blx@inputonce#1#2#3#4#5#6{%
  \ifcsundef{blx@file@#1}
    {\blx@info@noline{Trying to load #2..}%
     \IfFileExists{#1}
       {\blx@info@noline{... file '#1' found}%
        #3\@@input\@filef@und#4#5%
        \listxadd\blx@list@req@stat{#1}%
        \@addtofilelist{#1}}
       {\blx@info@noline{... file '#1' not found}#6}%
     \global\cslet{blx@file@#1}\@empty}
    {#5}}
\documentclass{article}
\usepackage[backend=biber,style=archaeologie]{biblatex}
\addbibresource{archaeologie-examples.bib}

\begin{document}
This is my text \cite{Mann2011} 
\end{document}
```

**Comment by u-fischer** [comment] 2018-02-25 22:42
You can't patch this outside biblatex in this way. You could try this as a work-around:

~~~~
\documentclass{article}

\usepackage{biblatex}
\usepackage{xpatch}
\makeatletter
\patchcmd\@filelist{biblatex-dm.cfg,}{}{}{\fail}
\makeatletter
\begin{document}
...
\end{document}
~~~~

**Comment by LukasCBossert** [comment] 2018-02-25 22:44
great. that works - I tried to patch within the `biblatex.sty` but didn’t change anything. Your MWE works fine!

**Comment by moewew** [comment] 2018-02-26 06:36
Ah yes, I'm sorry. The redefinition only works if the original definition in `biblatex.sty` is replaced with the new one. Then things should work.

**Comment by moewew** [comment] 2018-03-07 08:14
`biblatex` 3.11 and Biber 2.11 have been released. Unfortunately, we didn't make it in time for the TeX live freeze, so the versions are only available on TeX live 2018 pretest and MikTeX at the moment.

The introductory MWE gives the expected output now.

**Closed by moewew** 2018-03-07 08:14 UTC
Labels: bug
