### ISSUE TITLE
Title ending in "[...]" prints without dot/ missing final dot

### ISSUE THREAD

**Issue by ebouna** [plk/biblatex#1185] opened 2021-10-01 21:20 UTC
Consider the following MWE:
```
\begin{filecontents}{mybib.bib}
@article{gasparovic1943,
  title = {{\normalfont \bibstring{reviewof}} Milan Begović: Giga Barićeva. Roman iz [...]. Izvanredno izdanje. Treće izdanje, [...], Zagreb 1943 [...]},
  author = {Gašparović, Stanko},
  date = {1943},
  journaltitle = {Prosvjetni život},
  volume = {14--15},
  number = {2},
  pages = {351--352},
  langid = {croatian}
}
\end{filecontents}
\documentclass{article}
\usepackage[style=numeric]{biblatex}
\bibliography{mybib}  
\begin{document}
Test~\cite{gasparovic1943}.
\printbibliography
\end{document}
```
I have shortened the title, which is originally very long, and added "[...]". When printing the bibliography, at the end of the title there is no dot. If one removes "...]" from the end of the title, the dot is ouput. This behaviour seems to me faulty.  
The same happens (i.e. the is omitted), if one puts "[…]" (= [ - ellipsis - ]) at the end of the title.
If this is the desired behaviour, I'd be glad if you could explain me why it should be like this. Many thanks in advance.

**Comment by moewew** [comment] 2021-10-02 07:15
`biblatex`'s punctuation tracker tries to avoid double punctuation. The punctuation tracker is based on space factors and space factors ignore brackets. That means that as far as the tracker is concerned your title ends in a period, so no additional period is inserted as that would result in double punctuation.

You want the tracker to ignore the punctuation you added.This can be done by adding a `\@` directly after the offending punctuation. So you would say `[...]\@` instead of `[...]`. Note that ellipsis dots should ideally be `\dots`/`\textellipsis`, not `...`.

For ellipses like this (with brackets) I strongly recommend you use the `csquotes` command `\mktextelp` (loading `csquotes` is a good idea if you use `biblatex` anyway)

```latex
\documentclass[english]{article}
\usepackage[T1]{fontenc}
\usepackage{babel}
\usepackage{csquotes}

\usepackage[style=numeric]{biblatex}

\begin{filecontents}{\jobname.bib}
@article{gasparovic1943,
  title        = {{\normalfont \bibstring{reviewof}} Milan Begović:
                  Giga Barićeva. Roman iz \mktextelp. Izvanredno izdanje.
                  Treće izdanje, \mktextelp, Zagreb 1943 \mktextelp},
  author       = {Gašparović, Stanko},
  date         = {1943},
  journaltitle = {Prosvjetni život},
  volume       = {14--15},
  number       = {2},
  pages        = {351--352},
  langid       = {croatian},
}
\end{filecontents}
\addbibresource{\jobname.bib}  
\begin{document}
Test~\cite{gasparovic1943}.
\printbibliography
\end{document}
```
> Stanko Gašparović. “Rev. of Milan Begović: Giga Barićeva. Roman iz [...]. Izvanredno izdanje. Treće izdanje, [...], Zagreb 1943 [...]”. In: Prosvjetni život 14–15.2 (1943), pp. 351–352.

![image of output quoted above](https://user-images.githubusercontent.com/6755835/135707381-08ba0549-74aa-4854-b571-4aa8f4024abe.png)

**Comment by ebouna** [comment] 2021-10-02 09:26
Thanks a lot for this excellent explanation ! This was really helpful. I'll
do as you suggested.

Am Samstag, 2. Oktober 2021 schrieb moewew ***@***.***>:

**Comment by moewew** [comment] 2021-10-06 15:33
I think the `biblatex` side of things behaves reasonably here, so I'll close this as "works as intended".

**Closed by moewew** 2021-10-06 15:33 UTC

**Comment by ebouna** [comment] 2021-10-08 12:33
Yes. Everything is ok. Thanks a lot.
