### ISSUE TITLE
\defbibcheck example for shortjournal in manual does not work with locallabelwidth option

### ISSUE THREAD

**Issue by dcpurton** [plk/biblatex#990] opened 2020-04-12 15:18 UTC
I'm not sure if this is a bug or just that the example `\defbibcheck{shortjournal}{...}` in the manual is not sophisticated enough.

This check does not work if the `locallabelwidth` option is set (`\printbiblist[locallabelwidth]{shortjournal}`). The list ends up being empty even if it should contain items.

It would be nice to have a working example in the manual that covers this case.

# MWE

```TeX
\documentclass{article}

\begin{filecontents}[overwrite]{\jobname.bib}
@article{a,
  title = {First Title},
  journaltitle = {Journal Title},
  shortjournal = {JT},
  volume = {1},
  date = {2020},
  pages = {1-2}
}
@article{b,
  title = {Second Title},
  journaltitle = {Journal Title},
  shortjournal = {JT},
  volume = {1},
  date = {2020},
  pages = {1-2}
}
\end{filecontents}

\usepackage{biblatex}
\addbibresource{\jobname.bib}

\DeclareBibliographyDriver{shortjournal}{%
  \printfield{journaltitle}}

\defbibcheck{shortjournal}{%
  \iffieldundef{shortjournal}
    {\skipentry}
    {\iffieldundef{journaltitle}
       {\skipentry}
       {\ifcsdef{\strfield{shortjournal}=\strfield{journaltitle}}
          {\skipentry}
          {\savefieldcs{journaltitle}{\strfield{shortjournal}=\strfield{journaltitle}}}}}}

\begin{document}
\nocite{*}
% Does not work with locallabelwidth option
\printbiblist[locallabelwidth]{shortjournal}
\printbibliography
\end{document}
```

This produces:

![tex090](https://user-images.githubusercontent.com/6268044/79072427-261bc100-7d20-11ea-9b9e-00ca0eee63bf.png)

Without the `locallabelwidth` option, it produces:

![tex090](https://user-images.githubusercontent.com/6268044/79072459-464b8000-7d20-11ea-9502-9aaf16309400.png)

**Comment by dcpurton** [comment] 2020-04-12 15:41
Now that I think about it, the example in the manual doesn't deal with refsections either.

Maybe this should be a question for tex.stackexchange.

**Comment by moewew** [comment] 2020-04-13 11:39
Mhhh, I'd have said this *should* work, it doesn't at the moment, because `locallabelwidth` essentially requires that the entries are processed twice: Once to measure the lengths and then a second time for typesetting.

When the entries are processed for `locallabelwidth` we (among other things) define `\strfield{shortjournal}=\strfield{journaltitle}`. Then in the actual typesetting run this command is already defined and the entries are skipped.

**Comment by moewew** [comment] 2020-04-13 11:44
I have no idea how we could work around this with the current setup. I guess things would work if we avoided the two loops through all entries and instead write the maximal label length to the `.aux` file and pick it up from there. That would cost us an additional LaTeX run, but would avoid having to cycle through all entries twice.

**Comment by moewew** [comment] 2020-04-13 13:25
Pushed https://github.com/plk/biblatex/commit/3d2148aa1e3499626f93044eb80c9e850284ef8f. Hopefully, that resolves this issue. Testing (especially in more complex and longer documents) would be appreciated?

**Comment by plk** [comment] 2020-04-13 13:53
Slight error in 31?

<img width="917" alt="Screenshot 2020-04-13 at 3 52 pm" src="https://user-images.githubusercontent.com/1220851/79125685-d7613c00-7d9e-11ea-847a-d4a5599fe317.png">

**Comment by moewew** [comment] 2020-04-13 13:54
Ugh! I thought I had fixed that. I'll see to it.

**Comment by moewew** [comment] 2020-04-13 14:00
@plk That was a typo in https://github.com/plk/biblatex/commit/50b990c0fcd385d4117998f13d8ae8c850e966f5, fixed in https://github.com/plk/biblatex/commit/01b46e0c593f0c959fcd10ee224fb9941f644bdf. (Not the error I had in mind, but fortunately still easily fixed.)

**Comment by plk** [comment] 2020-04-13 14:16
All looks fine now.

**Comment by moewew** [comment] 2020-04-13 14:32
Phew! I was dreading my typos would never stop. I should really try and get the test suite running on my virtual machine again... Thanks for running the tests.

**Comment by plk** [comment] 2020-04-13 14:38
It's fine - I have to merge these with the multiscript branch and run tests anyway.

**Comment by dcpurton** [comment] 2020-04-14 10:13
Would you consider adding a `\therefsection` too?

So the test would be:

```TeX
\threfsection-\strfield​{shortjournal}=​\strfield​{journaltitle}}
```

Or something like that.

**Comment by moewew** [comment] 2020-04-14 18:14
> 
> 
> Would you consider adding a `\therefsection` too?
> 
> So the test would be:
> 
> ```
> \therefsection-\strfield​{shortjournal}=​\strfield​{journaltitle}
> ```
> 
> Or something like that.

To the documentation, you mean?

**Comment by dcpurton** [comment] 2020-04-15 09:51
@moewew, yes to the documentation. It's not essential, but I notice in general things just work with and without refsections, but this example is one that won't and I remember it took me a little while to figure out I needed to add it in to make this work with refsections.

**Comment by moewew** [comment] 2020-04-15 15:32
Let me know what you think about https://github.com/plk/biblatex/commit/200e3cf74e375d3f4082dc36cbbd0f878c921847. I had to fight with the font size for a bit, because the long lines looked awful when they were broken.

**Comment by moewew** [comment] 2020-04-20 15:16
@dcpurton Could you test the new code for `locallabelwidth` using the `.aux` in your real world document? (I think you won't even need a dev version of Biber, v2.14 will do fine. The `biblatex` dev release on SourceForge doesn't contain this change yet, so you'll have to install from the git repository. I'll be happy to provide a zipped TDS subtree if it helps.)

**Comment by dcpurton** [comment] 2020-04-23 14:47
@moewew I tried the dev build on the document I discovered this problem.

It does give data in the lists of abbreviations, which it didn't before. However, it doesn't actually create different label widths.

This may be because my abbreviation code is buggy, though.

I'll keep investigating.

**Comment by moewew** [comment] 2020-04-24 13:10
Hrm, maybe one of the tests that should avoid cluttering the `.aux` files with unnecessary label widths is misguided. Or there is a bug in reading back those lengths. Do the lengths that make it to the `.aux` file look OK?

I'll be happy to look at a slightly larger example if a real MWE is too tricky to produce, though I expect that it should be possible to build a fairly minimal example (custom filters and the likes are fine).

**Comment by moewew** [comment] 2020-05-10 07:10
@dcpurton Can I bother you about this again? Did you manage to reproduce the problem you were talking about in an MWE? (Since I'm quite interested in resolving the issue I'll happily take a not so minimal example as well.)

**Comment by moewew** [comment] 2020-06-27 07:52
@dcpurton Did you have another look at this? I still can't manage to reproduce an issue like the one you describe with the new code.

**Comment by dcpurton** [comment] 2020-06-27 08:20
Sorry! Been busy with other things. I'll try and get to it.

**Comment by moewew** [comment] 2020-06-27 12:48
Thank you.

**Comment by moewew** [comment] 2021-01-04 15:37
Closing this since the MWE works fine now. If you can find the time to reproduce the issue you were talking about or I missed anything else, just open a new issue.

**Closed by moewew** 2021-01-04 15:37 UTC
Labels: bug
