### ISSUE TITLE
items in the reference list cannot be layout across the page.

### ISSUE THREAD

**Issue by Vincent-zcm** [plk/biblatex#1188] opened 2021-10-04 12:39 UTC
When I am using this biblatex with biber, there will always be a little empty space in the page which cannot be filled by the next item, even if the height of the empty space is wider that that of the baselineskip.

**Comment by moewew** [comment] 2021-10-04 15:39
`biblatex` just uses a normal list environment, so the effect you are describing may well be a general limitation of generic LaTeX list environments in your document class and not something `biblatex` can realistically do anything about.

In any case, I'm afraid we can only investigate this issue further if you can share an example document with us that reproduces the undesirable effect with as little excess code as possible. I am aware that it may take some time to come up with a suitable example document for a context-dependent problem like this, but I'm afraid it is your best chance of having the problem looked at.

**Comment by Vincent-zcm** [comment] 2021-10-05 03:25
| |
ZhChm
|
|
***@***.***
|
签名由网易邮箱大师定制


On 10/5/2021 ***@***.***> wrote：
Thanks for your time. There is a zip file in the attachment of this email, which shows the problem I am facing. I am looking forwarding to your answer, thank you again!


| |
ZhChm
|
|
***@***.***
|
签名由网易邮箱大师定制


On 10/4/2021 ***@***.***> wrote：

biblatex just uses a normal list environment, so the effect you are describing may well be a general limitation of generic LaTeX list environments in your document class and not something biblatex can realistically do anything about.

In any case, I'm afraid we can only investigate this issue further if you can share an example document with us that reproduces the undesirable effect with as little excess code as possible. I am aware that it may take some time to come up with a suitable example document for a context-dependent problem like this, but I'm afraid it is your best chance of having the problem looked at.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by Vincent-zcm** [comment] 2021-10-05 03:26
Thanks for your time. There are two files in the attachment of this email, which show the problem I am facing. I am looking forwarding to your answer, thank you again!


| |
ZhChm
|
|
***@***.***
|
签名由网易邮箱大师定制


On 10/5/2021 ***@***.***> wrote：




| |
ZhChm
|
|
***@***.***
|
签名由网易邮箱大师定制


On 10/5/2021 ***@***.***> wrote：
Thanks for your time. There is a zip file in the attachment of this email, which shows the problem I am facing. I am looking forwarding to your answer, thank you again!


| |
ZhChm
|
|
***@***.***
|
签名由网易邮箱大师定制


On 10/4/2021 ***@***.***> wrote：

biblatex just uses a normal list environment, so the effect you are describing may well be a general limitation of generic LaTeX list environments in your document class and not something biblatex can realistically do anything about.

In any case, I'm afraid we can only investigate this issue further if you can share an example document with us that reproduces the undesirable effect with as little excess code as possible. I am aware that it may take some time to come up with a suitable example document for a context-dependent problem like this, but I'm afraid it is your best chance of having the problem looked at.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by moewew** [comment] 2021-10-05 05:10
There are no files in the posts on GitHub and no attachment in the emails I received from GitHub. But I'd really rather not deal with `.zip` files (especially because they don't encourage people to send small examples).

Ideally you would just post a minimised (as far as possible) example document as text right here.

**Comment by Vincent-zcm** [comment] 2021-10-05 05:20
I feel so sorry about the last email and thank you for answering me. There is a PDF file and a tex file in the attachment and the bib file is omitted. The PDF file was built by the tex file. Looking forward to your reply.


| |
ZhChm
|
|
***@***.***
|
签名由网易邮箱大师定制


On 10/5/2021 ***@***.***> wrote：

There are no files in the posts on GitHub and no attachment in the emails I received from GitHub. But I'd really rather not deal with .zip files (especially because they don't encourage people to send small examples).

Ideally you would just post a minimised (as far as possible) example document as text right here.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by moewew** [comment] 2021-10-05 05:23
We don't necessarily need to see the PDF file.

You can paste the contents of your `.tex` file right here and if your `.bib` file is required you can paste it here as well. (That is usually easier to do from the GitHub web interface than via email reply.)

For example like this

```latex
\documentclass[british]{article}
\usepackage[T1]{fontenc}
\usepackage{babel}
\usepackage{csquotes}

\usepackage[backend=biber, style=authoryear]{biblatex}


\addbibresource{biblatex-examples.bib}

\begin{document}
Lorem \autocite[381]{sigfridsson}

\printbibliography
\end{document}
```

**Comment by Vincent-zcm** [comment] 2021-10-05 05:36
The following is the contests of my .tex file.


\documentclass{ctexbook}
\usepackage{geometry}
\usepackage{fancyhdr}
\usepackage[backend=biber,
style=gb7714-2015,
citestyle=gb7714-2015,
gbnamefmt=lowercase, 
gbpub=false, 
gbpunctin=false, 
mincitenames=3, maxcitenames=3, 
autocite=superscript]{biblatex}
\defbibenvironment{bibliography}
{\list
{\printfield[labelnumberwidth]{labelnumber}}
{\setlength{\leftmargin}{0mm}
\setlength{\itemindent}{3.5em}
\setlength{\itemsep}{2pt}
    \setlength{\parsep}{2pt}
}}
{\endlist}
{\item}
\def\baselinestretch{1.25}
\geometry{
a4paper, 
hmargin = 30mm, top = 20mm, bottom = 32mm,
headsep = 0mm, headheight = 10mm, footskip = 8mm, 
}
\fancypagestyle{plain}{
  \fancyhf{}
  \renewcommand{\headrulewidth}{1pt}
  \renewcommand{\footrulewidth}{1pt}
  \fancyhead[C]{\zihao{5}\normalfont{biblatex}}
  \fancyfoot[C]{\zihao{5}\normalfont{page\ \thepage\ }}
}
\ctexset{
chapter = {
beforeskip = {-3.4mm}, afterskip = {5mm},
    format = {\mdseries\heiti\zihao{3}\centering}
  }
}


\addbibresource{thesis.bib}
\begin{document}
\chapter{绪论}


I LOVE \LaTeX\cite{ref1,ref2,ref3,ref4,ref5,ref6,ref7,ref8,ref9,ref10,ref11,ref12,ref13,ref14,ref15,ref16,ref17,ref18,ref19}。


You can see that there is a blank space after the reference[12] but the reference[13] cannot fill this space. 


\printbibliography[heading = bibintoc]
\end{document}


The following is the contents in my .bib file.
@article{ref1,
  author  = {biblatex},
  title   = {how to use biblatex how to use biblatex how to use biblatex how to use biblatex how to use biblatex},
  journal = {how to use biblatex how to use biblatex how to use biblatex how to use biblatex how to use biblatex},
  number  = {1},
  year    = {2021},
  pages   = {1-100}
}
@article{ref2,
  author  = {biblatex},
  title   = {how to use biblatex how to use biblatex how to use biblatex how to use biblatex how to use biblatex},
  journal = {how to use biblatex how to use biblatex how to use biblatex how to use biblatex how to use biblatex},
  number  = {1},
  year    = {2021},
  pages   = {1-100}
}
@article{ref3,
  author  = {biblatex},
  title   = {how to use biblatex how to use biblatex how to use biblatex how to use biblatex how to use biblatex},
  journal = {how to use biblatex how to use biblatex how to use biblatex how to use biblatex how to use biblatex},
  number  = {1},
  year    = {2021},
  pages   = {1-100}
}
@article{ref4,
  author  = {biblatex},
  title   = {how to use biblatex how to use biblatex how to use biblatex how to use biblatex how to use biblatex},
  journal = {how to use biblatex how to use biblatex how to use biblatex how to use biblatex how to use biblatex},
  number  = {1},
  year    = {2021},
  pages   = {1-100}
}
@article{ref5,
  author  = {biblatex},
  title   = {how to use biblatex how to use biblatex how to use biblatex how to use biblatex how to use biblatex},
  journal = {how to use biblatex how to use biblatex how to use biblatex how to use biblatex how to use biblatex},
  number  = {1},
  year    = {2021},
  pages   = {1-100}
}
@article{ref5,
  author  = {biblatex},
  title   = {how to use biblatex how to use biblatex how to use biblatex how to use biblatex how to use biblatex},
  journal = {how to use biblatex how to use biblatex how to use biblatex how to use biblatex how to use biblatex},
  number  = {1},
  year    = {2021},
  pages   = {1-100}
}
@article{ref6,
  author  = {biblatex},
  title   = {how to use biblatex how to use biblatex how to use biblatex how to use biblatex how to use biblatex},
  journal = {how to use biblatex how to use biblatex how to use biblatex how to use biblatex how to use biblatex},
  number  = {1},
  year    = {2021},
  pages   = {1-100}
}
@article{ref7,
  author  = {biblatex},
  title   = {how to use biblatex how to use biblatex how to use biblatex how to use biblatex how to use biblatex},
  journal = {how to use biblatex how to use biblatex how to use biblatex how to use biblatex how to use biblatex},
  number  = {1},
  year    = {2021},
  pages   = {1-100}
}
@article{ref8,
  author  = {biblatex},
  title   = {how to use biblatex how to use biblatex how to use biblatex how to use biblatex how to use biblatex},
  journal = {how to use biblatex how to use biblatex how to use biblatex how to use biblatex how to use biblatex},
  number  = {1},
  year    = {2021},
  pages   = {1-100}
}
@article{ref9,
  author  = {biblatex},
  title   = {how to use biblatex how to use biblatex how to use biblatex how to use biblatex how to use biblatex},
  journal = {how to use biblatex how to use biblatex how to use biblatex how to use biblatex how to use biblatex},
  number  = {1},
  year    = {2021},
  pages   = {1-100}
}
@article{ref10,
  author  = {biblatex},
  title   = {how to use biblatex how to use biblatex how to use biblatex how to use biblatex how to use biblatex},
  journal = {how to use biblatex how to use biblatex how to use biblatex how to use biblatex how to use biblatex},
  number  = {1},
  year    = {2021},
  pages   = {1-100}
}
@article{ref11,
  author  = {biblatex},
  title   = {how to use biblatex how to use biblatex how to use biblatex how to use biblatex how to use biblatex},
  journal = {how to use biblatex how to use biblatex how to use biblatex how to use biblatex how to use biblatex},
  number  = {1},
  year    = {2021},
  pages   = {1-100}
}
@article{ref12,
author  = {biblatex},
title   = {how to use biblatex how to use biblatex how to use biblatex how to use biblatex how to use biblatex},
journal = {how to use biblatex how to use biblatex how to use biblatex how to use biblatex how to use biblatex},
number  = {1},
year    = {2021},
pages   = {1-100}
}


@article{ref13,
  author  = {biblatex},
  title   = {how to use biblatex how to use biblatex how to use biblatex how to use biblatex how to use biblatex},
  journal = {how to use biblatex how to use biblatex how to use biblatex how to use biblatex how to use biblatex},
  number  = {1},
  year    = {2021},
  pages   = {1-100}
}
@article{ref14,
  author  = {biblatex},
  title   = {how to use biblatex how to use biblatex how to use biblatex how to use biblatex how to use biblatex},
  journal = {how to use biblatex how to use biblatex how to use biblatex how to use biblatex how to use biblatex},
  number  = {1},
  year    = {2021},
  pages   = {1-100}
}
@article{ref15,
  author  = {biblatex},
  title   = {how to use biblatex how to use biblatex how to use biblatex how to use biblatex how to use biblatex},
  journal = {how to use biblatex how to use biblatex how to use biblatex how to use biblatex how to use biblatex},
  number  = {1},
  year    = {2021},
  pages   = {1-100}
}
@article{ref16,
  author  = {biblatex},
  title   = {how to use biblatex how to use biblatex how to use biblatex how to use biblatex how to use biblatex},
  journal = {how to use biblatex how to use biblatex how to use biblatex how to use biblatex how to use biblatex},
  number  = {1},
  year    = {2021},
  pages   = {1-100}
}
@article{ref17,
  author  = {biblatex},
  title   = {how to use biblatex how to use biblatex how to use biblatex how to use biblatex how to use biblatex},
  journal = {how to use biblatex how to use biblatex how to use biblatex how to use biblatex how to use biblatex},
  number  = {1},
  year    = {2021},
  pages   = {1-100}
}
@article{ref18,
  author  = {biblatex},
  title   = {how to use biblatex how to use biblatex how to use biblatex how to use biblatex how to use biblatex},
  journal = {how to use biblatex how to use biblatex how to use biblatex how to use biblatex how to use biblatex},
  number  = {1},
  year    = {2021},
  pages   = {1-100}
}
@article{ref19,
  author  = {biblatex},
  title   = {how to use biblatex how to use biblatex how to use biblatex how to use biblatex how to use biblatex},
  journal = {how to use biblatex how to use biblatex how to use biblatex how to use biblatex how to use biblatex},
  number  = {1},
  year    = {2021},
  pages   = {1-100}
}
| |
ZhChm
|
|
***@***.***
|
签名由网易邮箱大师定制


On 10/5/2021 ***@***.***> wrote：

We don't necessarily need to see the PDF file.

You can paste the contents of your .tex file right here and if your .bib file is required you can paste it here as well. (That is usually easier to do from the GitHub web interface than via email reply.)

For example like this

\documentclass[british]{article}
\usepackage[T1]{fontenc}
\usepackage{babel}
\usepackage{csquotes}

\usepackage[backend=biber, style=authoryear]{biblatex}


\addbibresource{biblatex-examples.bib}

\begin{document}
Lorem \autocite[381]{sigfridsson}

\printbibliography\end{document}

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by moewew** [comment] 2021-10-05 05:56
Thanks for the example file. You may want to check your email program settings. I received several of your replies twice.

Anyhow, this is caused by `biblatex`'s default penalties against widows and orphans. (https://tex.stackexchange.com/q/4152/35864)

If [13] were moved up one page, its last line would end up on the following page

![image of widow in ref 13 first half](https://user-images.githubusercontent.com/6755835/135967933-e63cde70-ca84-4913-845d-03bb0b6ddd71.png)

![image of widow in ref 13, second half](https://user-images.githubusercontent.com/6755835/135967979-40300d94-a00a-47cc-a9dd-5c1f4026bc22.png)

This is usually typographically undesirable and `biblatex` tries to avoid cases like this by setting the "widow penalty" to a very high value.

https://github.com/plk/biblatex/blob/3f9f6dfc6ae363d2d39cbde0045a32c1658f7d99/tex/latex/biblatex/biblatex.def#L219-L225

If you don't mind the widow and would rather move 13 up one page, you can tell `biblatex` that you don't mind widows with

```latex
\renewcommand*{\bibsetup}{%
  \interlinepenalty=5000\relax
  \widowpenalty=0\relax
  \clubpenalty=10000\relax
  \raggedbottom
  \frenchspacing
  \biburlsetup}
```

In full

```latex
\documentclass{ctexbook}
\usepackage[showframe]{geometry}
\usepackage{fancyhdr}
\usepackage[backend=biber,
style=gb7714-2015,
citestyle=gb7714-2015,
gbnamefmt=lowercase,
gbpub=false,
gbpunctin=false,
mincitenames=3, maxcitenames=3,
autocite=superscript]{biblatex}
\defbibenvironment{bibliography}
{\list
{\printfield[labelnumberwidth]{labelnumber}}
{\setlength{\leftmargin}{0mm}
\setlength{\itemindent}{3.5em}
\setlength{\itemsep}{2pt}
    \setlength{\parsep}{2pt}
}}
{\endlist}
{\item}
\def\baselinestretch{1.25}
\geometry{
a4paper,
hmargin = 30mm, top = 20mm, bottom = 32mm,
headsep = 0mm, headheight = 10mm, footskip = 8mm,
}
\fancypagestyle{plain}{
  \fancyhf{}
  \renewcommand{\headrulewidth}{1pt}
  \renewcommand{\footrulewidth}{1pt}
  \fancyhead[C]{\zihao{5}\normalfont{biblatex}}
  \fancyfoot[C]{\zihao{5}\normalfont{page\ \thepage\ }}
}
\ctexset{
chapter = {
beforeskip = {-3.4mm}, afterskip = {5mm},
    format = {\mdseries\heiti\zihao{3}\centering}
  }
}

\renewcommand*{\bibsetup}{%
  \interlinepenalty=5000\relax
  \widowpenalty=0\relax
  \clubpenalty=10000\relax
  \raggedbottom
  \frenchspacing
  \biburlsetup}

\begin{filecontents}{\jobname.bib}
@Article{ref1,
  author  = {biblatex},
  title   = {how to use biblatex how to use biblatex how to use biblatex how to use biblatex how to use biblatex},
  journal = {how to use biblatex how to use biblatex how to use biblatex how to use biblatex how to use biblatex},
  number  = {1},
  year    = {2021},
  pages   = {1-100}
}
@Article{ref2,
  author  = {biblatex},
  title   = {how to use biblatex how to use biblatex how to use biblatex how to use biblatex how to use biblatex},
  journal = {how to use biblatex how to use biblatex how to use biblatex how to use biblatex how to use biblatex},
  number  = {1},
  year    = {2021},
  pages   = {1-100}
}
@Article{ref3,
  author  = {biblatex},
  title   = {how to use biblatex how to use biblatex how to use biblatex how to use biblatex how to use biblatex},
  journal = {how to use biblatex how to use biblatex how to use biblatex how to use biblatex how to use biblatex},
  number  = {1},
  year    = {2021},
  pages   = {1-100}
}
@Article{ref4,
  author  = {biblatex},
  title   = {how to use biblatex how to use biblatex how to use biblatex how to use biblatex how to use biblatex},
  journal = {how to use biblatex how to use biblatex how to use biblatex how to use biblatex how to use biblatex},
  number  = {1},
  year    = {2021},
  pages   = {1-100}
}
@Article{ref5,
  author  = {biblatex},
  title   = {how to use biblatex how to use biblatex how to use biblatex how to use biblatex how to use biblatex},
  journal = {how to use biblatex how to use biblatex how to use biblatex how to use biblatex how to use biblatex},
  number  = {1},
  year    = {2021},
  pages   = {1-100}
}
@Article{ref5,
  author  = {biblatex},
  title   = {how to use biblatex how to use biblatex how to use biblatex how to use biblatex how to use biblatex},
  journal = {how to use biblatex how to use biblatex how to use biblatex how to use biblatex how to use biblatex},
  number  = {1},
  year    = {2021},
  pages   = {1-100}
}
@Article{ref6,
  author  = {biblatex},
  title   = {how to use biblatex how to use biblatex how to use biblatex how to use biblatex how to use biblatex},
  journal = {how to use biblatex how to use biblatex how to use biblatex how to use biblatex how to use biblatex},
  number  = {1},
  year    = {2021},
  pages   = {1-100}
}
@Article{ref7,
  author  = {biblatex},
  title   = {how to use biblatex how to use biblatex how to use biblatex how to use biblatex how to use biblatex},
  journal = {how to use biblatex how to use biblatex how to use biblatex how to use biblatex how to use biblatex},
  number  = {1},
  year    = {2021},
  pages   = {1-100}
}
@Article{ref8,
  author  = {biblatex},
  title   = {how to use biblatex how to use biblatex how to use biblatex how to use biblatex how to use biblatex},
  journal = {how to use biblatex how to use biblatex how to use biblatex how to use biblatex how to use biblatex},
  number  = {1},
  year    = {2021},
  pages   = {1-100}
}
@Article{ref9,
  author  = {biblatex},
  title   = {how to use biblatex how to use biblatex how to use biblatex how to use biblatex how to use biblatex},
  journal = {how to use biblatex how to use biblatex how to use biblatex how to use biblatex how to use biblatex},
  number  = {1},
  year    = {2021},
  pages   = {1-100}
}
@Article{ref10,
  author  = {biblatex},
  title   = {how to use biblatex how to use biblatex how to use biblatex how to use biblatex how to use biblatex},
  journal = {how to use biblatex how to use biblatex how to use biblatex how to use biblatex how to use biblatex},
  number  = {1},
  year    = {2021},
  pages   = {1-100}
}
@Article{ref11,
  author  = {biblatex},
  title   = {how to use biblatex how to use biblatex how to use biblatex how to use biblatex how to use biblatex},
  journal = {how to use biblatex how to use biblatex how to use biblatex how to use biblatex how to use biblatex},
  number  = {1},
  year    = {2021},
  pages   = {1-100}
}
@Article{ref12,
author  = {biblatex},
title   = {how to use biblatex how to use biblatex how to use biblatex how to use biblatex how to use biblatex},
journal = {how to use biblatex how to use biblatex how to use biblatex how to use biblatex how to use biblatex},
number  = {1},
year    = {2021},
pages   = {1-100}
}


@Article{ref13,
  author  = {biblatex},
  title   = {how to use biblatex how to use biblatex how to use biblatex how to use biblatex how to use biblatex},
  journal = {how to use biblatex how to use biblatex how to use biblatex how to use biblatex how to use biblatex},
  number  = {1},
  year    = {2021},
  pages   = {1-100}
}
@Article{ref14,
  author  = {biblatex},
  title   = {how to use biblatex how to use biblatex how to use biblatex how to use biblatex how to use biblatex},
  journal = {how to use biblatex how to use biblatex how to use biblatex how to use biblatex how to use biblatex},
  number  = {1},
  year    = {2021},
  pages   = {1-100}
}
@Article{ref15,
  author  = {biblatex},
  title   = {how to use biblatex how to use biblatex how to use biblatex how to use biblatex how to use biblatex},
  journal = {how to use biblatex how to use biblatex how to use biblatex how to use biblatex how to use biblatex},
  number  = {1},
  year    = {2021},
  pages   = {1-100}
}
@Article{ref16,
  author  = {biblatex},
  title   = {how to use biblatex how to use biblatex how to use biblatex how to use biblatex how to use biblatex},
  journal = {how to use biblatex how to use biblatex how to use biblatex how to use biblatex how to use biblatex},
  number  = {1},
  year    = {2021},
  pages   = {1-100}
}
@Article{ref17,
  author  = {biblatex},
  title   = {how to use biblatex how to use biblatex how to use biblatex how to use biblatex how to use biblatex},
  journal = {how to use biblatex how to use biblatex how to use biblatex how to use biblatex how to use biblatex},
  number  = {1},
  year    = {2021},
  pages   = {1-100}
}
@Article{ref18,
  author  = {biblatex},
  title   = {how to use biblatex how to use biblatex how to use biblatex how to use biblatex how to use biblatex},
  journal = {how to use biblatex how to use biblatex how to use biblatex how to use biblatex how to use biblatex},
  number  = {1},
  year    = {2021},
  pages   = {1-100}
}
@Article{ref19,
  author  = {biblatex},
  title   = {how to use biblatex how to use biblatex how to use biblatex how to use biblatex how to use biblatex},
  journal = {how to use biblatex how to use biblatex how to use biblatex how to use biblatex how to use biblatex},
  number  = {1},
  year    = {2021},
  pages   = {1-100}
}
\end{filecontents}
\addbibresource{\jobname.bib}
\begin{document}
\chapter{绪论}


I LOVE \LaTeX\cite{ref1,ref2,ref3,ref4,ref5,ref6,ref7,ref8,ref9,ref10,ref11,ref12,ref13,ref14,ref15,ref16,ref17,ref18,ref19}。


You can see that there is a blank space after the reference[12] but the reference[13] cannot fill this space.


\printbibliography[heading = bibintoc]
\end{document}
```

**Comment by Vincent-zcm** [comment] 2021-10-05 07:19
Thanks for your answering very much!

**Comment by moewew** [comment] 2021-10-05 18:34
Alright. I think we can close this then.

**Closed by moewew** 2021-10-05 18:34 UTC
