### ISSUE TITLE
Wrong version number in documentation

### ISSUE THREAD

**Issue by LukasCBossert** [plk/biblatex#648] opened 2017-11-05 18:45 UTC
There is still `3.7` as version number in the documentation of the today’s release.

**Comment by moewew** [comment] 2017-11-05 18:47
Duplicate of https://github.com/plk/biblatex/issues/647

**Comment by moewew** [comment] 2017-11-05 18:49
This was already brought to PLK's attention. Version 3.8a has been uploaded to CTAN already, it will not have reached all mirrors yet, so some might still have 3.8 with the wrong version number.

The Biber issue is much more problematic.

**Closed** 2017-11-05 18:48 UTC
