### ISSUE TITLE
Fields type, eventtitle, venue in @unpublished

### ISSUE THREAD

**Issue by njbart** [plk/biblatex#687] opened 2018-01-21 18:00 UTC
“The script of a talk” is one of the use cases for `@unpublished` listed in the biblatex manual, and arguably this item type is well suited for presentations, speeches, or posters as well. In fact, biblatex-chicago and biblatex-apa explicitly recommend using `@unpublished` for such items.

Since there are upstream data sources that use `type`, `eventtitle`, and `venue` in `@unpublished` items (rather than `howpublished` and/or `note`), and biblatex-chicago does render `eventtitle` and `venue` already, I would like to suggest that biblatex (and biblatex-apa, for that matter) should permit and render these fields in `@unpublished` entries, too.

(I don’t expect `eventdate` to be used at all here, since there won’t be a publication date different  from the event date, so the date of the event will be entered nowhere else than in the `date` field.)

An example (from CMS 16e, 14.226) that might be useful for testing is:

```
@unpublished{teplin,
  author = {Teplin, Linda A. and McClelland, Gary M. and Abram, Karen M. and Washburn, Jason J.},
  date = {2005-03},
  title = {Early Violent Death in Delinquent Youth},
  type = {paper},
  eventtitle = {Annual Meeting of the {American Psychology-Law Society}},
  venue = {La Jolla, CA},
  langid = {american}
}
```

**Comment by moewew** [comment] 2018-01-22 10:49
Mhhh, @plk what do you think?
I'm not too keen to add more specific fields to `@unpublished`, I especially don't want to add a precedent that forces us to include all sorts of fields for `@unpublished` or other types. But this is about only two fields and the documentation pushes us towards `eventtitle` and `venue`.

**Comment by plk** [comment] 2018-01-22 10:52
I don’t mind this too much if it’s a generally applicable change.

**Comment by moewew** [comment] 2018-01-22 10:58
The question is where exactly this should go in the `unpublished` bibdriver?

**Comment by moewew** [comment] 2018-01-22 11:09
First suggestion is at https://github.com/plk/biblatex/compare/dev...moewew:eventunpub

**Comment by njbart** [comment] 2018-01-22 11:48
I think, `type` is essential, too (typical values include “paper”, “poster”, “keynote speech” etc.). The “First suggestion” does not seem to include it. Otherwise, I’d say the order howpublished – type – eventtitle – venue – note is fine.

**Comment by moewew** [comment] 2018-01-22 11:54
I guess initially this was intended to be in `howpublished`, but since we are already at it, I have added `type` as well.

Please have a look at #688.

**Comment by njbart** [comment] 2018-01-22 16:39
Well, from this:

```
@unpublished{teplin:2005early,
  author = {Teplin, Linda A. and McClelland, Gary M. and Abram, Karen M. and Washburn, Jason J.},
  date = {2005-03-31},
  eventdate = {2004-02-30},
  title = {Early Violent Death in Delinquent Youth},
  venue = {La Jolla, CA},
  type = {paper},
  eventtitle = {Annual {Meeting} of the {American Psychology-Law Society}},
  howpublished = {howpublished},
  note = {note},
  langid = {american},
}
```

I now get this (using `\usepackage[style=authoryear]{biblatex}`):

![screen shot 2018-01-22 at 17 16 04](https://user-images.githubusercontent.com/2765811/35231032-a10fb3dc-ff8f-11e7-9d8d-2b9157ffed52.png)

Not too bad, though `howpublished`, `type`, and `note` could be autocapitalized, and, personally, I’d use a few more commas and fewer full stops between the new elements, and maybe not even round brackets around the venue.

Other than that, I still fail to come up with a convincing use case for `eventdate` here – unless there is one I’m not aware of, I’d say its inclusion rather confuses things and should be better left out.

Finally, some users might want a format like “Paper presented at the Annual Meeting …”. This can be achieved by entering `type = {Paper presented at the\nopunct},` in the database, and could certainly be automated using the `\DeclareSourcemap` functionality. I’m not sure whether it’d be worth the effort to implement this in biblatex itself …

**Comment by moewew** [comment] 2018-01-22 19:13
Mhh, there is no precedence for `\autocap` in standard field formats. In general it seems `note` is never automatically capitalised. The same goes for `type`, which uses bibstrings, so I would suggest you use a bibstring for `paper`.

Since we already added `eventtitle` and `venue` we might as well add `eventdate`. Consider a multi-day conference which you could put in `eventdate`, `date` would then hold the exact date of presentation. I don't think this adds more confusion.

Since `@unpublished` is not exclusively used for talks I hesitate to include something specifically tailored to that end.

**Comment by njbart** [comment] 2018-01-23 07:08
A multi-day conference is indeed something where `eventdate` might be useful.

As to the other points – fair enough. That’s nothing I couldn’t handle on my side if needed. I’ll just note that in other styles many fields might appear mid-sentence, so in general I’m trying not to capitalize words or phrases such as “paper”.

Should I open a separate ticket for biblatex-apa?

**Comment by moewew** [comment] 2018-01-25 06:54
Closing this for now. If anything comes up, feel free to comment and reopen.

@njbart If you want to request changes in `biblatex-apa`, I suggest you open an issue at that bugtracker (https://github.com/plk/biblatex-apa/issues) as well, so this doesn't get lost and we lose track.

**Closed by moewew** 2018-01-25 06:54 UTC
Labels: enhancement
