### ISSUE TITLE
reading style ignores institution, produces odd output for report

### ISSUE THREAD

**Issue by jrmoserbaltimore** [plk/biblatex#1047] opened 2020-09-06 15:09 UTC
For the `report` entry type, the `reading` style will produce a citation like:

> Niklas Engborn and Christian Moser. "Earnings Inequality and the Minimum Wage: Evidence from Brazil". In: (2018) DOI: 10.21034/iwp.7

A report is typically a stand-alone work, and I would expect the `institution` field instead:

> Niklas Engborn and Christian Moser. "Earnings Inequality and the Minimum Wage: Evidence from Brazil". Federal Reserve Bank of Minneapolis (2018) DOI: 10.21034/iwp.7

For example, chicago author-year produces:

> Engborn, Niklas, and Christian Moser. 2018. “Earnings Inequality and the Minimum Wage: Evidence from Brazil.” Federal Reserve Bank of Minneapolis. https://doi.org/10.21034/iwp.7.

Given biblatex entry:

```
@Report{Engborn2018,
  author      = {Engborn, Niklas and Moser, Christian},
  date        = {2018},
  institution = {Federal Reserve Bank of Minneapolis},
  title       = {Earnings Inequality and the Minimum Wage: Evidence from Brazil},
  type        = {resreport},
  doi         = {10.21034/iwp.7},
}
```

**Comment by moewew** [comment] 2020-09-06 15:13
Hrmm, that doesn't look right. Can you please add a fully compilable example document that shows how you cite this entry and your bibliography setup?

From
```latex
\documentclass[british]{article}
\usepackage[T1]{fontenc}
\usepackage[utf8]{inputenc}
\usepackage{babel}
\usepackage{csquotes}

\usepackage[style=reading, backend=biber]{biblatex}


\begin{filecontents}{\jobname.bib}
@Report{Engborn2018,
  author      = {Engborn, Niklas and Moser, Christian},
  date        = {2018},
  institution = {Federal Reserve Bank of Minneapolis},
  title       = {Earnings Inequality and the Minimum Wage: Evidence from Brazil},
  type        = {resreport},
  doi         = {10.21034/iwp.7},
}
\end{filecontents}
\addbibresource{\jobname.bib}
\addbibresource{biblatex-examples.bib}


\begin{document}
\cite{sigfridsson,Engborn2018}
\printbibliography
\end{document}
```
I get
> Niklas Engborn and Christian Moser. Earnings Inequality and the Minimum Wage: Evidence from Brazil. Research rep. Federal Reserve Bank of Minneapolis, 2018. doi: 10.21034/iwp.7.

![Image of the output](https://user-images.githubusercontent.com/6755835/92328894-3b451380-f064-11ea-83e4-d3cb47a46275.png)

which looks alright.

**Comment by moewew** [comment] 2020-09-15 15:40
@jrmoserbaltimore Any news here? As mentioned above I failed to reproduce the behaviour you describe. It would be very much appreciated if you could share a fully compilable example document (in the style I showed above) that exhibits the problematic behaviour. If I can't reproduce the behaviour, I'm afraid I will have to close this issue because there is no sensible way to investigate what might be wrong here.

**Comment by moewew** [comment] 2020-10-07 06:24
Closing this since the issue cannot be reproduced with the information given so far. The `@report` entry in my MWE looked fine.

We can reopen once an MWE that reproduces the undesirable behaviour is provided or if we find some other way to reproduce this odd behaviour. If you have anything to add, just comment below.

**Closed by moewew** 2020-10-07 06:24 UTC
Labels: needs-feedback
