### ISSUE TITLE
Undefined control sequence \blx@tempb

### ISSUE THREAD

**Issue by ti-s** [plk/biblatex#697] opened 2018-01-26 21:45 UTC
Above error is shown when compiling the following file using Texlive 2017 with biblatex 3.10 and biber 2.10:

```
\documentclass{article}

\usepackage{filecontents}

\begin{filecontents}{bib.bib}
@article {a,
    title = {A title},
    auhtor = {A. Author},
    year = {2000},
}
@article {b,
    title = {B title},
    auhtor = {B. Author},
    year = {2000},
} 
@article {c,
    title = {C title},
    auhtor = {C. Author},
    year = {2000},
} 
@article {d,
    title = {D title},
    auhtor = {D. Author},
    year = {2000},
} 
\end{filecontents}

\usepackage[
backend=biber, 
style=numeric-comp
]{biblatex}

\addglobalbib{bib.bib}

\begin{document}
\newrefsection
\cite{a, b}
\newrefcontext[labelprefix=A.]
\printbibliography

\newrefsection
\cite{c, d}
\newrefcontext[labelprefix=B.]
\printbibliography
\end{document}
```
No error is shown when using an old Texlive 2017 installation with biblatex 3.7.

Also, there is no error with any of the following changes:
* only using one refsection
* using `labelprefex` only in one refcontext
* using `\cite{c}\cite{d}` instead of `\cite{c, d}`
* moving the `\newrefcontext` commands above the corresponding cite commands

**Comment by plk** [comment] 2018-01-27 20:43
Thank you for this report. New reference sections were not closing open reference contexts, which was the cause of this. This is fixed in biblatex 3.11 DEV version on Sourceforge. By the way your example needs `defernumbers=true` and there are warnings to this effect.

**Comment by ti-s** [comment] 2018-01-29 11:16
Thank you for the quick fix! The new version works for my real document, too.

**Comment by moewew** [comment] 2018-03-07 08:06
Fixed in `biblatex` 3.11. We didn't make it in time for the TeX live freeze, so TeX live 2017 will not get the update. TeX live 2018 (pretest) and MikTeX got the new versions of the course of the last few days.

**Comment by moewew** [comment] 2018-07-10 15:21
As reported in there is a similar issue with the `refesction` environment

```latex
\documentclass{article}
\usepackage[utf8]{inputenc}
\usepackage[T1]{fontenc}
\usepackage[backend=biber, style=numeric-comp, sorting=none, defernumbers=true]{biblatex}

\addbibresource{biblatex-examples.bib}
\usepackage[autostyle=true]{csquotes}

\begin{document}
\begin{refsection}
single citation \cite{sigfridsson}, \cite{nussbaum}.
multiple citations \cite{sigfridsson,nussbaum, worman}. 
\newrefcontext[labelprefix=A]
\printbibliography
\end{refsection}

\begin{refsection}
single citation \cite{sigfridsson}, \cite{nussbaum}.
multiple citations \cite{sigfridsson,nussbaum, worman}. 

\newrefcontext[labelprefix=B]
\printbibliography
\end{refsection}
\end{document}
```

**Comment by moewew** [comment] 2018-07-10 15:29
The fix for this seems to be similar to https://github.com/plk/biblatex/commit/02231e6d3250167f08c2319d6a3618b1fa01bfbc

The question is where exactly the `\endrefcontext` ought to go in

https://github.com/plk/biblatex/blob/208871d43388599781e5be9df2a02771792a354f/tex/latex/biblatex/biblatex.sty#L8961-L8974

before or after the `\begingroup`? Also adding `\endrefcontext` to `\refsection` probably makes it superfluous in `\newrefsection` because that calls `\refsection`

https://github.com/plk/biblatex/blob/208871d43388599781e5be9df2a02771792a354f/tex/latex/biblatex/biblatex.sty#L8953-L8958

but maybe the nesting wouldn't be quite right then...

**Comment by plk** [comment] 2018-09-25 17:57
Is this still an issue? I get no errors with the latest DEV versions.

**Comment by moewew** [comment] 2018-09-26 06:07
Interesting, I had not checked the MWE with 3.12 `dev` and indeed, there is no error. But there is still something wrong going on in the MWE. Have a look at the `\cite{sigfridsson,nussbaum, worman}` in the second `refsection`. I only get an empty pair of square brackets instead of a citation.

```
\documentclass{article}
\usepackage[utf8]{inputenc}
\usepackage[T1]{fontenc}
\usepackage[backend=biber, style=numeric-comp, sorting=none, defernumbers=true]{biblatex}

\addbibresource{biblatex-examples.bib}
\usepackage[autostyle=true]{csquotes}

\begin{document}
\begin{refsection}
single citation \cite{sigfridsson}, \cite{nussbaum}.
multiple citations \cite{sigfridsson,nussbaum, worman}. 
\newrefcontext[labelprefix=A]
\printbibliography
\end{refsection}

\begin{refsection}
single citation \cite{sigfridsson}, \cite{nussbaum}.
multiple citations \cite{sigfridsson,nussbaum, worman}. 

\newrefcontext[labelprefix=B]
\printbibliography
\end{refsection}
\end{document}
```

It turns out that adding `\endrefcontext` to `\endrefsection` solves the incorrect output for me in that case. I'm just not sure where exactly it should go and whether it should be in `\endrefsection` or `\blx@endrefsection`.

**Closed** 2018-11-06 08:07 UTC
Labels: bug
