### ISSUE TITLE
Spacing in \fullcite with autolang=langname

### ISSUE THREAD

**Issue by dustalov** [plk/biblatex#951] opened 2020-01-03 19:44 UTC
I am using `langid` for distinguishing between languages in multilingual bibliographies with `autolang=langname`.

After the TeX Live 2019 update to BibLaTeX 3.14 and Polyglossia 1.46, the `\fulltext` command started producing unexpected spacing in the beginning when the `langid` value is equal to the main language set to Polyglossia. When `langid` is not set, the output is correct. The `\printbibliography` output still remains correct in all cases.

I am wondering if I missed the recommended workaround. Before the update everything worked well, i.e., `entry1`, `entry2`, and `entry3` had zero additional horizontal spacing unlike `entry2` in the present example.

![Spacing in \fullcite with autolang=langname MWE](https://user-images.githubusercontent.com/40397/71745080-f7718d00-2e8a-11ea-84b2-91137e609224.png)

```latex
\begin{filecontents*}{\jobname.bib}
@misc{entry1,
  author  = {Doe, John},
  title   = {The quick brown fox jumps over the lazy dog},
  note    = {The five boxing wizards jump quickly},
  year    = {2020},
}

@misc{entry2,
  author  = {Doe, John},
  title   = {The quick brown fox jumps over the lazy dog},
  note    = {The five boxing wizards jump quickly},
  year    = {2020},
  langid  = {english},
}

@misc{entry3,
  author  = {Иванов, Иван},
  title   = {В чащах юга жил бы цитрус? Да, но фальшивый экземпляр!},
  note    = {Съешь же ещё этих мягких французских булок да выпей чаю},
  year    = {2020},
  langid  = {russian},
}
\end{filecontents*}

\documentclass{article}

\usepackage{fontspec}
\setmainfont{ztm}

\usepackage{polyglossia}
\setmainlanguage{english}
\setotherlanguage{russian}

\usepackage[backend=biber,autolang=langname]{biblatex}
\addbibresource{\jobname.bib}

\begin{document}

\fullcite{entry1}

\fullcite{entry2}

\fullcite{entry3}

\printbibliography

\end{document}
```

**Comment by moewew** [comment] 2020-01-03 19:52
I think this is due to https://github.com/reutenauer/polyglossia/issues/369 and https://github.com/reutenauer/polyglossia/issues/356 in `polyglossia`. I ran the MWE with `polyglossia` 1.46 and could reproduce the issue. With a newer development version I got from GitHub a while back the issue does not reappear.

**Comment by dustalov** [comment] 2020-01-03 20:29
Thanks! I think the safest option is to wait until Polyglossia submits the new version to CTAN.

**Comment by dustalov** [comment] 2020-01-04 16:26
Regarding the comment update: yes, exactly, the text is rendered as `A B C`.

**Comment by moewew** [comment] 2020-01-31 06:37
`polyglossia` v1.47 with a fix for the spurious spaces has been released and has landed in TeX live and MikTeX. With that version the MWEs posted here no longer produce unwanted space.

**Closed by moewew** 2020-01-31 06:37 UTC
Labels: external
