### ISSUE TITLE
Empty parentheses with missing year

### ISSUE THREAD

**Issue by jspitz** [plk/biblatex#793] opened 2018-08-31 08:09 UTC
In the MWE below, I'd expect that the parentheses holding issue and year will not be printed if both year and issue are undefined. Instead, empty parentheses are output, as in:

> Doe, Jane and John Due (n.d.). “Example title”. In: _Topnotch Studies_ 4.1 (), pp. 1–13.

I think this is a regression to earlier version, but I cannot put my finger on the version where it changed.

```
\documentclass{article}
\usepackage[english]{babel}
\usepackage{filecontents}
\usepackage[bibstyle=authoryear]{biblatex}

\addbibresource{\jobname.bib}
 
\begin{filecontents}{\jobname.bib}
    @article{Doe.2016,
 		author = {Doe, Jane and Due, John},
 		title = {Example title},
 		pages = {1--13},
 		volume = {4},
 		number = {1},
 		journal = {Topnotch Studies}
    }
\end{filecontents}
 
\begin{document}
\nocite{Doe.2016}
\printbibliography
\end{document}
```

**Comment by moewew** [comment] 2018-08-31 08:29
I suspect the `\iflabeldateisdate` doesn't correctly pick up the case where `labeldate` is `nodate`.

However, the MWE has always yielded bad results with non-`authoryear` styles anyway, so I would argue that in this case the input is wrong (`year` or `date` is a required field for `@article` and a published journal article should have a date associated with it. Sure, we are probably talking about accepted publications with no fixed date yet ...).

> Doe, Jane and John Due. “Example title”. In: Topnotch Studies 4.1 (), pp. 1–13.

**Comment by jspitz** [comment] 2018-08-31 08:44
But see the linked ticket for `biblatex-publist`. In this package, we output the year earlier and then clear it via `\clearfield`, so that the year is not output twice (note that `biblatex-publist` tries to be as bbx-agnostic as it possibly can). This does not work (any longer) with `labeldateparts=false` (it still works with `labeldateparts=true`). Investigating that revealed that there is something fishy in general. The testcase is just the simplest one I could come up with. I agree that it is a rather heuristic one.

**Comment by jspitz** [comment] 2018-08-31 12:30
And again, I am pretty sure this is a regression in newer versions of biblatex.

**Comment by moewew** [comment] 2018-08-31 12:43
I should have been clearer, sorry.

Yes, the specific behaviour you observed and showed in the MWE with `style=authoryear` is indeed new. This did not use to happen in older versions. And I have to agree that the output is not particularly fortuitous. But even then the output is in line with the behaviour of other styles in a similar situation (as mentioned and shown above you also get an empty pair of parentheses with `style=authorttitle`).

However, this issue is tied to the broader question of whether or not `issue+date` should give an empty pair of parentheses in the other non-`authoryear` styles if the year is missing (it currently does and it has *always* done that). So I have maybe unreasonably broadened the scope of this entire issue to include that question as well. And it is mainly this simple warning sign that I'm reluctant to get rid of.

I would not be too fussed if this was only about `\clearfield{year}` causing problems: If you delete required fields willy nilly, you must expect that the output might be a bit off, so you have to take precautions against that.

**Comment by jspitz** [comment] 2018-08-31 13:34
> If you delete required fields willy nilly, you must expect that the output might be a bit off, so you have to take precautions against that.

If you can give me a hint how to do that, I will.

**Comment by moewew** [comment] 2018-08-31 13:39
```latex
\renewbibmacro*{issue+date}{%
  \ifboolexpr{test {\iffieldundef{year}}
              and test {\iffieldundef{issue}}}
    {}
    {\printtext[parens]{%
       \printfield{issue}%
       \setunit*{\addspace}%
       \usebibmacro{date}}}%
  \newunit}
```
Only prints the parentheses if there is something to print in between (either `issue` or a date as indicated by presence of the `year` field). That works for all styles except `authoryear`, for `authoryear` and its derivatives you have to change each `mergedate` setting separately (but the idea is of course the same).

I'm just working on a patch for `biblatex` that does the right thing for all all `mergedate` settings.

**Comment by jspitz** [comment] 2018-08-31 13:48
Hm, I always thought that `\printtext` only prints if there is content and that such extra checks shouldn't be needed. Also, I am baffled why this check is not needed with `labeldateparts=true`

**Comment by moewew** [comment] 2018-08-31 13:53
`\printtext` does not check its contents (I guess that would be too complicated, because there could be arbitrary text and macros in its arguments, so there is no level of expansion that could be checked and an `\edef` is too risky). `\printfield`, `\printlist` and `\printname` check if they print something because that can easily be verified.

The `labeldateparts` malarkey only comes into play with `style=authoryear`, where `issue+date` would have to have different definitions depending on the `mergedate` settings (which I didn't show because I have to work out the details).

**Comment by moewew** [comment] 2018-08-31 16:10
Have a look at https://github.com/plk/biblatex/compare/dev...moewew:issuedateparens

I'm still not entirely sure if we should merge this...

**Comment by jspitz** [comment] 2018-09-01 07:27
This looks very reasonable to me.

**Comment by plk** [comment] 2018-09-25 19:08
Hmm, well, `\clearfield{}` is interesting as it's a `biblatex` macro that pre-dates the `biber` data modification system. It was used to remove data fields and so to my mind would not be expected to remove formatting for removed fields. However, since there is a data input system in biber to clear fields at source, the `\clear*{}` macros feel more formatting oriented so it's more ambivalent now. However, if you want to omit required fields, I think it's up to the user to patch macros to avoid formatting errors as @moewew shows above.

**Comment by moewew** [comment] 2018-09-26 07:33
Good point about `\clearfield` feeling more like a formatting instead of a data command now (actually that is a very important point if you clear date fields), but the difference between `\clearfield` and Biber sourcemap `null` is not actually that important in this specific case. `\clearfield` normally gets rid of the entire field including the formatting just as Biber would.

The issue here is caused by the fact that the formatting around year and issue is not in a field format (it's in a `\printtext`) and thus does not respond easily to empty fields. Now this could be guarded against fairly easily (though not very pretty), but I have two reservations

1. It is not in the code already. If PL would have thought that this makes sense, I'm really quite sure he would have included it from the start.
2. The empty pair of brackets serves as a convenient signpost that something is wrong. `date` is a required field and so there should be a year to output. 

That all said, let me reiterate that I have broadened the scope of the initial request here:

- There is indeed a difference in behaviour between earlier versions and 3.11 with respect to empty parentheses in `authoryear`-like fields with certain `mergedate` settings. Some older versions would not output empty brackets, 3.11 will.
- I took this further and also looked at other styles like `authortitle` that always will output an empty pair of brackets. I figured that if we are going to change the behaviour then it should change for all styles and all `mergedate` settings alike.

**Comment by jspitz** [comment] 2018-09-26 14:44
Note though comment 1: This behavior is a regression to earlier versions of biblatex, and thus a bug. I just noticed by chance that some of my bibliographies suddenly have these empty parentheses. I would expect that the original behavior is restored.

**Comment by moewew** [comment] 2018-10-08 08:47
https://github.com/plk/biblatex/compare/dev...moewew:issuedateparensreb contains the same suggestion rebased onto #810. I still don't really want to merge this, but I'm slowly coming round to the realisation that we might have to...

**Closed** 2020-05-16 14:55 UTC
Labels: wontfix
