### ISSUE TITLE
hyperref leads to a "! Missing number, treated as zero." error

### ISSUE THREAD

**Issue by dbitouze** [plk/biblatex#622] opened 2017-09-06 11:57 UTC
With a fresh `git pull` of the present repository, trying to run https://github.com/plk/biblatex/blob/dev/doc/latex/biblatex/examples/03-localization-keys.tex as suggested by @moewew in https://github.com/plk/biblatex/issues/615, leads to the following error:

```
! Missing number, treated as zero.
<to be read again> 
                   D
l.5 \usepackage
               {hyperref}
?
```
when `hyperref` is loaded, even with the following MCE:
```latex
\documentclass{article}
\usepackage[backend=biber]{biblatex}
\usepackage{hyperref}
\begin{document}

\end{document}
```

Here is my file list:

```
 *File List*
 article.cls    2014/09/29 v1.4h Standard LaTeX document class
  size10.clo    2014/09/29 v1.4h Standard LaTeX file (size option)
biblatex.sty    DATE vVERSION programmable bibliographies (PK/JW/AB)
pdftexcmds.sty    2017/03/19 v0.25 Utility functions of pdfTeX for LuaTeX (HO)
infwarerr.sty    2016/05/16 v1.4 Providing info/warning/error messages (HO)
ifluatex.sty    2016/05/16 v1.4 Provides the ifluatex switch (HO)
 ltxcmds.sty    2016/05/16 v1.23 LaTeX kernel commands for general use (HO)
   ifpdf.sty    2017/03/15 v3.2 Provides the ifpdf switch
etoolbox.sty    2017/01/02 v2.4 e-TeX tools for LaTeX (JAW)
  keyval.sty    2014/10/28 v1.15 key=value parser (DPC)
kvoptions.sty    2016/05/16 v3.12 Key value format for package options (HO)
kvsetkeys.sty    2016/05/16 v1.17 Key value parser (HO)
etexcmds.sty    2016/05/16 v1.6 Avoid name clashes with e-TeX commands (HO)
  logreq.sty    2010/08/04 v1.0 xml request logger
  logreq.def    2010/08/04 v1.0 logreq spec v1.0
  ifthen.sty    2014/09/29 v1.1c Standard LaTeX ifthen package (DPC)
     url.sty    2013/09/16  ver 3.4  Verb mode for urls, etc.
 xstring.sty    2013/10/13  v1.7c  String manipulations (C Tellechea)
  blx-dm.def
biblatex-dm.cfg
blx-compat.def    DATE vVERSION biblatex compatibility (PK/JW/AB)
biblatex.def    DATE vVERSION biblatex compatibility (PK/JW/AB)
standard.bbx    DATE vVERSION biblatex bibliography style (PK/JW/AB)
 numeric.bbx    DATE vVERSION biblatex bibliography style (PK/JW/AB)
 numeric.cbx    DATE vVERSION biblatex citation style (PK/JW/AB)
biblatex.cfg    
hyperref.sty    2017/03/14 v6.85a Hypertext links for LaTeX
hobsub-hyperref.sty    2016/05/16 v1.14 Bundle oberdiek, subset hyperref (HO)
hobsub-generic.sty    2016/05/16 v1.14 Bundle oberdiek, subset generic (HO)
  hobsub.sty    2016/05/16 v1.14 Construct package bundles (HO)
  ifvtex.sty    2016/05/16 v1.6 Detect VTeX and its facilities (HO)
 intcalc.sty    2016/05/16 v1.2 Expandable calculations with integers (HO)
kvdefinekeys.sty    2016/05/16 v1.4 Define keys (HO)
pdfescape.sty    2016/05/16 v1.14 Implements pdfTeX's escape features (HO)
bigintcalc.sty    2016/05/16 v1.4 Expandable calculations on big integers (HO)
  bitset.sty    2016/05/16 v1.2 Handle bit-vector datatype (HO)
uniquecounter.sty    2016/05/16 v1.3 Provide unlimited unique counter (HO)
letltxmacro.sty    2016/05/16 v1.5 Let assignment for LaTeX macros (HO)
 hopatch.sty    2016/05/16 v1.3 Wrapper for package hooks (HO)
xcolor-patch.sty    2016/05/16 xcolor patch
atveryend.sty    2016/05/16 v1.9 Hooks at the very end of document (HO)
atbegshi.sty    2016/06/09 v1.18 At begin shipout hook (HO)
refcount.sty    2016/05/16 v3.5 Data extraction from label references (HO)
 hycolor.sty    2016/05/16 v1.8 Color options for hyperref/bookmark (HO)
 ifxetex.sty    2010/09/12 v0.6 Provides ifxetex conditional
 auxhook.sty    2016/05/16 v1.4 Hooks for auxiliary files (HO)
  pd1enc.def    2017/03/14 v6.85a Hyperref: PDFDocEncoding definition (HO)
hyperref.cfg    2002/06/06 v1.2 hyperref configuration of TeXLive
 hpdftex.def    2017/03/14 v6.85a Hyperref driver for pdfTeX
rerunfilecheck.sty    2016/05/16 v1.8 Rerun checks for auxiliary files (HO)
 english.lbx    DATE vVERSION biblatex localization (PK/JW/AB)
 nameref.sty    2016/05/21 v2.44 Cross-referencing by name of section
gettitlestring.sty    2016/05/16 v1.5 Cleanup title references (HO)
    test.out
    test.out
 ***********

```

**Comment by moewew** [comment] 2017-09-06 12:03
The dev version of `biblatex.sty` on GitHub has placeholders for `\abx@date` and `\abx@version`. You'd need to fill in a valid date and a version number there, that can also be done with the build script. See https://github.com/plk/biblatex/blob/dev/README.md#installation#
You will need Biber 2.8 (dev) to use `biblatex` 3.8.

Since you need the new version of Biber anyway, it is probably easier to get both Biber and `biblatex` from Sourceforge https://sourceforge.net/projects/biblatex-biber/files/biblatex-biber/development/, https://sourceforge.net/projects/biblatex/files/development/

**Comment by moewew** [comment] 2017-09-12 16:42
Could you get things up and running? Or is the problem still present even if `\abx@date` and `\abx@version` are filled in correctly?

**Comment by moewew** [comment] 2017-09-12 16:42
@dbitouze Could you get things up and running? Or is the problem still present even if `\abx@date` and `\abx@version` are filled in correctly?

**Comment by hansfn** [comment] 2017-09-14 09:49
I can confirm that if the date and version is correctly filled, it works. (I did try that before I decided to just run the build script and install the dev version.)

Anyway, motivated by this issue (and my own struggles), I have created a pull request - see #625 - that maybe can close this issue?

**Comment by moewew** [comment] 2017-10-19 15:59
I'll close this for now, because this should be caused by the 'missing' date and version values on `dev`.

If this is not the case, please comment here and we reopen this with more detailed info.

**Closed by moewew** 2017-10-19 15:59 UTC
