### ISSUE TITLE
Turkish lbx file

### ISSUE THREAD

**Issue by bariserkus** [plk/biblatex#867] opened 2019-01-30 16:28 UTC
I would like to start a GitHub repo for coding the Turkish lbx file. I have read the wiki on preparing a new lbx file, so I roughly know about the things to watch out.

I want to ask the suggested way of using GitHub as I am new to GitHub.

Should I:
* Fork the complete biblatex repo to my GitHub account, work only on the turkish.lbx file and push whenever the turkish.lbx file made some progress. 
* First open an unofficial public repository with content only the turkish.lbx file and when it is ready to submit, I fork biblatex repo, replace the turkish.lbx file and push it.
* First open an unofficial public repository with content only the turkish.lbx file and when it is ready to submit, I send it to developers by mail, so that they can add it to the official repository.
* Follow other suggested method(s)

**Comment by moewew** [comment] 2019-01-30 16:33
Thank you very much for considering contributing to `biblatex`.

Method 1 or 2 would make things easy for us, so if you are happy to use GitHub that would be preferred. To make your life easier make sure to work on a new branch (and not one of the branches `dev` or `master`) ideally based on the current `dev`.

Sometimes it is necessary to add additional code to files other than the normal `.lbx`, so I would go for method 1 and fork the entire repository.

**Comment by bariserkus** [comment] 2019-01-31 19:39
Ok. I have reviewed the Latvian and Hungarian language posts.

This is the procedure I will follow:

* I will fork the entire plk/biblatex repo
* Create a new branch `turkish` on my repo.
* Copy either `english.lbx` or `german.lbx` to create a template for `turkish.lbx` (tbd after discussion here.)
* I will first start with the simple part: direct translations in the `\DeclareBibliographyStrings`
* At the mean time, I will get familiar with the other parts, advertise the topic and try to get attention from other Turkish-LaTeX users.

I would like to confirm the following about the merging and testing: I am guessing that other contributors have to fork my repo, work on the Turkish branch of my repo, and I have to do the merging/testing on the Turkish branch. At some point I will request for a pull to merge the Turkish branch into the dev of plk/biblatex, am I right? 

(I did not see the Latvian and Hungarian branches on plk/biblatex, which is the usual way I guess since keeping these branches away from the upstream repo is a suggested way of housekeeping. )

Sorry if my questions are silly.

**Comment by moewew** [comment] 2019-02-01 08:46
Sounds good to me. Of course if there is anything we can help with (date formats, other extras etc.), you can just comment here and we can try to work things out. It has become apparent to me in the last few translation projects, though, that `biblatex` localisations have their limits and that some things just can't be done elegantly and some not at all, so be prepared to have to work around a few limitations, settle with second-best solutions and explain some bits and pieces of Turkish grammar to us.

Indeed there were no Latvian and Hungarian branches on this repository since those files were developed elsewhere (Hungarian at https://github.com/marczellm/biblatex/tree/hungarian for example).

**Comment by bariserkus** [comment] 2019-02-06 19:26
I have done a little bit more research. Seems like I will be following the forking-based Gitflow approach. This is roughly summarized [here](http://www.dalescott.net/using-gitflow-with-githubs-fork-pull-model/). I will be opening a branch `feature/turkish-lbx` and as progress made, I will be request pulls from my repo's `origin/feature/turkish-lbx` to biblatex's `plk/upstream/dev` branch. Other contributors -if any- will be forking from my repo, and pushing into my repo's `feature/turkish-lbx` branch with pull requests. Testing will be done mostly on my side. (sorry my progress takes time; using my spare time...)

**Comment by moewew** [comment] 2019-02-06 20:32
Sounds about right to me. You can really use whatever workflow is convenient for you, as long as we can get the `.lbx` committed into `dev` with a fairly clean history (ideally just in one commit - maybe squashed - that adds `turkish.lbx`).

**Comment by bariserkus** [comment] 2019-02-06 20:34
I have forked this repo, setup the branch `feature/turkish-lbx`, setup the `turkish.lbx` file from `english.lbx`, did some preliminary changes (e.g.  `and` --> `ve`),  setup a test folder specific for Turkish lbx file with some very simple latex, bib and LyX fies for initial testing, and it works! So ready to go.

For now I converted the file to UTF-8 encoding, which I will convert back to the original encoding with ASCII characters later.

Anybody wants to contribute to Turkish lbx file can fork from my repo and work on the `feature/turkish-lbx` branch: [See Here.](https://github.com/bariserkus/biblatex)

**Comment by bariserkus** [comment] 2019-02-06 20:36
> Sounds about right to me. You can really use whatever workflow is convenient for you, as long as we can get the `.lbx` committed into `dev` with a fairly clean history (ideally just in one commit - maybe squashed - that adds `turkish.lbx`).

Ok! Probably I will remember this before the pull request.

**Comment by moewew** [comment] 2019-02-06 20:42
Great! Be sure to let us know if there is anything we can help with. (Date formats etc.) I don't think it is mentioned in the Wiki, but you can test your localisation file against https://github.com/plk/biblatex/blob/dev/doc/latex/biblatex/examples/03-localization-keys.tex to see if things are working as expected.

**Comment by bariserkus** [comment] 2019-02-06 20:48
> Great! Be sure to let us know if there is anything we can help with. (Date formats etc.) I don't think it is mentioned in the Wiki, but you can test your localisation file against https://github.com/plk/biblatex/blob/dev/doc/latex/biblatex/examples/03-localization-keys.tex to see if things are working as expected.

This is mentioned in the issue posts many times. Difficult to miss. :) Maybe I can contribute to the Wiki?

I thought that it would be much more convenient to start with a simpler tex file and I would be better if I switch to the `03-localization-keys.tex` file after some progress.

**Comment by moewew** [comment] 2019-02-06 20:57
Sure, go ahead. The wiki can be edited by anyone.

As for you test files, I can only repeat myself: Do whatever works for you. It would just be good if `turkish.lbx` would give the right output with `03-localization-keys.tex` at the end when you submit the file.

There is really not a lot of formality you have to keep up with here when it comes to your workflow. We have some formal standards when it comes to the final product (we prefer ASCII-only over UTF-8 for the moment, there should be no errors or warnings introduced by the file, ...) and have a few preferences as to how things are merged (to `dev`, ideally one compact commit - but these are things we can sort out at our end as well, if things go wrong), but that's it. Just get started and see where it takes you.

**Comment by bariserkus** [comment] 2019-02-06 21:00
> Sure, go ahead. The wiki can be edited by anyone.
> 
> As for you test files, I can only repeat myself: Do whatever works for you. It would just be good if `turkish.lbx` would give the right output with `03-localization-keys.tex` at the end when you submit the file.
> 
> There is really not a lot of formality you have to keep up with here when it comes to your workflow. We have some formal standards when it comes to the final product (we prefer ASCII-only over UTF-8 for the moment, there should be no errors or warnings introduced by the file, ...) and have a few preferences as to how things are merged (to `dev`, ideally one compact commit - but these are things we can sort out at our end as well, if things go wrong), but that's it. Just get started and see where it takes you.

👍

**Comment by abdulkerimgok** [comment] 2019-12-30 09:58
We have finished the translations to turkish, but there are a couple of problems I am hoping you'll be able to fix. 

When tested the lbx file against the localization key;

first, there a small number of strings that are undefined even though they are already defined in the localization key. So when I comment out those, I can compile the pdf with no problem. 

second, I did try to modify the extras, but wasn't able to compile the bibliography probably because of the date extras. 

----
So here are the answers to your questions from the wiki page. 

- What kind of dash do you use in number ranges like "35-50"?
\textendash with spaces

- What kind of dash do you use in date ranges like "1st January-3rd February 2009"?
\textendash with spaces

- In lists and enumerations, do you add a comma in addition to connectors like "and"? Examples:
No comma in addition to connectors as in UK English: "apples, oranges and cherries"

- How do you format short ordinals? Are ordinals gender/number sensitive? Examples:
Ordinals are not gender/number sensitive, the same with German: 1. 2. 3. 4. 5. 

- What's the gender of the word "edition"? No gender for the word "edition".
- What's the gender of the word "series" (of a journal)? No gender for the word "series".
Turkish is a gender insensitive language. 

- What's the long date format? 
[day as number] [month name] [year] = 31 January 2009

- What's the short date format? Examples:
day/month/year
day.month.year
Both are acceptable such as 31/01/2009 or 31.01.2009

After which punctuation marks do you capitalize a word? Examples:
after ". ! ?" (as in English = package default)

----
Another problem might arise after we compile the bibliography. 

The order of subject/verb/object is kind of reversed in turkish. 

So do you think that a passive string like 

edited by some person [in english] = some author by edited [in turkish]

would be a problem? if so, is there an easy work around. 

----
We will appreciate if you could us on these.

**Comment by moewew** [comment] 2019-12-30 21:39
Thank you very much for the work on `turkish.lbx`!

> first, there a small number of strings that are undefined even though they are already defined in the localization key. So when I comment out those, I can compile the pdf with no problem.

Since new bibstrings need to be announced in `biblatex.sty` (or with `\NewBibliographyString`) some strings might come out as undefined if your `biblatex` is not quite as new as the current dev version. Usually that is nothing to worry about and there will only be a few of those strings that can be checked manually. Once the `.lbx` is released everything will work correctly. Of course I can't say anything more without knowing more about your  `biblatex` versions and the strings that caused the error.

> second, I did try to modify the extras, but wasn't able to compile the bibliography probably because of the date extras.

If you can tell me what you have done (i.e. show the modified `.lbx` file) I might be able to help. If translators have issues with the extras we usually tell them not to worry about it and copy the  extras from `german.lbx` (don't take the extras from `english.lbx` or `american.lbx` since they are unnecessarily complicated). We will fill in the correct extras based on the questionnaire from the wiki.


> The order of subject/verb/object is kind of reversed in turkish.
> 
> So do you think that a passive string like
>
> edited by some person [in english] = some author by edited [in turkish]
>
> would be a problem? if so, is there an easy work around.

If I understand correctly what you are saying then yes, that could be a problem. It would help if you could illustrate what you mean in an example. It would also help if you could try to find examples from actual Turkish bibliographies that show how situations like this are normally handled in Turkish.

It has become clear to me that even though `biblatex` has a lot to offer in the localisation department, some of its localisation features are woefully inadequate for languages that aren't part of
a broad western European Germanic/Romanic language family. At some point we will have to think about trying to overhaul the localisation system to make it more international. But that is going to involve a lot of effort and needs a lot of thought and input from speakers of a variety of languages to make sure the system is a flexible as necessary. I don't see that happening any time soon. For the time being we're stuck with what we have so far. Usually that means that we try to work around `biblatex`'s limitations.

Usually the easiest workarounds use some clever grammatical trick to get around `biblatex`'s limitations. Since I don't speak Turkish I can't offer any help there, I'm afraid. It might be possible to try and get the expected output by patching/redefining stuff that `.lbx` files usually don't touch (see for example `magyar.lbx`: https://github.com/plk/biblatex/blob/dev/tex/latex/biblatex/lbx/magyar.lbx, https://github.com/plk/biblatex/issues/717), but that involves quite some work, is bound to be less reliable than other localisation features and might not even be enough.

**Comment by abdulkerimgok** [comment] 2019-12-31 11:44
Thank you for all the help. 

All the issues with missing definitions (except langserbian and fromserbian which are I believe not included yet) and date extras have been solved. 

Turns out I needed an upgrade as you pointed out. 

The localization key now compiles with bibliography with no problem. 

And I assume all the translations are okay for now, but @bariserkus will do the review. 

You can see the turkish.lbx and the modified localization key file here. 

[](https://github.com/abdulkerimgok/biblatex/tree/feature/turkish-lbx/tex/latex/biblatex/lbx)

--- 
The actual problem is the grammar structure of Turkish language. Here is a snip from the pdf. 

![image](https://user-images.githubusercontent.com/11618766/71620050-afc3da80-2bd8-11ea-922d-06dec9cee6f9.png)

_Trf. düz. Warren E. Preece_ should read _Warren E. Preece trf. düz._ 

Trf. = tarafından = by [in English]
düz. = düzenlenmiştir = edited [in English]

It's _edited by Warren E. Preece_ in English, but with the same structure, it is not suited for Turkish. 

So in the passive voice in English, the subject or name comes at the end.

But, in Turkish, the subject or name comes in the beginning. 

I hope this example made it easier for you to understand what the problem is. 

---
So this is a problem for all the passive strings that start with "by" or "with". Not for others. 

We need to move names to the beginning for all passive strings. 

If there is not any easy solution, the only thing comes to my mind is that we translate all the passive strings as if there were active so that short versions of strings like _editortr_ and _byeditortr_ are the same. And that way it won't be totally wrong in Turkish.

**Comment by abdulkerimgok** [comment] 2019-12-31 11:47
Forgot to attach the link: 

You can see the turkish.lbx and the modified localization key file here. 

https://github.com/abdulkerimgok/biblatex/tree/feature/turkish-lbx/tex/latex/biblatex/lbx

**Comment by moewew** [comment] 2020-01-01 16:18
I opened a pull request with a few small modifications at https://github.com/abdulkerimgok/biblatex/pull/1.

----

I noticed that some strings contain `:` in trailing positions. Normally bibstrings should not contain trailing punctuation (except for punctuation signifying an abbreviation). The style should decide whether a colon, period or space should follow.

---

Moving names and strings is going to be extremely messy (if it is at all possible with sensible effort), so if there is a trick to keep the current word order and still produce grammatically correct Turkish that would be great. I realise this is a lot to ask, but if you could find real examples of Turkish bibliographies for works like this and could find out how they handle things, that might help us.

**Comment by moewew** [comment] 2020-08-31 15:04
`biblatex` 3.15 with the Turkish localisation has been released and is available in MikTeX and TeX live now.

Thanks to everybody who helped to make this happen!

**Closed by moewew** 2020-08-31 15:04 UTC
Labels: enhancement, fixedindev, localisation

**Comment by abdulkerimgok** [comment] 2020-09-14 13:08
> `biblatex` 3.15 with the Turkish localisation has been released and is available in MikTeX and TeX live now.
> 
> Thanks to everybody who helped to make this happen!

Great! 

Thank you for all the help...
