### ISSUE TITLE
Text line contains an invalid character.

### ISSUE THREAD

**Issue by gerdji** [plk/biblatex#1051] opened 2020-09-09 15:02 UTC
The latest Biblatex update results in an error during compiling:
The text line contains an invalid character. \bgroup\nohyphenation#1\egroup
(see Screenshot).
![invalid_character](https://user-images.githubusercontent.com/71025861/92616182-37143280-f2be-11ea-975b-6353f859ad36.png)

If I comment the following part out, everything works fine again.

% work around odd XeTeX/babel-french behaviour
% https://github.com/plk/biblatex/issues/979
% fix by Ulrike Fischer
% https://tex.stackexchange.com/a/544914/
\ifundef\XeTeXrevision
  {\providerobustcmd*{\textnohyphenation}[1]{%
     \bgroup\nohyphenation#1\egroup}}
  {\providerobustcmd*{\textnohyphenation}[1]{%
     \bgroup\nohyphenation#1\egroup^^^^200b}}

**Comment by moewew** [comment] 2020-09-09 15:35
This sounds like it could be related to https://github.com/plk/biblatex/issues/1044. It would be great if you could post a fully compilable example document that throws the error so we can be sure that the fix suggested in #1044 (https://github.com/plk/biblatex/commit/2e5ec8bd1d267203b76a2a6922507ebd498af9e2) works here as well. I do not get an error from a simple example like
```latex
\documentclass[british]{article}
\usepackage[T1]{fontenc}
\usepackage[utf8]{inputenc}
\usepackage{babel}
\usepackage{csquotes}

\usepackage[style=authoryear, backend=biber]{biblatex}

\addbibresource{biblatex-examples.bib}


\begin{document}
Lorem \autocite{sigfridsson}
\printbibliography
\end{document}
```
does not error for me.

**Comment by plk** [comment] 2020-09-09 15:37
Looks like this is in the master branch but not dev? Perhaps it was fixed after the last release?

**Comment by moewew** [comment] 2020-09-09 15:40
Yeah, it was fixed on `dev`. It's one of the fixes lined up for 3.15b.

A few other things need feedback and https://github.com/plk/biblatex/issues/1041 needs some more work, but I'm hoping to be able to give the go for 3.15b soon-ish.

**Comment by plk** [comment] 2020-09-09 15:42
Ah, fine, I though you had probably already dealt with this for 3.15b

**Comment by moewew** [comment] 2020-09-15 15:38
@gerdji Did you get a chance to test the fix at #1044? If not, a short test file that reproduces the error would be very much appreciated, so I can test if the fix from #1044 also solves this issue.

**Comment by gerdji** [comment] 2020-09-17 07:04
Sorry I could not respond earlier.
Indeed it seems that the pdfx-Package causes the error:

%minimal example
\documentclass[british]{article}
\usepackage[T1]{fontenc}
\usepackage[utf8]{inputenc}
\usepackage{babel}
\usepackage{csquotes}
\usepackage[a-1b]{pdfx}  

\usepackage[style=authoryear, backend=biber]{biblatex}

\addbibresource{biblatex-examples.bib}

\begin{document}
	Lorem \autocite{sigfridsson}
	\printbibliography
\end{document}
%%%%

**Comment by moewew** [comment] 2020-09-17 07:08
Thank you very much for that. MWE. I can reproduce the issue with v3.15a and can confirm that the fix for #1044 lined up for 3.15b resolves the problem.

I'll close this issue here as a duplicate. Further comments about this issue can be left in #1044.

**Closed by moewew** 2020-09-17 07:08 UTC
Labels: needs-feedback

**Comment by moewew** [comment] 2020-09-19 12:32
@plk  I think I have everything ready that I wanted to release in 3.15b. So I think we can release. 


Question is if we also want to release a Biber update to fix https://github.com/plk/biber/issues/329. In that case we might want to go for `biblatex` 3.16/Biber 2.16. That would also make sure that the Windows Biber binary on CTAN is repaired (https://github.com/plk/biber/issues/334).

**Comment by plk** [comment] 2020-09-20 19:39
@moewew - I think 2.16/3.16 is the best idea, yes. Just a bit of testing on the datamodel validation change in `biber`.
