### ISSUE TITLE
\printbiblist not consistent with \printbibliography

### ISSUE THREAD

**Issue by jiewuza** [plk/biblatex#814] opened 2018-10-07 08:48 UTC
I came across this issue when I was writing a `.cls` file.
I use biblatex as
```
\RequirePackage[sorting=none,backend=biber,style=numeric-comp,bibstyle=gb7714-2015,defernumbers=true]{biblatex}
```
And this is a test.bib
```
@article{testkey,
author = {Author},
title = {A Test},
journal = {Journal Name},
volume = {44},
number = {5},
pages = {569 - 581},
year = {2018}
}
```

With \printbibliography, I get in pdf:
`AUTHOR. A Test[J]. Journal Name, 2018, 44(5): 569-581.`, which is consistent with bibstyle=gb7714-2015.

While, with \printbiblist, I get in pdf:
`AUTHOR. A Test[J]. Journal Name, 5. 2018: 569-581.`.
Note that `volume` is missing and `number` goes before `year`.

**Comment by moewew** [comment] 2018-10-07 08:59
That is not unexpected. `\printbibliography` and `\printbiblist{...}` are mean to do different things.

- `\printbibliography` prints a bibliography
- `\printbiblist{...}` is a generalisation of what used to be `\printshorthands`, i.e. a list of certain bibliography entries along with a certain label and an explanatory text that resolves this label. It need not be the case that the entry in a bibliography list and the bibliography coincide. It is up to the style to decide this.

See for example
```
\documentclass[british]{article}
\usepackage[T1]{fontenc}
\usepackage[utf8]{inputenc}
\usepackage{babel}
\usepackage{csquotes}

\usepackage[style=authoryear, backend=biber]{biblatex}

\addbibresource{biblatex-examples.bib}


\begin{document}
\cite{sigfridsson,knuth:ct:a,kant:kpv,kant:ku}
\printbibliography
\printbiblist{shorthand}
\end{document}
```
with the standard styles.

Please show us a *complete* example document (see https://tex.meta.stackexchange.com/q/228/35864 and https://tex.meta.stackexchange.com/q/4407/35864) that reproduces your undesired output and not just code snippets. But please note that at the moment your code involves the contributed style `gb7714-2015` for which issues should be reported at https://github.com/hushidong/biblatex-gb7714-2015, ideally you would reproduce the issue with only the standard styles.

**Comment by jiewuza** [comment] 2018-10-07 13:58
Here is an example.tex
```
\documentclass[british]{example}
\addbibresource{test.bib}

\begin{document}
\maketitle
\cite{testkey}
\printbibliography
\end{document}
```

The example.cls:
```
\NeedsTeXFormat{LaTeX2e}
\ProvidesClass{example}[]

\LoadClass[12pt,a4paper]{article}
 \RequirePackage[sorting=none,backend=biber,autocite=superscript,style=numeric-comp,
   defernumbers=true,
 ]{biblatex}

\renewcommand{\maketitle}[1][12em]{
	\begin{titlepage}
		\begin{center}
      \printbiblist[heading=none,title=none]{test}
		\end{center}
	\end{titlepage}
}
```

And test.bib is the same.
You just put the those files in the same directory, and do `latexmk example.tex`

**Comment by moewew** [comment] 2018-10-07 14:38
Mhhh, I'm not entirely sure what you want to use `\printbiblist` for in your actual document, but at least in the MWE it does not really look like the right tool for the job.

The documentation explains `\printbiblist` as follows (§3.7.3 *Bibliography Lists*)
> `biblatex `can, in addition to printing normal bibliographies, also print arbitrary lists of information derived from the bibliography data such as a list of shorthand abbreviations for particular entries or a list of abbreviations of journal titles.

To me that seems to imply that bibliography lists are meant to highlight particular bits of the entry data in a way different from the normal bibliography. It is commonly used to resolve `shorthands` or other kind of abbreviations or short terms. See my example above or https://tex.stackexchange.com/q/349875/35864 a related idea is https://www.ctan.org/pkg/biblatex-shortfields

It goes on to explain
> A bibliography list differs from a normal bibliography in that the same bibliography driver is used to print all entries rather than a specific driver being used for each entry depending on the entry type.

In particular
```
\printbiblist{<biblistname>}
```
tries to call the driver `<biblistname>` and not the usual driver for the specific entry type for each item.

Indeed in the `.log` file of the MWE we find
```
Package biblatex Warning: No driver for entry type 'test'.
(biblatex)                Using fallback driver on input line 26.
```
The fallback driver then gives different results than the actual type-specific drivers.
The immediate problem could be resolved by defining  a `test` driver similar to the `shorthand` driver.

```
\documentclass[british]{article}
\usepackage[T1]{fontenc}
\usepackage[utf8]{inputenc}
\usepackage{babel}
\usepackage{csquotes}
\usepackage[sorting=none,backend=biber,autocite=superscript,style=numeric-comp,defernumbers=true]{biblatex}

\usepackage{filecontents}
\begin{filecontents}{\jobname.bib}
@article{testkey,
author = {Author},
title = {A Test},
journal = {Journal Name},
volume = {44},
number = {5},
pages = {569 - 581},
year = {2018}
}
\end{filecontents}

\addbibresource{\jobname.bib}

\DeclareBibliographyDriver{test}{%
  \usedriver
    {}
    {\thefield{entrytype}}%
  \finentry}

\begin{document}
\begin{center}
\printbiblist[heading=none,title=none]{test}
\end{center}

\cite{testkey}

\printbibliography
\end{document} 
```

But I am very sceptical that this is a good use for `\printbiblist`. What stops you from using
```
\printbibliography[heading=none]
```
instead?

**Comment by jiewuza** [comment] 2018-10-08 01:52
Thank you for your explanation. It really helps me understand biblatex document.
And yes, at first I was using `\printbibliography[heading=none]`.
But there would be a label number `[1]` before the bibliography.

Then I tried `\printbibliography[omitnumbers=true,heading=none]` to hide the leading numbers.
I had enabled `defernumbers` according to the document, however, it does not work. 

And finally I came across `\printbiblist`, and it hides the leading number.
I must admit that I did not understand the document well at the time I used it, until you explain to me.

**Comment by moewew** [comment] 2018-10-08 05:37
Mhhh, I still don't quite understand what you want to use `\printbiblist` for, but you get citations that are very similar to the bibliography entry with `\fullcite`. And you could also define a new bibliography environment without numbers.

```
\documentclass[british]{article}
\usepackage[T1]{fontenc}
\usepackage[utf8]{inputenc}
\usepackage{babel}
\usepackage{csquotes}

\usepackage[style=numeric, backend=biber]{biblatex}

\addbibresource{biblatex-examples.bib}

\defbibenvironment{weirdbib}
  {\list
     {}
     {\setlength{\leftmargin}{0pt}%
      \setlength{\itemsep}{\bibitemsep}%
      \setlength{\parsep}{\bibparsep}}%
      \renewcommand*{\makelabel}[1]{\hss##1}}
  {\endlist}
  {\item}

\begin{document}
\fullcite{sigfridsson}
\printbibliography[env=weirdbib]
\end{document}
```

**Comment by jiewuza** [comment] 2018-10-08 08:09
Well, I must misused `\printbiblist`.
I have two bib-list, say "fixed" category and "dynamic" category.
I want to print the two list as:
for "fixed" category, print no heading, just a list of bibs without the leading number label ([1] and etc.)
for "dynamic" category, print "References" heading, and then a list starting from [1];

This `weirdbib` environment almost does what I want, except that the "dynamic" category starts from other number than 1. Here is a MWE:
```
\documentclass[british]{article}

\usepackage[sorting=none,backend=biber,autocite=superscript,style=numeric-comp]{biblatex}
\addbibresource{test.bib}
\DeclareBibliographyCategory{fixed}
\addtocategory{fixed}{testkey}

\defbibenvironment{weirdbib}
  {\list
     {}
     {\setlength{\leftmargin}{0pt}%
      \setlength{\itemsep}{\bibitemsep}%
      \setlength{\parsep}{\bibparsep}}%
      \renewcommand*{\makelabel}[1]{\hss##1}}
  {\endlist}
  {\item}

\begin{document}
\autocite*{testkey}      % in fact I want the bibs of fixed category always be printed 
                                       % no matter cited or not, but I do not know how to do this, so I just cited it for the time being

\printbibliography[heading=none,env=weirdbib,category=fixed]

\autocite{testkey2,testkey3}

\printbibliography[notcategory=fixed]               % result: 
                                                                               % [2]  blah blah ....       
                                                                               % [3]  blah blah ....  
\end{document}
```

**Comment by jiewuza** [comment] 2018-10-08 14:27
Nice! I learnt a lot about biblatex from your code. 
Thank you very much.

**Comment by moewew** [comment] 2018-10-09 08:34
I'm closing this now as *invalid* because things work as intended.

If you'd like more help with your document, you can ask questions on https://tex.stackexchange.com/questions/tagged/biblatex or your favourite LaTeX forum.

**Closed by moewew** 2018-10-09 08:34 UTC
Labels: invalid, question

**Comment by jiewuza** [comment] 2018-10-14 09:04
@moewew I still have a very closely related question.
I can set `doi=false, url=false, isbn=false, eprint=false` options for biblatex package. 
But can I omit doi, url, isbn, sprint when printing the fixed category bib-list, while still print them for the dynamic category.

**Comment by moewew** [comment] 2018-10-14 09:32
It is not a documented feature, but the internal implementation of these options allows you to say something like `\togglefalse{bbx:eprint}` at least with the standard styles. You can keep the effect local by using it within a refsection of with `\begingroup...\endgroup`
```
\documentclass[british]{article}

\usepackage[sorting=none,backend=biber,autocite=superscript,style=numeric-comp]{biblatex}
\addbibresource{biblatex-examples.bib}
\DeclareBibliographyCategory{fixed}
\addtocategory{fixed}{sigfridsson}

\defbibenvironment{weirdbib}
  {\list
     {}
     {\setlength{\leftmargin}{0pt}%
      \setlength{\itemsep}{\bibitemsep}%
      \setlength{\parsep}{\bibparsep}}%
      \renewcommand*{\makelabel}[1]{\hss##1}}
  {\endlist}
  {\item}

\begin{document}
\begin{refsection}
\nocite{sigfridsson}
\togglefalse{bbx:url}\togglefalse{bbx:eprint}\togglefalse{bbx:doi}\togglefalse{bbx:isbn}
\printbibliography[heading=none,env=weirdbib]
\end{refsection}

\autocite{geer,worman,kastenholz}
\printbibliography
\end{document}
```

Please note that the issue tracker here should only be used to report bugs, suggest features or discuss the development of the package. Support questions and 'how do I do ...' are better asked in forums like https://latex.org/forum/viewforum.php?f=50 or Q&A sites like https://tex.stackexchange.com/questions/tagged/biblatex. We simply don't have the capacity for that.

**Comment by jiewuza** [comment] 2018-10-14 09:45
Wow~~ Thank you. 
The question is based on the context, so I asked it here. 
I will ask for help on those sites.
