### ISSUE TITLE
"file" field processing bug with unexpected newline

### ISSUE THREAD

**Issue by FieldsLi** [plk/biblatex#500] opened 2016-10-20 11:53 UTC
### reproduce the bug
Suppose I have a MWE as follows:
```latex
\documentclass{article}
\usepackage{color}
\usepackage[backend=bibtex8]{biblatex}
\begin{filecontents}{bibtest.bib}
@article{Boumans1998,
	author = {Boumans, R. and Heemskerk, C.},
	doi = {10.1016/S0921-8890(97)00054-7},
	file = {:D$\backslash$:/LIB@Mendeley/Robotics and Autonomous Systems/1998, Boumans, Heemskerk, The European Robotic Arm for the International Space Station.pdf:pdf},
	issn = {09218890},
	journal = {Rob. Auton. Syst.},
	keywords = {era,european robotic ann,space robotics},
	pages = {17--27},
	title = {{The European Robotic Arm for the International Space Station}},
	volume = {23},
	year = {1998}
}
@phdthesis{watkins89,
	author = {Watkins, Christopher J. C. H.},
	booktitle = {PhD Thesis},
	file = {:D$\backslash$:/LIB@Mendeley/PhD Thesis/1989, Watkins, Learning from Delayed Rewards.pdf:pdf},
	title = {{Learning from Delayed Rewards}},
	year = {1989}
}
\end{filecontents}
\addbibresource{bibtest.bib}
\begin{document}
\color{blue}
Nothing should be output before this line
\cite{Boumans1998}
\cite{watkins89}
\printbibliography
\end{document}
```
However, the result pdf by using pdflatex gives
![r](https://cloud.githubusercontent.com/assets/17979090/19558733/b0f6fd50-96fe-11e6-91d5-b616159941ff.png)

### direction cause

The reason is that the generated \jobname.bbl gives as follows
```latex
% $ biblatex auxiliary file $
% $ biblatex bbl format version 2.7 $
% Do not modify the above lines!
%
% This is an auxiliary file used by the 'biblatex' package.
% This file may safely be deleted. It will be recreated as
% required.
%
\begingroup
\makeatletter
\@ifundefined{ver@biblatex.sty}
  {\@latex@error
     {Missing 'biblatex' package}
     {The bibliography requires the 'biblatex' package.}
      \aftergroup\endinput}
  {}
\endgroup

\sortlist[entry]{nty/global/}
  \entry{Boumans1998}{article}{}
    \name{author}{2}{}{%
      {{hash=BR}{%
         family={Boumans},
         family_i={B\bibinitperiod},
         given={R.},
         given_i={R\bibinitperiod},
      }}%
      {{hash=HC}{%
         family={Heemskerk},
         family_i={H\bibinitperiod},
         given={C.},
         given_i={C\bibinitperiod},
      }}%
    }
    \keyw{era,european robotic ann,space robotics}
    \strng{namehash}{BRHC1}
    \strng{fullhash}{BRHC1}
    \field{labelnamesource}{author}
    \field{labeltitlesource}{title}
    \field{sortinit}{B}
    \field{sortinithash}{B}
    \verb{doi}
    \verb 10.1016/S0921-8890(97)00054-7
    \endverb
    \field{issn}{09218890}
    \field{pages}{17\bibrangedash 27}
    \field{title}{{The European Robotic Arm for the International Space
  Station}}
    \field{volume}{23}
    \verb{file}
    \verb :D$\backslash$:/LIB@Mendeley/Robotics and Autonomous Systems/1998,
  Boum
    \verb ans, Heemskerk, The European Robotic Arm for the International Space
  St
    \verb ation.pdf:pdf
    \endverb
    \field{journaltitle}{Rob. Auton. Syst.}
    \field{year}{1998}
  \endentry

  \entry{watkins89}{thesis}{}
    \name{author}{1}{}{%
      {{hash=WCJCH}{%
         family={Watkins},
         family_i={W\bibinitperiod},
         given={Christopher J. C.\bibnamedelima H.},
         given_i={C\bibinitperiod\bibinitdelim J\bibinitperiod
  C\bibinitperiod\bibinitdelim H\bibinitperiod},
      }}%
    }
    \strng{namehash}{WCJCH1}
    \strng{fullhash}{WCJCH1}
    \field{labelnamesource}{author}
    \field{labeltitlesource}{title}
    \field{sortinit}{W}
    \field{sortinithash}{W}
    \field{booktitle}{PhD Thesis}
    \field{title}{{Learning from Delayed Rewards}}
    \verb{file}
    \verb :D$\backslash$:/LIB@Mendeley/PhD Thesis/1989, Watkins, Learning from
  De
    \verb layed Rewards.pdf:pdf
    \endverb
    \field{type}{phdthesis}
    \field{year}{1989}
  \endentry
\endsortlist
\endinput

```

In this \jobname.bbl, the bug lies here
```latex
******
    \verb{file}
    \verb :D$\backslash$:/LIB@Mendeley/Robotics and Autonomous Systems/1998,
  Boum
    \verb ans, Heemskerk, The European Robotic Arm for the International Space
  St
    \verb ation.pdf:pdf
    \endverb
******
    \verb{file}
    \verb :D$\backslash$:/LIB@Mendeley/PhD Thesis/1989, Watkins, Learning from
  De
    \verb layed Rewards.pdf:pdf
    \endverb
******
```
It seems that each \verb just out put a string with a maximal length of 72 chars (the last 4 chars are put in the newline without \verb).
### more information that may help

I think the related codes of biblatex may be
`\DeclareFieldFormat{file}{\url{#1}}` in biblatex.def, 
```latex
% Verbatim fields
% {<field>}
\protected\def\blx@bbl@verbdef#1{%
  \begingroup
  \let\verb\blx@bbl@verbadd
  \def\blx@tempa{#1}%
  \let\NewValue\@empty}

\protected\def\blx@bbl@verbend{%
  \ifcsdef{blx@fih@\blx@tempa}
    {\csname blx@fih@\blx@tempa\expandafter
     \endcsname\expandafter{\NewValue}%
     \ifdefvoid\NewValue}
    {\@secondoftwo}
       {}
       {\blx@bbl@addfield{\blx@tempa}{\NewValue}}%
  \endgroup}
******
\def\blx@hook@fileverb{%
  \let\do\@makeother
  \dospecials
  \catcode`\\=\z@
  \catcode`\{=\@ne
  \catcode`\}=\tw@}
```
in biblatex.sty
and `\RequirePackage{url}` in biblatex.sty.
These information may help, but I am not sure.

I hope anyone can confirm this bug or fix it. Good Luck!

**Comment by plk** [comment] 2016-10-20 13:19
Can you use biber? It does not have this problem. @josephwright - is this something that can be fixed in the .bst for bibtex backend?

**Comment by FieldsLi** [comment] 2016-10-20 14:28
Thank your for your quick response.

I am using texlive2016. Before posting this issue, I have tried setting default bibliography tool as biber, and using command line to compile the main.tex. Both generated a blank _main.bbl_ file, leaving the bibliography empty. So I used bibtex or bibtex8 (both of which have the above issue).

As the biber is capable of producing the pdf correctly, I will try to get my biber work corrrectly at this stage.

Thanks for the help! And biblatex is awesome!

**Comment by moewew** [comment] 2016-10-20 16:48
I'm pretty sure this is actually a duplicate of https://github.com/plk/biblatex/issues/449. Why Biber does not work for you we can't say from here. It works for me on your MWE.

**Comment by FieldsLi** [comment] 2016-10-21 01:59
That's right, this issue is a **duplicate of #499**. I failed to find that issue before posting this issue. I should search more carefully next time.

Yeah, the biber does produce a `.blg` file, which says
```
[0] Config.pm:354> INFO - This is Biber 2.6
[0] Config.pm:357> INFO - Logfile is 'main.blg'
[36] biber-MSWIN32:302> INFO - === 
[63] Biber.pm:359> INFO - Reading 'main.bcf'
[160] Biber.pm:823> INFO - Found 2 citekeys in bib section 0
[173] Biber.pm:3658> INFO - Processing section 0
[193] Biber.pm:3828> INFO - Looking for bibtex format file 'bibtest.bib' for section 0
```

I have compile the file in two ways: 
1. set the default bibliography tool as biber (also specified the `backend=biber` in `main.tex`), then hit F5 (with default compiler pdflatex); 
2. `pdflatex main.tex`, then `biber main.tex`, then `pdflatex main.tex`; [an answer at stackexchange](http://tex.stackexchange.com/questions/26516/how-to-use-biber)
Both of these ways gives me an empty `main.bbl`.

Am I doing it wrong, or what shoud I do to get biber to work fine?

**Comment by plk** [comment] 2016-10-21 06:28
You don't run biber on the `.tex` file, you run it on the `.bcf` file which the first latex pass produces: `biber main.bcf` or just `biber main`.

**Closed by plk** 2016-10-21 06:28 UTC
