### ISSUE TITLE
Latest biblatex raises compile error with pdfx package

### ISSUE THREAD

**Issue by xu-cheng** [plk/biblatex#1044] opened 2020-09-01 22:42 UTC
MWE:
```test
\documentclass{article}
\usepackage[a-1b]{pdfx}
\usepackage{biblatex}

\begin{document}
test
\end{document}
```

Compile log:
```
$ pdflatex test.tex
This is pdfTeX, Version 3.14159265-2.6-1.40.21 (TeX Live 2020) (preloaded format=pdflatex)
 restricted \write18 enabled.
entering extended mode
(./test.tex
LaTeX2e <2020-02-02> patch level 5
L3 programming layer <2020-08-07>
(/usr/local/texlive/2020/texmf-dist/tex/latex/base/article.cls
Document Class: article 2019/12/20 v1.4l Standard LaTeX document class
(/usr/local/texlive/2020/texmf-dist/tex/latex/base/size10.clo))
(/usr/local/texlive/2020/texmf-dist/tex/latex/pdfx/pdfx.sty
(/usr/local/texlive/2020/texmf-dist/tex/generic/iftex/iftex.sty)
(/usr/local/texlive/2020/texmf-dist/tex/generic/iftex/ifpdf.sty)
(/usr/local/texlive/2020/texmf-dist/tex/generic/iftex/ifxetex.sty)
(/usr/local/texlive/2020/texmf-dist/tex/latex/ms/everyshi.sty)
(/usr/local/texlive/2020/texmf-dist/tex/generic/iftex/ifluatex.sty){/usr/local/
texlive/2020/texmf-var/fonts/map/pdftex/updmap/pdftex.map}
(/usr/local/texlive/2020/texmf-dist/tex/latex/base/inputenc.sty)
(/usr/local/texlive/2020/texmf-dist/tex/latex/pdfx/l8u-penc.def)
(/usr/local/texlive/2020/texmf-dist/tex/latex/xcolor/xcolor.sty
(/usr/local/texlive/2020/texmf-dist/tex/latex/graphics-cfg/color.cfg)
(/usr/local/texlive/2020/texmf-dist/tex/latex/graphics-def/pdftex.def))
(/usr/local/texlive/2020/texmf-dist/tex/latex/hyperref/hyperref.sty
(/usr/local/texlive/2020/texmf-dist/tex/generic/ltxcmds/ltxcmds.sty)
(/usr/local/texlive/2020/texmf-dist/tex/generic/pdftexcmds/pdftexcmds.sty
(/usr/local/texlive/2020/texmf-dist/tex/generic/infwarerr/infwarerr.sty))
(/usr/local/texlive/2020/texmf-dist/tex/latex/graphics/keyval.sty)
(/usr/local/texlive/2020/texmf-dist/tex/generic/kvsetkeys/kvsetkeys.sty)
(/usr/local/texlive/2020/texmf-dist/tex/generic/kvdefinekeys/kvdefinekeys.sty)
(/usr/local/texlive/2020/texmf-dist/tex/generic/pdfescape/pdfescape.sty)
(/usr/local/texlive/2020/texmf-dist/tex/latex/hycolor/hycolor.sty)
(/usr/local/texlive/2020/texmf-dist/tex/latex/letltxmacro/letltxmacro.sty)
(/usr/local/texlive/2020/texmf-dist/tex/latex/auxhook/auxhook.sty)
(/usr/local/texlive/2020/texmf-dist/tex/latex/kvoptions/kvoptions.sty)
(/usr/local/texlive/2020/texmf-dist/tex/latex/hyperref/pd1enc.def)
(/usr/local/texlive/2020/texmf-dist/tex/generic/intcalc/intcalc.sty)
(/usr/local/texlive/2020/texmf-dist/tex/generic/etexcmds/etexcmds.sty)
(/usr/local/texlive/2020/texmf-dist/tex/latex/url/url.sty)
(/usr/local/texlive/2020/texmf-dist/tex/generic/bitset/bitset.sty
(/usr/local/texlive/2020/texmf-dist/tex/generic/bigintcalc/bigintcalc.sty))
(/usr/local/texlive/2020/texmf-dist/tex/generic/atbegshi/atbegshi.sty))
(/usr/local/texlive/2020/texmf-dist/tex/latex/hyperref/hpdftex.def
(/usr/local/texlive/2020/texmf-dist/tex/latex/atveryend/atveryend.sty)
(/usr/local/texlive/2020/texmf-dist/tex/latex/rerunfilecheck/rerunfilecheck.sty

(/usr/local/texlive/2020/texmf-dist/tex/generic/uniquecounter/uniquecounter.sty
))) (/usr/local/texlive/2020/texmf-dist/tex/latex/hyperref/puenc.def)
(/usr/local/texlive/2020/texmf-dist/tex/generic/stringenc/stringenc.sty)
(/usr/local/texlive/2020/texmf-dist/tex/latex/hyperref/psdextra.def)
(/usr/local/texlive/2020/texmf-dist/tex/generic/colorprofiles/colorprofiles.sty

(/usr/local/texlive/2020/texmf-dist/tex/generic/colorprofiles/colorprofiles.tex
)) (/usr/local/texlive/2020/texmf-dist/tex/generic/stringenc/se-pdfdoc.def)
(/usr/local/texlive/2020/texmf-dist/tex/latex/pdfx/AdobeColorProfiles.tex)
(/usr/local/texlive/2020/texmf-dist/tex/latex/pdfx/8bit.def)
** pdfx: No file test.xmpdata . Metadata will be incomplete!
<<sRGB.icc>> (/usr/local/texlive/2020/texmf-dist/tex/latex/pdfx/8bit.def)
(/usr/local/texlive/2020/texmf-dist/tex/generic/pdftex/glyphtounicode.tex)
(/usr/local/texlive/2020/texmf-dist/tex/latex/pdfx/glyphtounicode-cmr.tex)
(/usr/local/texlive/2020/texmf-dist/tex/latex/pdfx/glyphtounicode-ntx.tex)
(/usr/local/texlive/2020/texmf-dist/tex/latex/base/ifthen.sty)
(/usr/local/texlive/2020/texmf-dist/tex/latex/xmpincl/xmpincl.sty)
(/usr/local/texlive/2020/texmf-dist/tex/latex/pdfx/8bit.def)
Using XMP template file: pdfa.xmp
<<pdfa.xmpi>>)
(/usr/local/texlive/2020/texmf-dist/tex/latex/biblatex/biblatex.sty
(/usr/local/texlive/2020/texmf-dist/tex/latex/etoolbox/etoolbox.sty)
(/usr/local/texlive/2020/texmf-dist/tex/latex/logreq/logreq.sty
(/usr/local/texlive/2020/texmf-dist/tex/latex/logreq/logreq.def))
! Text line contains an invalid character.
l.2175      \bgroup\nohyphenation#1\egroup^^^
                                             ^200b}}
?
```

**Comment by moewew** [comment] 2020-09-02 05:34
Thank you for reporting this.

That's https://github.com/plk/biblatex/commit/cd0cccf5cc8144b27786c21ea55c413d0ac3a297 for #979 coming back to bite us.

I don't fully understand the root cause of this, but I'm guessing `pdfx` makes Unicode chars like this *invalid* with pdfLaTeX and so the line errors very early on when it is read (it is never executed). https://github.com/plk/biblatex/commit/2e5ec8bd1d267203b76a2a6922507ebd498af9e2 moves the Unicode char to `blx-unicode.blx`, which is only read by LuaLaTeX and XeLaTeX, where `U+200B` doesn't appear to have been made invalid.

**Comment by davidcarlisle** [comment] 2020-10-01 20:16
It is  character 30 (control-^) which is set to catcode15 (you see same with `\UseRawInputEncoding` even if pdfx is not used.)  An alternative would be to use `\char"200B`

**Comment by moewew** [comment] 2020-10-02 06:07
@davidcarlisle Is `\char"200B` different from `^^^^200b` in a way that could come back and haunt us here? I don't really understand why `^^^^200b` fixed https://github.com/plk/biblatex/issues/979 in the first place, so I'd like to understand if and how further changes here can break even more stuff.

**Comment by davidcarlisle** [comment] 2020-10-02 08:41
@moewew  yes it could bite you, to take a simpler example `^^41` parses as `A`  so `\typeout{^^41}`  types out A (and similar makes A in pdf bookmarks or auxiliary files passed to biber or whatever).  Conversely `\char"41` _typesets_ as A but in a typeout or other expansion only contexts it makes `\char"41` so probably not what you want.

So if I read it right it was OK in that place but in other places it could fail.

Apparently pdfx is going to change not to leave this as catcode15 anyway but it could come up in other places (\UseRawEncoding` is the culprit really.

**Comment by moewew** [comment] 2020-10-07 06:16
@davidcarlisle Thanks for the explanation. I guess we'll stick with `^^^^200b` but bury it in the Unicode-only file so only LuaLaTeX and XeLaTeX get to see it.

----

If anyone needs a quick workaround for the issue before we release `biblatex` 3.16, David suggests something at https://tex.stackexchange.com/q/564990/35864.

**Comment by thbtppl** [comment] 2020-12-14 17:15
I just wanted to ask whether there is any set date for the release of biblatex 3.16?
I figured I get a lot of warning in my log files partially due to the \catcode workaround.
The \catcode fix needs to be done after loading pdfx but before loading biblatex.
However hyperref should be among the last loaded packages, but pdfx loads it.

**Comment by moewew** [comment] 2021-01-03 07:29
`biblatex` v3.16 with a fix for this issue was released in 31 Dec 2020 and is available now in both MikTeX and TeX live. With that version the MWE from above compiles fine again.

**Closed by moewew** 2021-01-03 07:29 UTC
Labels: bug, fixedindev

**Comment by mvrozanti** [comment] 2021-05-17 13:51
For those of us not using `pdfx`, but who depend on `\UseRawInputEncoding`, is there a workaround available? I'm on `BibTeX 0.99d (TeX Live 2020/Arch Linux)`

**Comment by davidcarlisle** [comment] 2021-05-17 14:08
@mvrozanti  There is really no use case for `\UseRawInputEncoding` other than to use as a quick temporary patch if using some old code designed for latex2.09 that was never updated for inputenc . Since inputenc has been available since 1994 hopefully this is rather rare.

**Comment by moewew** [comment] 2021-05-17 14:56
With the current release version of `biblatex` (v3.16) I cannot reproduce an obvious issue related to `\UseRawInputEncoding`
```latex
\UseRawInputEncoding
\documentclass[british]{article}
\usepackage[T1]{fontenc}
\usepackage{babel}
\usepackage{csquotes}

\usepackage[backend=biber, style=authoryear]{biblatex}

\addbibresource{biblatex-examples.bib}

\begin{document}
Lorem \autocite{sigfridsson}

\printbibliography
\end{document}
```
compiles fine for me.

But as @davidcarlisle says, you probably don't need (or want) `\UseRawInputEncoding` anyway.

**Comment by mvrozanti** [comment] 2021-05-17 15:06
Turns out I really didn't it. Thanks for the response anyway guys!
