### ISSUE TITLE
for a specific entry, not inheriting the field of the mother entry

### ISSUE THREAD

**Issue by maieul** [plk/biblatex#403] opened 2016-04-04 16:35 UTC
I refer anonymous works published in a not anonymous work

````
@book{Main,
  Author = {Someone},
  Title={Some title}
}

@bookinbook{Second,
  Title={Some title},
  Crossref={Main}
`````
Theere is two for `Second` not inheriting `Main`:
- use `noinherit` in `\DeclareDataInheritance`. However, for some books, I want the inheritance.
- use empty field `Title={}` but 
   - makes biber warning
   - some gui, as bibdesk, automatically delete them.

Should it be possible to add option to directy tell on a .bib entry to not inherit some field ? to make exception on \DeclareDataInheritance

**Comment by plk** [comment] 2016-04-04 20:48
I have added  a per-entry option to block all inheritance on an entry but blocking on certain fields per-entry would be too complex.

```
@bookinbook{Second,
  OPTIONS = {noinherit},
...
```

**Comment by maieul** [comment] 2016-04-04 20:56
unfortunatly, a per-entry option is totally unuseful… in my case, for example, I need that the <code>title</code> of the main entry become the <code>booktitle</code> of the subentry.

Should it not be possible to do something like <code>Author={\Noinherit}</code> in the subentry ?

**Comment by plk** [comment] 2016-04-04 21:13
This would be very difficult. What about a combination of source mapping to add

```
field = {\relax}
```
and then defining inheritance rules with `override=false` for those fields?

**Comment by maieul** [comment] 2016-04-04 21:47
For now, what I can do is something like this 

````
\DeclareSourcemap{
  \maps[datatype=bibtex]{
    \map[overwrite]{
  	  \step[match=\string\\relax,fieldsource=author,fieldtarget=author,fieldvalue={}]
	  }
 }
}
`````

But I don't see how I could do a noinherit in \DeclareSourcemap. Also, I can see how I could do it for ALL the field containing a relax, and not only author field.

**Comment by plk** [comment] 2016-04-05 09:14
I haven't really thought about it too much but I had an idea you could *create* fields with `\relax` in them and then in `\DeclareDataInheritance`, make sure `override=false` is set in the right places to prevent such fields being overrwritten which would effectively block just that field. If printed, the fields do nothing.

**Comment by maieul** [comment] 2016-04-05 09:27
"If printed, the fields do nothing." yes, but it will fail on "ifnameundef" ?

**Comment by plk** [comment] 2016-04-05 09:39
That's a potential problem, yes ...

**Comment by plk** [comment] 2016-04-06 18:50
Try biblatex 3.4/biber 2.5 again. I think it will do what you need now. Have a look at the biblatex PDF, page 199. You can define sets of fields to block using the new `\DeclareDatafieldSet` functionality and use these per-entry to block inheritance of fields per-entry.

**Comment by maieul** [comment] 2016-04-06 19:00
I will look Friday, or this week-end.

**Comment by maieul** [comment] 2016-04-08 11:57
I have looked on the hanbdook. It seems to be ok for me.

However, the biber version does not work

- dowloaded by https://sourceforge.net/projects/biblatex-biber/files/biblatex-biber/development/binaries/OSX_Intel/biber-darwin_x86_64.tar.gz/download.
- <code>biber *bcf</code>
- error message <code>dyld: Library not loaded: /opt/local/lib/perl5/5.22/darwin-thread-multi-2level/CORE/libperl.dylib
  Referenced from: /var/folders/0g/vh5y8yv93js6v76gmjpnt4mr0000gr/T//par-6d616965756c/cache-a06ceeaebd8c05e62e25f7d6b91364d7adb646b8/biber
  Reason: image not found
Trace/BPT trap: 5</code>

I am on a Mac with OS X 10.8.5, Intel Core i7

**Comment by plk** [comment] 2016-04-08 13:16
Hmm I just downloaded that and it worked fine. I am running on 10.11.4. It's built on a machine running 10.6. Is this the first time it's not worked for you like this?

**Comment by maieul** [comment] 2016-04-08 13:17
yes, first time.

**Comment by maieul** [comment] 2016-04-08 13:18
<code>biber --cache</code> also produce the same problem.

**Comment by maieul** [comment] 2016-04-08 13:23
here, maybe, one piste

http://stackoverflow.com/q/17703510/3206025

**Comment by plk** [comment] 2016-04-08 13:57
This looks like a PAR::Packer bug, I have reported it.

**Comment by maieul** [comment] 2016-04-08 14:00
ok, so wait and see.

**Comment by plk** [comment] 2016-04-10 14:09
Can you pull biber 2.5 dev again. It is very strange, I have been diagnosing this with the PAR::Packer author and he couldn't reproduce. I could but now, in the middle of diagnosing, I can't reproduce any more - it works fine ...

**Comment by maieul** [comment] 2016-04-10 14:26
tried again with the version uploaded on SF the 2016-04-08.

same problem

**Comment by plk** [comment] 2016-04-10 15:24
What about the DEV i386 version? And also this one:

https://www.dropbox.com/s/4jc98419kfysljb/biber.zip?dl=0

**Comment by maieul** [comment] 2016-04-10 15:30
Dropbox version have a little different message:
````
dyld: lazy symbol binding failed: Symbol not found: ___strlcpy_chk
  Referenced from: /var/folders/0g/vh5y8yv93js6v76gmjpnt4mr0000gr/T//par-6d616965756c/cache-671ac266ecef6ef66c1cc9249960e158b875f3e6/e4e6251f.bundle
  Expected in: /usr/lib/libSystem.B.dylib

dyld: Symbol not found: ___strlcpy_chk
  Referenced from: /var/folders/0g/vh5y8yv93js6v76gmjpnt4mr0000gr/T//par-6d616965756c/cache-671ac266ecef6ef66c1cc9249960e158b875f3e6/e4e6251f.bundle
  Expected in: /usr/lib/libSystem.B.dylib

Trace/BPT trap: 5
````

The i386 producted

`````
dyld: Library not loaded: /opt/local/lib/perl5/5.22/darwin-thread-multi-2level/CORE/libperl.dylib
  Referenced from: /var/folders/0g/vh5y8yv93js6v76gmjpnt4mr0000gr/T//par-6d616965756c/cache-4edcca91e079ce8da23d6bc98b3f9c47f4928ba2/biber
  Reason: image not found
Trace/BPT trap: 5
````

**Comment by plk** [comment] 2016-04-10 15:32
Ok, the first one is because that was built on 10.11. The second one is the same error. Still investigating.

**Comment by plk** [comment] 2016-04-10 15:40
I think we have found the issue, it's a change in the latest Par-Packer release which breaks builds on older OSX systems. I use 10.5 and 10.6 to build for maximum compat. Building on 10.11 is fine. Looking into it.

**Comment by plk** [comment] 2016-04-10 16:10
Should be fixed - please pull the binaries uploaded just now.

**Comment by maieul** [comment] 2016-04-10 16:25
1) The error message does not more occur with both i386 and 64b Mac binaries.
2) Hoewever, despite the use of  biber --cache, there is many warning message identical `Use of uninitialized value in string eq at /var/folders/0g/vh5y8yv93js6v76gmjpnt4mr0000gr/T/par-6d616965756c/cache-ab61f4f9d1736d369af2791fc77d5beff9316ecc/inc/lib/Biber/Entry.pm line 656`
3) The `\DeclareDatafieldSet` and noinherit works well. Many thanks !

**Comment by plk** [comment] 2016-04-10 16:26
Can you give me a MWE to reproduce 2)?

**Comment by maieul** [comment] 2016-04-10 16:27
```
\documentclass{article}
\usepackage[style=verbose]{biblatex}
\DeclareDatafieldSet{noauthor}{
\member[field=author]
}
\usepackage{filecontents}
\begin{filecontents}{test.bib}
@book{Main,
  Author = {Someone},
  Title={Some title}
}

@bookinbook{Second,
  Title={Some title},
  Crossref={Main},
  Options = {noinherit=noauthor} 
}
\end{filecontents}
\bibliography{test.bib}
\begin{document}
\nocite{*}
\printbibliography
\end{document}
```

**Comment by plk** [comment] 2016-04-10 16:38
Fixed - please get the latest binary again.

**Comment by maieul** [comment] 2016-04-10 16:47
both x86 and 64b versions are working well now. Many thanks again.

**Closed** 2016-04-11 16:11 UTC
