### ISSUE TITLE
backref + hyperxmp/XMPLangAlt + AtEndPreamble -> "Command \do undefined"

### ISSUE THREAD

**Issue by urrameu** [plk/biblatex#1105] opened 2021-02-08 21:51 UTC
Hi,

This probably won't affect many people, but is weird and did not happen with previous versions of biblatex.

The `\XMPLangAlt` macro from the hyperxmp package redefines `\do` and so does biblatex. When calling `\XMPLangAlt` from within `\AtEndPreamble`, this causes LaTeX to stop with an error on the last iteration if `backref` is true (the macro that triggers the error is `\abx@aux@backref` in the AUX file). A MWE:

```latex
\documentclass{book}
\usepackage{etoolbox}

\usepackage{filecontents}
\begin{filecontents}{\jobname.bib}
@book{appleby,
  author  = {Humphrey Appleby},
  title   = {On the Importance of the Civil Service},
  year    = {1980},
}
\end{filecontents}
\usepackage[backref=true]{biblatex}
\addbibresource{\jobname.bib}

\usepackage{hyperref}
\usepackage{hyperxmp}
\AtEndPreamble{\XMPLangAlt{en}{pdfsubject={Something silly}}}

\begin{document}
Hi \cite{appleby}.
\printbibliography
\end{document}

```

Using `\AtBeginDocument` instead of `\AtEndPreamble` solves the problem, as well as calling `\XMPLangAlt` inside a group. This error does not occur with biblatex 3.12, but does occur with version 3.16. I will also write to the hyperxmp author about this.

**Comment by moewew** [comment] 2021-02-09 05:57
Thank you very much for reporting this bug.

It's caused by using `\renewcommand*{\do}` instead of `\def\do` in a macro. `hyperxmp`'s `\XMPLangAlt` sets `\do` to `\relax` so that `\renewcommand*{\do}` fails. Since `\do` is a scratch macro, we shouldn't assume anything about it, apparently not even that it is defined (and different from `\relax`).

A fix is in https://github.com/plk/biblatex/commit/6567414b0b2a658a867fc023e22842d42c26b9ad.

A workaround for now is to define `\do` again after `\XMPLangAlt`.
```latex
\errorcontextlines=100
\documentclass{book}
\usepackage[backref=true]{biblatex}

\usepackage{hyperref}
\usepackage{hyperxmp}
\AtEndPreamble{\XMPLangAlt{en}{pdfsubject={Something silly}}\def\do{}}

\begin{filecontents}{\jobname.bib}
@book{appleby,
  author  = {Humphrey Appleby},
  title   = {On the Importance of the Civil Service},
  year    = {1980},
}
\end{filecontents}
\addbibresource{\jobname.bib}

\begin{document}
Hi \autocite{appleby}.

\printbibliography
\end{document}
```
Of course another workaround would be to copy the new definition of `\blx@ifprintableinlist` from https://github.com/plk/biblatex/commit/6567414b0b2a658a867fc023e22842d42c26b9ad.

**Comment by moewew** [comment] 2022-02-08 06:48
`biblatex` 3.17 with the fix for this has been released and is available in both TeX live and MikTeX. The initial example file now compiles without error.

**Closed by moewew** 2022-02-08 06:48 UTC
Labels: bug
