### ISSUE TITLE
missing latin.lbx fatal in 3.12

### ISSUE THREAD

**Issue by ExecutorElassus** [plk/biblatex#872] opened 2019-02-16 14:19 UTC
I recently updated to biblatex version 3.12, biber version 2.12. In my document, I have the Latin language defined, which used to give a warning in the latex log during compilation that latin.lbx wasn't found (so far as I know there is no standard latin.lbx file, which is maybe another thing worth asking about), and that it was falling back to some other language.

Now, however, the error causes mis-formatting of the preamble, and compilation fails when it can't find the '\begin{document}' command later on. 

I'm encountering this problem with Lyx; downgrading biblatex/biber to 3.7/2.7 allows compilation to complete successfully despite the warning. I'm not sure if this is a problem with Lyx's formatting, or something different with biblatex, so I'm reporting here. 

Thanks for the help.

**Comment by moewew** [comment] 2019-02-16 14:23
Is there any chance that you could show us a short example document that reproduces the error (a so-called MWE, see for example https://texfaq.org/FAQ-minxampl, http://www.minimalbeispiel.de/mini-en.html, https://tex.meta.stackexchange.com/q/228/35864, https://tex.meta.stackexchange.com/q/4407/35864)?

I can compile the following MWE without error and only get a warning
```
Package biblatex Warning: Language 'latin' not supported.
(biblatex)                Using fallback language 'british' on input line 13.
```
```
\documentclass[latin,british]{article}
\usepackage[T1]{fontenc}
\usepackage[utf8]{inputenc}
\usepackage{babel}
\usepackage{csquotes}

\usepackage[style=authoryear, backend=biber]{biblatex}

\addbibresource{biblatex-examples.bib}

\begin{document}
\cite{sigfridsson}
\printbibliography
\end{document}
```

Even if Latin is the main language there is no error. But `cquotes`' quotation marks become question marks.

**Comment by johannesbottcher** [comment] 2019-02-17 05:52
Also posted on https://latex.org/forum/viewtopic.php?f=19&t=32249

**Comment by moewew** [comment] 2019-02-17 06:31
@johannesbottcher Thanks for the link.

@ExecutorElassus Your question on LaTeX community contains marginally more information than the query here, but even with those added bits I'm completely unable to reproduce an error.
```latex
% XeLaTeX
\documentclass{article}
\usepackage{polyglossia}
\setmainlanguage{english}
\setotherlanguage{latin}
\usepackage{csquotes}

\usepackage{biblatex-chicago}

\addbibresource{biblatex-examples.bib}

\begin{document}
\cite{sigfridsson}
\printbibliography
\end{document}
```
compiles fine for me as well.

We really need a way to reproduce the error you are getting. The best way to do that is to show us a minimal example document. See the links in my first comment.

Please also include as much of the `.log` and `.blg` files as you possibly can.

**Comment by ExecutorElassus** [comment] 2019-02-18 09:35
Thanks for your replies. As I said at the beginning, I'm writing the document with Lyx, so it might be that Lyx handles errors differently than straight latex/xetex. But I'm attaching two files (they will need to be in the same directory to run): a MWE .lyx file, and the .bib file it uses.

With biblatex/biber 3.12/2.12, compile fails. With 3.07/2.07, it runs. 

[biblatex test.zip](https://github.com/plk/biblatex/files/2874893/biblatex.test.zip)

**Comment by moewew** [comment] 2019-02-18 09:50
When I open this file on my LyX installation I get a pop-up containing the following message
> The module biblatex has been requested by this document but has not been found in the list of available modules.

If I ignore that message and press on to compile the first error message I receive is
```
! Package biblatex Error: Incompatible package 'natbib'.

See the biblatex package documentation for explanation.
Type  H <return>  for immediate help.
 ...                                              
                                                  
l.167 \blx@packageincompatibility
                                 
The 'natbib' package and biblatex are incompatible.
```
(The LyX dialog shows that slightly differently, but it was easier to copy and paste it like this.)
All other following LaTeX error messages are related to that issue. `biblatex` complains because `natbib` has already defined its commands.

I also get an error from Biber
```
ERROR - Cannot find 'logobib.bib'!
```
The `.zip` only contained `bookbib.bib`, but the document also requests `logobib.bib`.

As far as I can see none of this has to do with the language. It is solely caused by the `.lyx` file requesting `natbib` with
```
\cite_engine natbib
\cite_engine_type authoryear 
```
but then also loading `biblatex` in the preamble with
```
\usepackage[notes,natbib,backend=biber,autocite=plain,alldates=edtf,idemtracker=context,ibidtracker=context,dateabbrev=false,language=american]{biblatex-chicago}
\renewcommand{\citet}[1]{\autocite{#1}}
```

You need to tell LyX that you don't want it to load `natbib`. Unfortunately, I have very little experience with LyX and don't quite know how you could tell it to load `biblatex-chicago` instead of `biblatex` or `natbib`. But as far as I can see this is not at all a `biblatex` issue and certainly not one related to a missing `latin.lbx`.

The error message might be different now because we made the incompatibility error more aggressive (and useful) in https://github.com/plk/biblatex/pull/751. But the same document must have thrown structurally similar errors with an older version of `biblatex` as well.

**Comment by jspitz** [comment] 2019-02-18 10:09
The issue here seems to be that the OP uses the biblatex module that was provided  for basic biblatex usage before proper biblatex support was added with LyX 2.3.0. This module needs to be removed from the file. See https://wiki.lyx.org/BibTeX/Biblatex#toc2

**Comment by jspitz** [comment] 2019-02-18 10:23
As to loading biblatex-chicago, you can add to _Document > Settings > Local Layout_
`Provides biblatex 1`
Then you can load `biblatex-chicago` in the preamble manually.

For a full fledged support, where you could select biblatex-chicago from the list in _Document > Settings > Bibliography_ and have the extra citation commands of that package, someone would need to sit down and write a `biblatex-chicago.citeengine` analoguous to the `biblatex-natbib.citeengine` LyX already provides. Also some slight adaptations in the source would be necessary, bot those would be trivial.

**Comment by jspitz** [comment] 2019-02-18 10:36
@moewew while we are at it: are you, from the top of your head, aware of more packages that use a wrapper rather than being loaded from biblatex itself? I can add very quick basic support for loading them (rather than `biblatex`) in LyX via (f. ex.)
`Requires biblatex-chicago`
in `Document > Settings > Local Layout`, a layout or a module file.

**Comment by moewew** [comment] 2019-02-18 10:41
@jspitz At the moment I can only think of `biblatex-chicago`.

**Comment by ExecutorElassus** [comment] 2019-02-18 11:53
my apologies for the confusion with Lyx's new support for biblatex. Attached is a new .zip file (with the correct logobib.bib) modified according to jspitz and moewew's recommendations. Compile still fails with biblatex-3.12 and related biber.
[biblatex test.zip](https://github.com/plk/biblatex/files/2875450/biblatex.test.zip)

Or do I have something else set here incorrectly?

**Comment by moewew** [comment] 2019-02-18 12:00
The file compiles fine for me. There are no errors. I get a few warnings, but most of them are related to `biblatex-chicago` using older option names (nothing terrible).

Please upload the full `.log` and `.blg` files of your compilation run. If you get an error on compilation click <kbd>View Complete Log</kbd> in the *LaTeX Errors* window (otherwise go to *Document > LaTeX Log*). In the *LaTeX Log* window press the <kbd>Open Containing Directory</kbd> button on the bottom left and get the `.log` and `.blg` files there.

**Comment by ExecutorElassus** [comment] 2019-02-18 12:07
Hi moewew,

attached are both logs.
[logs.zip](https://github.com/plk/biblatex/files/2875487/logs.zip)

thanks for the help.

**Comment by moewew** [comment] 2019-02-18 12:17
There seems to be a syntax error in `cms-american.lbx`. Your `.log` has
```
cms-american.lbx 2016/06/01 v 3.4 biblatex localization
```
mine has
```
cms-american.lbx 2018/01/09 v 3.10 biblatex localization
```
So that suggests that the old version has an error that was fixed in the new version. `biblatex` got slightly more picky about syntax errors in `.lbx` files in version 3.11 (https://github.com/plk/biblatex/pull/702), so that might explain why you did not get an error with an older `biblatex` version.
Update your TeX distribution to make sure that all package versions match.

I'll note that it looks as though your system has several TeX installations. `biblatex` lives in
```
/usr/share/texmf-site/tex/latex/biblatex/
```
whereas `biblatex-chicago` lives in
``` 
/usr/share/texmf-dist/tex/latex/biblatex-chicago
```
Note the `texmf-site` vs `texmf-dist`.

**Comment by moewew** [comment] 2019-02-18 12:25
Mhhh, seems as though you only installed `biblatex` into `/usr/share/texmf-site/` everything else lives in `/usr/share/texmf-dist/` as is considerably older. It almost looks as though you only manually upgraded `biblatex` and left everything else in `TeX Live 2017` state. That is a really bad idea. Package/version incompatibilities like the one you have just observed get much more likely if you do that.

I strongly suggest you remove the manual update of `biblatex`. Either go back to TeX live 2017 completely or install a current TeX live (2018). But don't mix and match.

**Comment by jspitz** [comment] 2019-02-18 12:27
For the record: As to LyX, I have just committed the basic support to lyx-devel (2.3.4dev)

**Comment by ExecutorElassus** [comment] 2019-02-18 12:32
> I strongly suggest you remove the manual update of `biblatex`. Either go back to TeX live 2017 completely or install a current TeX live (2018). But don't mix and match.

This is, I think, a general problem with gentoo's handling of texlive, in that it is very out of date.

I have a "live" complete texlive installation residing elsewhere on the system. Should I just tell Lyx to use that one?

Cheers

**Comment by moewew** [comment] 2019-02-18 12:35
In this case the fact that gentoo doesn't ship the bleeding edge of LaTeX packages is not the main issue. It only becomes an issue once one starts manually updating stuff. Sure if you want to use new features you need new versions, but for many users the old versions are enough and the stability that the system gets from not updating all the time is very valuable.

If you want the bleeding edge, by all means point LyX to your up-to-date installation. Just make sure that there are no version mess-ups like this again.

**Comment by jspitz** [comment] 2019-02-18 12:36
You don't need to tell LyX specifically. You just need to set the environment variables properly (PATH, TEXMFCNF)

**Comment by jspitz** [comment] 2019-02-18 12:39
More specifically: Add to ~/.profile he following lines
```
export TEXMFCNF=/usr/local/texlive/2018/texmf/web2c:$TEXMFCNF
export PATH=/usr/local/texlive/2018/bin/x86_64-linux:$PATH
```
(adjust the paths as desired)

**Comment by ExecutorElassus** [comment] 2019-02-18 12:46
> More specifically: Add to ~/.profile the following lines
> 
> ```
> export TEXMFCNF=/usr/local/texlive/2018/texmf/web2c:$TEXMFCNF
> export PATH=/usr/local/texlive/2018/bin/x86_64-linux:$PATH
> ```
> (adjust the paths as desired)

Thank you, this solved the issue for me. I'm now using my local texlive, updated from upstream directly, rather than gentoo's texlive (which was causing other issues as well that are fortunately now also resolved).
Thanks for the help, and apologies for the trouble.

**Comment by moewew** [comment] 2019-02-19 16:24
Since the problem seems to be solved and there is nothing to do on the `biblatex` side, I'm closing this issue.

For future issues please keep the following in mind (in no particular order).
1. This is the `biblatex` issue tracker for **bug reports and feature requests**. We can't really offer user support.  For support questions you are probably better off asking over at https://latex.org/, https://tex.stackexchange.com/, https://groups.google.com/forum/#!forum/comp.text.tex or on one of the many other TeX support/help forums.
   - Of course it is not always easy to determine beforehand if the issue you are facing is more of a support issue or a bug in the software. Furthermore, I'd much rather have a few false positives reported here than having real bugs go unnoticed because they are only discussed in forums and never brought up here. So if there are doubts I have no problems with erring on the side of reporting here. I also appreciate that in this particular case the symptoms are consistent with this being a `biblatex` issue and one could even argue this is a `biblatex` bug<sup>After all `biblatex` used to be more lenient with malformed `.lbx` files.</sup>, so please don't see this as a personal attack/criticism.
2. Please **include a minimal working example** reproducing the undesirable behaviour right from the start. Even if you think the issue would be easy to reproduce just from a short description of the problem it is *much, much* easier to investigate issues if we can be sure that we are all talking about the same thing. Often it is quite impossible to even think about what might be causing the issue if one has not seen the relevant code (see my first comment).
    -  Ideally the working example would consist of only one `.tex` file and if necessary a short `.bib` file with relevant example entries. In case the exact entries are not relevant, please consider using `biblatex-examples.bib`, which is installed on all systems with `biblatex`.
    - If you are using LyX it might be a bit harder to construct a minimal working example. But it should be possible. If possible export the document as `.tex`, verify that that reproduces the issue and use that. If that is not possible, try to make the `.lyx` file as light as possible.
3. **Make sure that the example *really* reproduces the issue.** Ideally you verify that on an independent system (be aware of possible version differences between systems; for example it was once extremely useful to test examples on Overleaf, but currently their `biblatex`/Biber version is quite a bit behind the actual release version, so that tests with their system are not necessarily representative of the current state). But at the very least try the example in an empty folder before you submit it.
4. **Make sure the example is as minimal as possible.** Remove as much excess code as you possibly can.
    - On that note, please try and reproduce the issue with `biblatex` standard styles. Contributed styles are not maintained by us and issues with those should be reported to the relevant maintainers. Often it is possible to just replace your current style with a remotely similar standard style while still reproducing the issue. As above it may not always be easy to see whether an issue is a core `biblatex` bug or a problem in a contributed style, so again I'd rather err on the side of over-reporting here than having stuff go unnoticed.
5. If possible **test your example with the current version** of *all* packages involved. Maybe the issue has already been resolved. It may not always be possible to test things with the newest version, in that case clearly state the version you are talking about.
6. Please **include precise error and warning messages** in your initial report. Remember that the first error message is often the most important one in TeX, subsequent errors might just be knock-on effects. In case there are many messages or you don't known what is relevant, err on the side of including 'too much' information and include the entire `.log` and `.blg` files. (But please make sure your example is as minimal as possible, otherwise the `.log` files can get unwieldy quickly.)
7. **Describe the undesirable (and desired) behaviour precisely.** This is not so relevant with errors, where it is quite clear what the undesirable behaviour is (the error) and what the behaviour should be instead (the error should go away), but it becomes very important in other contexts. It is always helpful to include a description of the status quo as well as a description of what you would want to see instead.
8. **If you report, discuss or inquire about the issue elsewhere as well, please include links to the relevant places *on all sides*.** It would be frustrating to have effort unnecessarily duplicated when people at one end work on an issue that has already been solved at the other end. It is also helpful for people with a similar problem to be directed to other places where it has been discussed, especially if there is no other response at one of the places. (It didn't happen here, so I only mention it in parentheses, but I would consider it extremely rude to report an issue to several developers without disclosing that fact and including links to the other reports.)

**Closed by moewew** 2019-02-19 16:24 UTC
Labels: invalid
