### ISSUE TITLE
Sort Bibliography Entries by Number of Citations

### ISSUE THREAD

**Issue by dollodart** [plk/biblatex#1146] opened 2021-05-27 03:43 UTC
This is following up with a request for the feature asked about in this [TeX SE question](https://tex.stackexchange.com/questions/362294/using-citecounter-for-sorting-in-biblatex). Often one wants to list bibliography entries in order of importance and probably the best definition of importance is the number of times an entry was cited.

This issue is also related to Issue #1138 for the general question of "how can I dynamically add biblography entry data with in-document LaTeX data". One way to do this is to make an auxillary file like was given in an answer to the question on TeX SE. That was also what I suggested in Issue #1138 in analogy to backref and pageref. However, that is an abuse of the .aux file because updating the bibliography entry data with static data instead of a page reference doesn't require the document to be compiled. Another way to do this would be to declare a Sourcemapping, but since the command is limited to the preamble, it doesn't have access to the in-document data when it writes the maps to the .bcf file. But the `entrytarget` option used to set fields on dynamically created entries could be used to add arbitrary data for each entry type using the existing Sourcemap options (see below).

The default sorting behavior of biber, based on citation order, is achieved by writing to the .bcf file the entry key with `\blx@xml@citekey` which puts an `order` attribute in the `bcf:citekey` element. Citation count could be put as another attribute in `bcf:citekey` elements, but this would require changing biber to use that attribute. In general, it is desired to dynamically update the fields for entries with in-document data. It might be possible to declare a `SaveData` macro to be used like this in, e.g., a cite command:

```
\DeclareCiteCommand{\mycite}
{\usebibmacro{prenote}}
{\usebibmacro{mycite}}
{\multicitedelim}
{\usebibmacro{postnote}
\SaveData{\thefield{entrykey}}{citecount}{\arabic{citecounter}}
```

The `\SaveData` would write something like the below to the .bcf file:

```
<bcf:map>
  <bcf:map_step map_entry_target="|entrykey|" map_field_set="citecount" map_field_value="|citecounter|"/>
</bcf:map>
```

Here `\SaveData` would be like the following inside a `\DeclareSourcemapping{\maps{...}}`

```
\map{\step[fieldset={citecount},fieldvalue={|citecounter|},entrytarget={|entrykey|}}
```

Since this would be executed at each `\mycite`, this would save an element to the .bcf file at each citation (assuming an `\immediate\write`). Since there's no way for the cite command to know if it is the last one, biber should just discard all but the last written data or overwrite with the last known step, the latter of which is already the behavior.

Can Sourcemap declarations be allowed throughout the document body and the .bcf file be written at end of document in order to let one dynamically add bibliography entry data with in-document LaTeX data? Or is there another solution, e.g., write to a different file that is not an auxillary file but will be read by biber?

**Comment by plk** [comment] 2021-06-03 21:25
`biber` already keeps track of how many times any key is cited in a given section - it's just that this counter isn't currently used for anything and so adding a sorting option for number of citations should be possible - I will look into it.

**Comment by plk** [comment] 2021-06-03 23:20
A new sorting option `\citecount` is now available for sorting templates in DEV 3.17 and also a new default sorting template `sorting=count` which uses this. This requires `biber` 2.17 DEV. Both are on SourceForge in development folder.

**Comment by moewew** [comment] 2021-06-04 06:22
Going purely by cite requests in the `.bcf` will unfortunately lead to weird results in some cases.

For example `\textcite` is implemented as a two-pass command in some styles, so in those styles `\textcite`s will be counted double. See the following example, where `worman` should be sorted last because it has only 2 real citations, but it sorted in the middle, because it has four cite requests.
```latex
\documentclass[british]{article}
\usepackage[T1]{fontenc}
\usepackage{babel}
\usepackage{csquotes}

\usepackage[backend=biber, style=authoryear-icomp, sorting=count, citecounter]{biblatex}

\renewbibmacro*{finentry}{\printtext{Cited~\arabic{citecounter} times}\finentry}

\addbibresource{biblatex-examples.bib}

\begin{document}
Lorem \parencite{sigfridsson}
Lorem \parencite{sigfridsson}
Lorem \parencite{sigfridsson}
Lorem \parencite{sigfridsson}
Lorem \parencite{sigfridsson}

ipsum \cite{nussbaum}
ipsum \cite{nussbaum}
ipsum \cite{nussbaum}

dolor \textcite{worman}
dolor \textcite{worman}

\printbibliography
\end{document}
```

Indeed the existing `citecounter` feature is implemented completely on the LaTeX/`biblatex` side of things and is even context dependent (text body/footnote). Its counting can be suspended locally, so that it yields the expected results in the example. (Suspending the counter locally also helps with commands like `\citeauthor` which we may not want to count as a normal citation.) I think (but I would have to verify that) that for commands like `\textcite` the cite counter is suspended *after* the citation request is written to the `.bcf`, so it might be too late at that point for Biber to react.

**Comment by plk** [comment] 2021-06-04 07:23
Hmm, I didn't look too deeply into the conditions under which the .bcf was written. I wonder if we could force a .bcf write under the same conditions as that which sets `citecounter`?

**Comment by plk** [comment] 2021-06-04 09:07
This is complicated by re-runs - if you just do `latex->biber->latex->latex`, it's correct in the above example. It's only when you run `biber` again that the `.bcf` is then incorrect, presumably due the `.aux` contents.

**Comment by moewew** [comment] 2021-06-04 10:45
Ah, yeah. That is also the two-pass structure.

----

I think this is going to be tricky. The code is set up in such a way that the cite request is written out way before the actual code of the cite command does its thing. In particular the cite request is always written out, while the cite command code is only executed if the actual entry is available (that's why on a first LaTeX run the number of citation requests in the `.bcf` are as expected, the two-pass structure can only be executed once the data is there).

For those interested in the details, the relevant macro here is `\blx@citeloop`

https://github.com/plk/biblatex/blob/400ddec33343b3e33d57d90a4555a0e5197735b5/tex/latex/biblatex/biblatex.sty#L11140-L11175

The cite requests are written to the `.bcf` by `\forcsvlist\blx@citeadd{#1}` (l. 11159), the actual cite code is executed (for all entries whose data is available!) in `\forlistloop\blx@citeprint` at the end of the macro definition. The citation tracker is traditionally disabled in the precode, which only comes into play in `\blx@citeprint`.

**Comment by moewew** [comment] 2021-06-04 15:09
I'd have thought our best chance would be to calculate the number of citations on the LaTeX side and write it to the `.bcf` file (in a separate bit of the `.bcf`). That would require several LaTeX, Biber, LaTeX, LaTeX, Biber, LaTeX cycles though, since (as seen above) we only know the number of citations properly after the Biber run (depending on when we write the counters to the `.bcf` we might need an additional LaTeX run after that). That would be the simplest solution in the sense that we could just bolt on this solution to the existing framework. But of course it feels a bit meh what with it needing several Biber runs to converge.

**Comment by plk** [comment] 2021-06-04 20:50
I really don't want to require more than one `biber` run - that opens whole new arena of misery. To be clear - does all this means that we always need two latex runs before `biber` to get this right as we need to use the `.aux` information before we get to `biber`? If it's always correct in the `.bcf` as far as number of '<bcf:citekey>' elements after one `biber` run, is there a real problem here as we never run `biber` twice anyway. Or, we modify the `.aux` macros so that they don't result in a different `.bcf` on the second `latex` run?

**Comment by moewew** [comment] 2021-06-05 06:01
If we write the info to the `.bcf` at the end we probably won't need several LaTeX runs. But I can't think of a solution in the current framework that does not require several Biber runs.

The number of citations in the first `.bcf` is only correct in the example because the two-pass structure of `\textcite` can only come out after the Biber run. Subsequent Biber runs will have the additional calls in the `.bcf`. We cannot rely on Biber only being run once, because the normal modus operandi for working on a document is to recompile it with LaTeX and Biber as required without cleaning the auxiliary files. Plus, `\textcite` is not the only command that causes trouble here. `\citeauthor` would be another example: It writes a cite request to the `.bcf`, but is not counted for the citecounter. Leading to the following wrong sort order
```latex
\documentclass[british]{article}
\usepackage[T1]{fontenc}
\usepackage{babel}
\usepackage{csquotes}

\usepackage[backend=biber, style=authoryear-icomp, sorting=count, citecounter]{biblatex}

\renewbibmacro*{finentry}{\printtext{Cited~\arabic{citecounter} times}\finentry}

\addbibresource{biblatex-examples.bib}

\begin{document}
Lorem \parencite{sigfridsson}
Lorem \parencite{sigfridsson}
Lorem \parencite{sigfridsson}
Lorem \parencite{sigfridsson}
Lorem \parencite{sigfridsson}

ipsum \cite{nussbaum}
ipsum \cite{nussbaum}
ipsum \cite{nussbaum}

dolor \textcite{worman}
dolor \textcite{worman}

sit \parencite{geer}
sit \citeauthor{geer}
sit \citeauthor{geer}
sit \citeauthor{geer}
sit \citeauthor{geer}
sit \citeauthor{geer}
sit \citeauthor{geer}
sit \citeauthor{geer}
sit \citeauthor{geer}

\printbibliography
\end{document}
```

**Comment by plk** [comment] 2021-06-05 15:00
I am currently wondering if we shouldn't anyway suppress writing a citekey element to the .bcf for commands which are not really a citation like `\citeauthor` and `\citetitle`? This will help a bit in general. If there was a `\citeauthor` for a key but no other citation of the key, the entry shouldn't be in the bibliography.

**Comment by moewew** [comment] 2021-06-05 19:06
But then it wouldn't be possible to `\citeauthor` an entry that wasn't cited with a 'real' cite command, because the data wouldn't be present in the `.bbl` file. This might be problematic. I must admit that my general feeling would be that this is a rare case and if `\citeauthor` were a new feature I might be persuaded to agree that this is sensible behaviour, but since currently `\citeauthor` issues a cite request I fear this might break people's documents.

I should also say that while `\citeauthor` and `\textcite` are cases where we have a fairly strong intuition as to what would be the expected behaviour this need not be the case for (other) user-defined commands. It is entirely conceivable that someone wants a 'real' cite command that is not counted by citecounter for some reason. Such a command would be tricky to pull off if 'real' cite commands write cite requests to the `.bcf` and 'ancillary commands' like `\citeauthor` don't.

On the technical side of things `\citeauthor` and bona fide cite commands like `\cite` are implemented in exactly the same way with `\DeclareCiteCommand`. The only thing that distinguishes them is the fact that `\citeauthor` turns off tracking in the prenote with `\boolfalse{citetracker}`/`\citetrackerfalse`. At least in the current implementation the cite request will already have been written out when we reach the prenote code and the`\boolfalse{citetracker}`/`\citetrackerfalse`.

**Comment by plk** [comment] 2021-06-05 20:42
I am thinking that we need to do something like this:

- Stop writing out citekeys to `.bcf` synchronously. Save them instead in a list of some sort that can be processed and output at section end. We already do this for citekey aliases. This fixes the timing issues
- Move .bcf xml code output into this new list out of `\blx@bibreq` and onto the end of the prenote phase of citations declared with `\DeclareCiteCommand` so that the .bcf output can be conditionalised on the citetracker booleans/flags
- Look at how to stop the `.aux` commands generated by the post `biber` run from creating a difference `.bcf`

**Comment by moewew** [comment] 2021-06-06 07:01
Hmmm, I'm not sure if that would help a lot. The prenote code is only executed if data is present in the `.bbl` file and that is only true after a Biber run. So we always need a Biber run to get to that point.

Of course we could do a two-way system: Write the cite request to the `.bcf` unconditionally if the data isn't there. Write it to the `.bcf` later (in the prenote step) if the data is there. But that could then also require several Biber runs if the `.bcf` changes.

----

Here's what I would try to do.

Couple the new sorting method to the `citecounter` option (i.e. `\citecount` works only with `citecounter` enabled).
1. Let LaTeX run as normal and collect all cite request in the `.bcf`.
2. Run Biber, Biber doesn't sort at all in this run, it just gives us the data.
3. In the next LaTeX run we can resolve all citations and count all citations. At the end of the run we know the cite counter for each entry. Write that to the `.bcf`.
4. Run Biber again, this time Biber can sort by cite counter.
5. LaTeX again, everything is fine.

I agree that having to run Biber multiple times is a bit meh, but if we couple this to an advanced option people are sort of warned. Users who don't use the option will never get into trouble with Biber rerun, because everything will remain as is without the option.

**Comment by plk** [comment] 2021-06-06 19:47
Ah yes, I hadn't quite realised that the prenote assumed data ...
Then I think we have no choice and need an extra `biber` run - I have implemented this in the dev branches and it seems to give the right results now after an extra `biber` and `latex` run. The counter `biber` uses for `\citecount` sort is now the value of the (global) `biblatex` `citecounter` value and so is sensitive to the mechanisms which disable it locally for things like `\citeauthor`.

**Comment by moewew** [comment] 2021-06-06 20:01
Sounds good. I won't have time to look at this closer tonight, but will hopefully get to it during the week.

**Comment by moewew** [comment] 2021-06-20 13:02
https://github.com/plk/biblatex/commit/983b4402c22c68412c85beca95ee644b8c37a95b implements rerun detection for `.bcf` changes, so that users should hopefully always get the expected result.

---

@plk While I was playing around with this I noticed that entries with citecount 0 (which is unusual, but certainly possible) sort before all other entries.

See
```latex
\documentclass[british]{article}
\usepackage[T1]{fontenc}
\usepackage{babel}
\usepackage{csquotes}

\usepackage[backend=biber, style=authoryear-icomp,
 sorting=count, citecounter
]{biblatex}

\renewbibmacro*{finentry}{\printtext{Cited~\arabic{citecounter} times}\finentry}

\addbibresource{biblatex-examples.bib}

\begin{document}
ipsum \cite{nussbaum}
ipsum \cite{nussbaum}
ipsum \cite{nussbaum}

dolor \textcite{worman}
dolor \textcite{worman}

Lorem \parencite{sigfridsson}
Lorem \parencite{sigfridsson}
Lorem \parencite{sigfridsson}
Lorem \parencite{sigfridsson}
Lorem \parencite{sigfridsson}

sit \citeauthor{geer}
sit \citeauthor{geer}
sit \citeauthor{geer}
sit \citeauthor{geer}
sit \citeauthor{geer}
sit \citeauthor{geer}

\printbibliography
\end{document} 
```
I'd have expected `geer` with 0 citations to sort last.

**Comment by plk** [comment] 2021-06-20 21:20
Should be fixed in DEV biber

**Comment by moewew** [comment] 2021-06-21 06:25
Thank you very much. Things sort correctly now.

But now I'm curious, why do you have to force `-1` for cite count 0?

**Comment by plk** [comment] 2021-06-21 09:05
It's due to the rather delicate logic for the sorting dispatch routines. `if(0)` is always false but `if(-1)` isn't - the logic for sorting data structure building needs clear lines between empty data, data that is an empty string, data that is 0 etc. There are enough of these potentially conflicting cases that it's better to ensure clear data passing into the sorting data structures than messy conditionals trying to cover every case. This has caused all sorts of edge case bugs in the past.

**Closed** 2022-02-08 06:54 UTC
Labels: enhancement
