### ISSUE TITLE
Enhance uniquename feature

### ISSUE THREAD

**Issue by moewew** [plk/biblatex#623] opened 2017-09-08 15:11 UTC
`biblatex` already offers `\DeclareUniquenameTemplate` to customise the `uniquename` feature for use with the extended name format. It is, however, currently not possible to know *which* name part triggers the disambiguation. The only thing we get to know is the `uniquename` counter.

In the following MWE the `uniquename` counter is 1 for all names, yet the name part that makes the difference is different.

```
\documentclass{article}
\usepackage{filecontents}

\begin{filecontents*}{\jobname.bib}
@book{Book1,
  author = {Elk, Junior, Anne},
  date = {2011},
  title = {Foo},
}
@book{Book2,
  author = {Elk, Senior, Anne},
  date = {2011},
  title = {Foo},
}
@book{Book3,
  author = {Belk, Amanda},
  date = {2011},
  title = {Foo},
}
@book{Book4,
  author = {Belk, Bamanda},
  date = {2011},
  title = {Foo},
}
\end{filecontents*}

\usepackage[style=authoryear,backend=biber]{biblatex}
\addbibresource{\jobname.bib}

\DeclareUniquenameTemplate{
  \namepart[use=true, base=true]{prefix}
  \namepart[base=true]{family}
  \namepart{given}
  \namepart{suffix}
}

\begin{document}
    \cite{Book1,Book2}

    \cite{Book3,Book4}

    \printbibliography
\end{document}
```

I have no idea at the moment how Biber could pass the info over to `biblatex` in a usable way, but I thought I would open this ticket for discussion and to collect ideas.

**Comment by plk** [comment] 2017-09-08 15:16
Off the top of my head, I am fairly sure that`biber` has this information easily available. The first question though is, can you think of a use case for this? Why would anyone want to know what disambiguated a name? As I remember from the code, the only potential confusion is that when further disambiguation happens (full name instead of initial for example) and that makes no difference, then it falls back to a less specific `uniquename` value.

**Comment by moewew** [comment] 2017-09-08 15:21
It came up in https://tex.stackexchange.com/q/390369/

In the related https://tex.stackexchange.com/a/390393/ I added a new name part `cjk` for the CJK version of the name. So a eastern name would have `family`, `given` (transliterated) and a `cjk` part.

The idea now is to disambiguate names as follows

`family` > `family`+`given` > `family`+`given`+`cjk`

without initials.

In that case I would need to know if `given` already makes things unique or whether I need to add `cjk`.

**Comment by plk** [comment] 2017-09-08 15:29
This is hard - we would need to expand the `uniquenames` package option and also the return values for the `uniquename` counter. I agree it is worth doing though.

**Comment by plk** [comment] 2017-09-08 15:30
Currently we have hard-coded the idea of initials and fullnames which correspond to the firstname only.

**Comment by moewew** [comment] 2017-09-08 15:35
Yes `\DeclareUniquenameTemplate` was a good first step to open `uniquename` to the extended name format, but most of it still comes from a time when we only had BibTeX names.

We probably need to overhaul the entire thing. Instead of a counter we could give back the first name part in `\DeclareUniquenameTemplate` that makes the name unique. Ideally it would be possible to control whether or not to consider initials.

**Comment by plk** [comment] 2017-09-08 15:47
The first thing is to decide on the adequacy of the `uniquename` package option. I think that this is already aware of the new system as "initials" and "full name" mentioned in the option documentation does indeed now take account of every defined name part from `\DeclareUniquenameTemplate` and so perhaps it is mostly a case of the return from the `uniquename` counter?

**Comment by moewew** [comment] 2017-09-08 15:51
Yes and maybe more fine grained control over initials in `\DeclareUniquenameTemplate`. So that one can ask to disambiguate a certain name part by initials only and another one by initials or in full.

**Comment by plk** [comment] 2017-09-09 22:31
I will look at that first. Do you have any sense of how such per-namepart disambiguation scope (none, inits, full) would interact with the global `uniquename` option? Should they override the global option? It is not clear to me which should be given priority. For example, at the moment, if `uniquename=init`, then this overrides the implicit full namepart disambiguation of `\DeclareUniquenameTemplate`. If this latter is extended to allow per-namepart disambiguation scope choice for particular nameparts, and we set one namepart to "init" - does a global `uniquename=full` override this or vice-versa?

**Comment by moewew** [comment] 2017-09-10 10:43
Mhhh, I'm not sure.

Maybe we can add a switch to the declarations in `\DeclareUniquenameTemplate` that either keeps the global default set by the option, or overrides it explicitly.

**Comment by plk** [comment] 2017-09-10 10:45
I think the global should just set the default for every namepart if not otherwise specified. However, I've looked into this and I think it would be a major overhaul to do even the fine-grained initials control. The problem is that currently, the information we pass in the .bbl only says that a name as a whole needs to print the initial or full name etc. We would need a new .bbl format to allow passing information about the disambiguation of individual name parts and then biblatex changes to deal with this information in name formats. It also means quite complex changes in the most complicated part of `biber` - the loop that deals with `uniquename`/`uniquelist` interaction.

**Comment by moewew** [comment] 2017-09-10 10:48
Ah well. Is there anything less invasive that could be done?

**Comment by plk** [comment] 2017-09-10 10:51
I'm still investigating whether this is manageable ...

**Comment by plk** [comment] 2017-09-10 17:52
This is very hard to do - first I'd like to be convinced that per-namepart `uniquename` is really important. Can you perhaps speak to this? I can't imagine many (any?) styles would need some parts disambiguated by full name and other parts only by initials?

**Comment by moewew** [comment] 2017-09-11 09:36
I'm not too fussed about a possibility to control the initial/full setting per namepart. I think it would be nice to have, but I have no idea about the feasibility on Biber's side. I have no good concrete examples in mind.

**Comment by plk** [comment] 2017-09-17 20:58
Some progress on this - I have a biber branch with considerable changes which passes all tests. It tracks `uniquename` disambiguation in much more detail, recording which namepart disambiguates and at at which level (inits/full). It also supports the level per-namepart. Currently this information is not used. Next step is to decide on a `.bbl` format to pass this through and then look at the `biblatex` aspects of this.

**Comment by moewew** [comment] 2017-09-19 12:07
That sounds good. At the moment I have no real intuition what the interface for Biber should look like.

Since this feature can only really be used with `\DeclareUniquenameTemplate` the output format can be very basic. (Just give the name part and the required level.) The developer/user will have to code the name formats to make use of the new feature in accordance to their `\DeclareUniquenameTemplate`.

I think it is important that backwards compatibility is ensured for `uniquename`. A few custom styles use the counter directly.
My idea was that we would not touch the output of `uniquename` in the `.bbl` and add another `extendeduniquename` (?) that offers the new interface. We could then use the new field in the standard styles, but would not make custom styles unusable immediately.

Another idea is to take the current format of `uniquename` and extend it.
```
\DeclareUniquenameTemplate{
  \namepart[use=true, base=true]{prefix}
  \namepart[base=true]{family}
  \namepart{given}
}
```
To that end number all non-`base=true` name parts in `\DeclareUniquenameTemplate` from 1 to n.
Output 0 if `base=true`-names are enough to disambiguate a name.
Output 2n-1 if non-`base=true` namepart n disambiguates with initials.
Output 2n if non-`base=true` namepart n didambiguates in full.

This approach is fully backwards-compatible.
But it does not take into account "mixed" disambiguation (part 1 in full, part 2 with inits), I'm not sure if Biber supports that.

**Comment by plk** [comment] 2017-09-19 12:13
Yes, I will leave the normal `uniquename` counter alone. I am thinking about adding `uniquename` information per namepart with a `un` suffix which should cover the requirements:

```
           family={AAA},
           familyi={A\\bibinitperiod},
           familyun={0}}}%
           familyi={A\\bibinitperiod}}}%
```

**Comment by moewew** [comment] 2017-09-19 12:20
As long as it is easily accessible in `\DeclareNameFormat` I'm fine with anything.

**Comment by plk** [comment] 2017-09-21 22:07
Can you look at the "un" branches of both biblatex and biber (or the latest 3.8/2.8 Sourceforge uploads)? There is now an enhanced .bbl format which contains information about the `namepart` which caused `uniquename` disambiguation (`uniquenamepart` key at name level) along with `uniquename` values for each `namepart` (`<namepart>un`). The uniquename settings at the name level is also still present for backwards compat. biblatex itself does nothing with this new information at the moment, it merely recognises it internally. See if you think that this information will be sufficient for what we need. `\DeclareUniquenameTemplate` now supports a new `context` attribute per `namepart` which overrides the implied full/init level of the global `uniquename` setting on a per-namepart basis.

**Comment by moewew** [comment] 2017-09-22 07:04
Thank you very much for your effort. Just tested this and I can do everything I want now.

Would it be possible to offer `context=fullonly` so that initials are not used for disambiguation? Of course the same effect can be obtained by changing the name format to not distinguish between `un=1` and `un=2`, but it might be nice to have one switch for that. If it can be implemented easily, that is.

Is there any rule that explains how the `un` of nameparts that were not enough to disambiguate is filled?
With
```
\DeclareUniquenameTemplate{
  \namepart[use=true, base=true]{prefix}
  \namepart[base=true]{family}
  \namepart{given}
  \namepart{cjk}
}
```
I got
```
      \name{author}{1}{}{%
        {{uniquename=1,uniquepart=cjk,hash=137db319fcba905b93146b1eb53decd1}{%
           family={Zhang},
           familyi={Z\bibinitperiod},
           given={Xuecheng},
           giveni={X\bibinitperiod},
           givenun=1,
           cjk={張學成},
           cjki={張\bibinitperiod},
           cjkun=1}}%
      }

      \name{author}{1}{}{%
        {{uniquename=1,uniquepart=cjk,hash=7590e773972833a2e409409600c23dd2}{%
           family={Zhang},
           familyi={Z\bibinitperiod},
           given={Xuecheng},
           giveni={X\bibinitperiod},
           givenun=1,
           cjk={章學成},
           cjki={章\bibinitperiod},
           cjkun=1}}%
      }


      \name{author}{1}{}{%
        {{uniquename=2,uniquepart=cjk,hash=853b00329ae5c21f3c665aa7ef497c98}{%
           family={Willard},
           familyi={W\bibinitperiod},
           given={Xuecheng},
           giveni={X\bibinitperiod},
           givenun=1,
           cjk={Flobbel},
           cjki={F\bibinitperiod},
           cjkun=2}}%
      }

      \name{author}{1}{}{%
        {{uniquename=2,uniquepart=cjk,hash=81dba3697200e4efa99cbfd1476cbf12}{%
           family={Willard},
           familyi={W\bibinitperiod},
           given={Xuecheng},
           giveni={X\bibinitperiod},
           givenun=1,
           cjk={Fnorm},
           cjki={F\bibinitperiod},
           cjkun=2}}%
      }
```
So it seems they are just set to init, i.e. the minimal setting that makes everything unique.

**Comment by plk** [comment] 2017-09-22 08:00
That is still an open question about the `un` setting for the parts that did not disambiguate. We have never had to deal with that before really. I am open to suggestions. I suppose it should be 1 if `uniquename/context`=init* or 2 if `uniquename/context`=2? I'll look into the `contextfull` option.

**Comment by moewew** [comment] 2017-09-22 08:09
Frankly, I don't think it matters really which way we choose as long as it is consistent (and documented). I think it makes sense to take the `un` value of the disambiguating name part (in my example from above that would mean 1 for the first two and 2 for the last two entries), but I could easily live with something else.

**Comment by plk** [comment] 2017-09-22 09:41
I wonder if we can set the non-disambiguating parts to 0 to give the style choice about what to do with them? The reason I set them to 1 was because they have to be at least initials and since they don't disambiguate, it's best to give them the minimal form.

**Comment by moewew** [comment] 2017-09-22 09:52
Since the styles have to decide what to do with the values anyway that would also be possible. I personally would only expect 0 for the nameparts after the disambiguating namepart (i.e. the nameparts I definitely don't need to print for uniqueness), but my view is influenced by the one particular application I have in mind, the fact that I think that 0 means 'don't print this name part' and the fact that intuitively I will probably always print all name parts before the disambiguating part.

**Comment by plk** [comment] 2017-09-22 09:56
Good point although 0 really means "no disambiguation needed or disambiguation to the maximum level does not disambiguate". What about then having initials only for parts before the disambiguating part and 0 afterwards?

**Comment by moewew** [comment] 2017-09-22 10:10
Ah, I forgot about the 'does not disambiguate' bit.

Initials only would also be OK, although in my head the procedure checks if a namepart disambiguates with initials and if not expands it to full and checks again, if not it goes on to the next namepart. In this procedure nameparts before the disambiguating part are left in full because the are not touched again.
So I would intuitively use full/2. But again my intuition is only led by that one application I have in mind, I don't really know other 'name schemes' well enough to have any insight into what could be actually useful.

**Comment by plk** [comment] 2017-09-22 11:57
I was thinking that the `un` value would be a guide of what to print for a name which is disambiguated only to the minimum required. So if you wanted 2 for all parts in your example, then this would be achieved by `context=fullonly` i n the template?

**Comment by moewew** [comment] 2017-09-22 12:06
As I said, my intuitions are very much guided by that one application I had in mind. Especially if `fullonly` is available I can live with any logical thing you come up with.

I might add that with
```
\DeclareUniquenameTemplate{
  \namepart[use=true, base=true]{prefix}
  \namepart[base=true]{family}
  \namepart{given}
  \namepart{suffix}
}
```
> B. Crouch, Jr. and B. Crouch, Sr.

looks a bit odd to me and I would prefer
> Bartemius Crouch, Jr. and Bartemius  Crouch, Sr.

But there is probably a system where the extended `\DeclareUniquenameTemplate` really makes sense and a minimal disambiguation is preferred.

**Comment by moewew** [comment] 2017-09-22 14:54
Here is something new. I thought I would give https://tex.stackexchange.com/q/313176/35864 a spin with the enhanced uniquename feature. I noticed that it would be extremely handy to be able to define separate `\DeclareUniquenameTemplate`s for each `sortnamekeyscheme`. I'm not sure if that is possible, but since different sorting is possible in the form of `\DeclareSortingNamekeyScheme` I though it might be worth to ask.

The same basically holds for `\DeclareLabelalphaNameTemplate`.

**Comment by plk** [comment] 2017-09-23 21:08
Actually it's very useful because what I have seen is that with the usage constantly growing, such requests are pre-emptive of things that are requested eventually anyway.

**Comment by plk** [comment] 2017-09-23 21:30
I have implemented `fullonly` as a `context` value in `\DeclareUniquenameTemplate` - this will force full names despite initials being enough to disambiguate. Perhaps you can test it?

**Comment by moewew** [comment] 2017-09-23 22:02
> Do you think it would be enough to select a `uniquenametemplate` based on the `sortnamekeyscheme` and if a specific template exists for this to use it and if there isn't one, fall back on the global `uniquenametemplate`?

Yes, that would do it, I think (although it's really late and I'm not sure if I have thought this through). The `sortnamekeyscheme` option could then essentially become a `name(key)scheme` (meta-)option as it controls sorting (`\DeclareSortingNamekeyScheme`), uniquename (`\DeclareUniquenameTemplate`) and labelalphaname (`\DeclareLabelalphaNameTemplate`) generation. Of course there is always the possibility that a user may want to do something even more exotic and may want to control each of the three separately.

I'll ponder this a bit more tomorrow and will get back to you with tests of the new `fullonly` option.

**Comment by moewew** [comment] 2017-09-24 08:35
Did some tests with `fullonly` and things work as expected.

As I said above I'm not too excited about the 0 for name parts before the disambiguating one
```
      \name{author}{1}{}{%
        {{uniquename=2,uniquepart=cjk,hash=137db319fcba905b93146b1eb53decd1}{%
           family={Zhang},
           familyi={Z\bibinitperiod},
           given={Xuecheng},
           giveni={X\bibinitperiod},
           givenun=0,
           cjk={張學成},
           cjki={張\bibinitperiod},
           cjkun=2}}%
      }
```
I'd have preferred `2` for `givenun=0,` here. But I can accept your point that `0` may also mean 'was not enough to disambiguate' (a new value for that would be nice for at least the `...un` feature, so we can distinguish the two very different meanings of `0`).

Quite a few things in `biblatex` are called `context` (`refcontext`, `delimcontext`) already, so maybe we could rename the option to `mode`, `expansion`, `detail` or another more fitting name.

**Comment by plk** [comment] 2017-09-24 09:02
Do you have a MWE for that example? I'm not sure why you are getting `given=0` there before the `cjk` part because if no expansion disambiguates a part before the disambiguating part, it should revert to `1` because that's the minimal information that needs to be printed. If you want `2`, you can then set `fullonly` on any parts preceding the disambiguating part.

I have renamed `context` to `disambiguation` to make it explicit since that's the term used in all docs about uniquename (will upload later when we've sorted these other things out).

**Comment by moewew** [comment] 2017-09-24 09:36
Not entirely minimal, sorry. But you can see what's going on
```
\documentclass{article}
\usepackage[fallback]{xeCJK}
\usepackage{xunicode-addon}
\setmainfont[Ligatures={Common, TeX}]{Times New Roman}
\setCJKmainfont[Scale=1]{SimSun}

\usepackage{filecontents}
\begin{filecontents*}{\jobname.dbx}
\ProvidesFile{chicago-authordate.dbx}[2016/07/24 extended name format for biblatex]
\DeclareDatamodelConstant[type=list]{nameparts}{prefix,family,suffix,given,cjk}
\end{filecontents*}
\begin{filecontents*}{\jobname.bib}
@book{Book1,
title = {Shuming},
titleaddon = {書名},
author = {family=Zhang, cjk=章學成, given=Xuecheng},
location = {Beijing},
publisher = {Zhonghua Shuju},
date = {2017},
}
@book{Book2,
title = {Shuming er},
titleaddon = {書名二},
author = {family=Zhang, cjk=張學成, given=Xuecheng},
location = {Shanghai},
publisher = {Shangwu Yinshuguan},
date = {2016},
}
@book{Book3,
title = {Sŏmyŏng},
titleaddon = {書名},
author = {family=Zhang, cjk=장학성, given=Haksŏng},
location = {Shanghai},
publisher = {Shangwu Yinshuguan},
date = {2016},
}
\end{filecontents*}

\usepackage[style=authoryear,backend=biber,datamodel=\jobname]{biblatex}
\addbibresource{\jobname.bib}

% Based on definitions from biblatex.def

\newbibmacro*{name:cjk}[3]{%
  \usebibmacro{name:delim}{#2#3#1}%
  \usebibmacro{name:hook}{#2#3#1}%
  \mkbibnamefamily{#1}%
  \ifdefvoid{#2}{}{\bibnamedelimd\mkbibnamegiven{#2}}%
  \ifdefvoid{#3}{}{\bibnamedelimd\mkbibnamecjk{#3}}}

\newbibmacro*{name:cjk-nocjk}[3]{%
  \usebibmacro{name:delim}{#2#3#1}%
  \usebibmacro{name:hook}{#2#3#1}%
  \mkbibnamefamily{#1}%
  \ifdefvoid{#2}{}{\bibnamedelimd\mkbibnamegiven{#2}}}

\DeclareNameFormat{labelname}{%
  \iffieldequalstr{uniquepart}{base}
    {\usebibmacro{name:family}
       {\namepartfamily}
       {\namepartgiven}
       {\namepartprefix}
       {\namepartsuffix}}
    {\ifdefvoid{\namepartcjk}
       {\ifnumequal{\namepartgivenun}{1}
          {\ifuseprefix
             {\usebibmacro{name:given-family}
               {\namepartfamily}
               {\namepartgiveni}
               {\namepartprefix}
               {\namepartsuffixi}}
             {\usebibmacro{name:given-family}
               {\namepartfamily}
               {\namepartgiveni}
               {\namepartprefixi}
               {\namepartsuffixi}}}
          {\usebibmacro{name:given-family}
             {\namepartfamily}
             {\namepartgiven}
             {\namepartprefix}
             {\namepartsuffix}}}
       {\iffieldequalstr{uniquepart}{given}
          {\usebibmacro{name:cjk-nocjk}
             {\namepartfamily}{\namepartgiven}{\namepartcjk}}
          {\usebibmacro{name:cjk}
             {\namepartfamily}{\namepartgiven}{\namepartcjk}}}}%
  \usebibmacro{name:andothers}}

\DeclareUniquenameTemplate{
  \namepart[use=true, base=true]{prefix}
  \namepart[base=true]{family}
  \namepart[context=fullonly]{given}
  \namepart[context=fullonly]{cjk}
}

\begin{document}
  \cite{Book1,Book2,Book3}

  \printbibliography
\end{document}
```
gives me 
```
      \name{author}{1}{}{%
        {{uniquename=2,uniquepart=cjk,hash=137db319fcba905b93146b1eb53decd1}{%
           family={Zhang},
           familyi={Z\bibinitperiod},
           given={Xuecheng},
           giveni={X\bibinitperiod},
           givenun=0,
           cjk={張學成},
           cjki={張\bibinitperiod},
           cjkun=2}}%
      }
 
      \name{author}{1}{}{%
        {{uniquename=2,uniquepart=cjk,hash=7590e773972833a2e409409600c23dd2}{%
           family={Zhang},
           familyi={Z\bibinitperiod},
           given={Xuecheng},
           giveni={X\bibinitperiod},
           givenun=0,
           cjk={章學成},
           cjki={章\bibinitperiod},
           cjkun=2}}%
      }
```
in the `.bbl`.

**Comment by plk** [comment] 2017-09-24 10:21
There was a bug - fixed with regression tests in place - can you check? Note that "context" is now "disambiguation" so you'll need to change that in your `\DeclareUniquenameTemplate`. I expect the `un` value to be a communication to the style about what it should print, instead of needing interpretation so you are right that if you set `fullonly` then that always means value 2 which in turn means "print the full namepart". This I think is always safe as you have to print something for every namepart even if you set disambiguation to "none". So, basically, the template says which level to use for disambiguation but the `un` value which results from this tells you what to print.

**Comment by plk** [comment] 2017-09-24 10:31
I realise now that currently, the only way a namepart`un` value before the disambiguating part would be 0 is when, in the template, it is explicitly set to "none". This means that it is ignored for disambiguation. Then, we leave the formatting up to the style because this only means "namepart was not used for disambiguation". I think this is reasonable - what do you think?

**Comment by moewew** [comment] 2017-09-24 11:07
I'm happy with my `.bbl` now.

I agree with your interpretation of the `un` value. It should be our best guess of what the user might want to print to (minimally) disambiguate a name based on the `\DeclareUniquenameTemplate` settings. Of course the user can choose to act differently based on their needs, but what we have now seems reasonable.

It makes sense to output `0` for `none` nameparts. Though I have a hard time imagining why `none` would be useful then. What is the difference to leaving the namepart out of `\DeclareUniquenameTemplate` altogether?

I'm a bit unhappy with how `full` means basically 'fullonly or init'. Maybe we could rename `fullonly` to `full` and `full` to `both`? Or rename `init` to `initonly`, so things are consistent.

**Comment by plk** [comment] 2017-09-24 11:48
True that "none" is the same as leaving a namepart out completely but it is easy to allow for this, just for completeness.

Agreed about the terminology - latest uploads now have `initorfull` instead of `full` (just in case in the future any other options are added and `both` is then ambiguous) and `fullonly` is now `full`. The semantics of `init` and `full` for the global `uniquename` option remain as before as it's too big a change to alter them too and probably not necessary.

We just have to decide about the `\DeclareSortingNamekeyScheme` etc. interaction.

**Comment by moewew** [comment] 2017-09-24 12:00
Very good.

Regarding `\DeclareSortingNamekeyScheme` et al. I would go with what I suggested above. Create a new meta-option `name(key)scheme` (name subject to change if something more appropriate comes along) that controls sorting (`sortnamekeyscheme` for `\DeclareSortingNamekeyScheme`), uniquename (`uniquenamename(key)scheme` for `\DeclareUniquenameTemplate`) and labelalphaname (`labelalphaname(key)scheme` `\DeclareLabelalphaNameTemplate`). If something is not declared for a specific scheme, fall back to the defaults.

Of course that lets the number of new schemes explode, but I think this is the only way to enable the user to do everything independently. I admit, I'm not sure if that makes sense since you rightfully point out that these things are intimately related.
Alternatively, we could tie everything to `sortnamekeyscheme`, but that takes away the option for independence.

**Comment by plk** [comment] 2017-09-24 12:42
Hmm, we are really talking about per-refsections options here. That is tricky because adding new per-refsection options is very difficult - it requires a lot of changes in both `biblatex` and `biber` - I've had to do it twice for name sorting schemes and prefices. I wonder if changing the `sortingnamekeyscheme` option for refsections to `namekeyscheme` and making this a meta-option which sets all three of the thing you mention would be ok?

**Comment by moewew** [comment] 2017-09-24 12:47
That would be OK, too. Of course I'd prefer to be able to define the things independently, but I have no idea how hard that is to implement. The benefit of being able to change the three things independently is probably quite low, so if it is hard to implement the benefit/cost ratio would say we just implement the meta-option to set all three things simultaneously.

**Comment by plk** [comment] 2017-09-24 12:54
It would still be possible independently, if any of the three things had no variant with the name `namekeyscheme`, it would fall back on the global setting.

**Comment by moewew** [comment] 2017-09-24 13:28
Yes, it is unlikely that one would want to control everything independently. It would be nice to have even though I can't think of an application right now, but it is definitely not out top priority. If it would require restructuring of lots of code, what you have in mind is definitely enough.

**Comment by plk** [comment] 2017-09-24 17:49
Just to be clear, the ideal would be to have `uniquenametemplatename` and `labelalphanametemplatename` as options for refsections just like `sortnamekeyschemename`?

**Comment by moewew** [comment] 2017-09-25 07:42
Not only for `refsection`s (the docs mention contexts?), but also per-name, per-namelist and per-entry. So these options should work exactly like `sortnamekeyscheme`.

**Comment by plk** [comment] 2017-09-25 07:50
Hmm, that makes it much harder. I'm not sure how much use narrower contexts than refcontext are for `uniquenametemplate` as that would probably make uniqueness really confusing. Same with labels I think - uniqueness and labels result in printed information and if that's not predictable between entries, I think that gets really confusing? `sortnamekeyscheme` doesn't change what is printed for a entry.

**Comment by moewew** [comment] 2017-09-25 07:53
Mhh, well per-name makes sense to me.
Assume I want to treat Western names with `family -> given initial -> given full` and CJK names with `family -> given full -> CJK full`. That I can only get if I can control this per-name (per-namelist, per-entry depending on the exact situation). The exact same holds for sorting.

**Comment by plk** [comment] 2017-10-08 20:47
I'm working on this now, should have something for you to test soon.

**Comment by plk** [comment] 2017-10-20 22:58
This was fairly major biber surgery as I took the opportunity to regularise sorting scheme handling internals. You can try biblatex 3.8 and biber 2.8 DEV versions. `uniquenametemplate` and `labelalphanametemplate` are now per-refcontext, per-entry, per-namelist and per-name.

**Comment by moewew** [comment] 2017-10-21 10:43
That sounds great. Thank you very much.

I'll play around with this and report back. (Might take some time to get back into things and understand why I wanted certain features.)

**Comment by plk** [comment] 2017-10-21 10:47
It would be nice in your investigations to create some docs for biblatex - perhaps adding to `93-nameparts.tex`? It has an accompanying `.dbx` you can customise too.

**Comment by moewew** [comment] 2017-10-21 10:48
Will see what I can do.

**Comment by moewew** [comment] 2017-10-21 11:28
A few things:

- Am I right in thinking that I can specify a uniquename template with `uniquenametemplatename` in the `.bib` file? (That would need to be mentioned in the docs.)
- In analogy to `sortnamekeyscheme` I would drop the `name` ending.
- `keyval` also throws an error, it seems the corresponding `\define@key{blx@opt@name}` and `\define@key{blx@opt@namelist}` are missing.
- Biber warns `WARN - Invalid namepart 'uniquenametemplatename' found in extended name format name 'author'`, but things work fine.

The same holds probably for `sortnamekeyschemename` and `labelalphanametemplatename`.

**Comment by moewew** [comment] 2017-10-21 11:34
It would be ideal if there were a one-name-catches-all option that would set `sortnamekeyschemename`, `labelalphanametemplatename`,  `uniquenametemplatename` all to the same value at once.

**Comment by moewew** [comment] 2017-10-21 16:37
Things are working rather well so far. But there is a weird behaviour in the following MWE
```
\documentclass[a4paper]{article}
\usepackage{fontspec}
\setmainfont{Cambria}
\setsansfont{Arial}
\setmonofont{Courier New}
\usepackage[british]{babel}
\usepackage{csquotes}
\usepackage{filecontents}
\begin{filecontents}{\jobname.bib}
@book{tolstoy,
  author       = {given=Лев, patronymic=Николаевич, family=Толстой, uniquenametemplatename=russian},
  title        = {Война и мир},
  date         = {1877}
}
@book{bulgakov,
  author       = {given=Михаил, patronymic=Афанасьевич, family=Булгаков, uniquenametemplatename=russian},
  title        = {Мастер и Маргарита},
  date         = {1966}
}
\end{filecontents}
\usepackage[style=authoryear,datamodel=93-nameparts,backend=biber]{biblatex}
\addbibresource{biblatex-examples.bib}
\addbibresource{\jobname.bib}

\DeclareUniquenameTemplate[ethiopian]{
  \namepart[base=true]{given}
  \namepart{patronymic}
  \namepart{papponymic}}

\DeclareUniquenameTemplate[russian]{
  \namepart[base=true]{family}
  \namepart{given}
  \namepart{patronymic}
}

\begin{document}
\noindent\textcite{tolstoy}\\
\textcite{bulgakov}

\printbibliography
\end{document}

```

when run as-is I don't get `givenun` information in the `.bbl`, but with the `\DeclareUniquenameTemplate[ethiopian]{` bit removed `givenun` magically reappears.

**Comment by plk** [comment] 2017-10-21 23:30
I have rationalised the naming of a few things. I have dropped all the "scheme" terminology from sorting as it was confusing with since "scheme" is used in the docs to refer to citation and reference schemes mostly and the other context options talk about "template". Some options and cmds are now renamed and deprecation warnings are in place (notably `\DeclareSortingScheme` and `\DeclareSortingNamekeyScheme`). `sortingnamekeyscheme` is now `sortingnamekeytemplatename`. I want the "name" endings to differentiate from the actual templates themselves and it was just too messy to have different forms of the option names between biblatex and biber.

I have also added to the main table of options in the doc to show per-refcontext, per-namelist and per-name option scope.

There is now a `nametemplates` meta-option which sets the three other nametemplate options at once, as you requested.

All this is documented.

Your issue was a bug which is now fixed if you pull the latest 3.8/2.8 dev versions.

**Comment by moewew** [comment] 2017-10-22 10:08
Things work very well so far. I am in the process of producing an extended `93-nameparts` with CJK, Ethiopian and Russian names. I will submit a pull request once things here are finalised and the commits are on GitHub. (As an aside: I can't help thinking that Russian names are already handled rather well out of the box in the default scheme when the patronymic is simply considered a given name.)

It's not ideal that `sortingnamekeytemplatename`, `uniquenametemplatename` and `labelalphatemplatename` are so long in the, but if there are technical considerations against dropping the 'name' bit, I can accept that. It should probably be mentioned in the docs that the per-name and per-namelist options differ from their 'document-option' counterparts in that they need the additional 'name'.

Would it be possible to make `nametemplates` 'per-name' and 'per-namelist' as well?

**Comment by plk** [comment] 2017-10-22 13:49
The "long" format of the options are universal and are mandatory everywhere otherwise it gets really messy mapping them going into and coming out of biber and also makes reading the code a pain because then there is a clash between the options holding the actual templates and the options naming them. It gets really difficult to make sense of the code without some sort of strict naming here (even for me and at some point, I need to educate someone else to help with this ...). 

`nametemplates` is now possible at all scopes and I added docs to the options scope table appendix with brief example of how to set options at per-entry, per-namelist and per-name scope.

**Comment by moewew** [comment] 2017-10-22 14:04
Very nice.

Unfortunately,
```author       = {given=Лев, patronymic=Николаевич, family=Толстой, nametemplates=russian},```
does not work for me, I get 
```WARN - Invalid namepart 'nametemplates' found in extended name format name 'author' in entry 'tolstoy', ignoring```

Should `\ifsortingnamekeytemplate` be renamed to `\ifsortingnamekeytemplatename`? It would also be good to have analogous commands for `uniquenametemplatename` and `labelalphatemplatename`.

**Comment by plk** [comment] 2017-10-22 15:11
Fixed - you just need to pull biblatex again, not biber.

**Comment by moewew** [comment] 2017-10-22 15:28
Thank you very much. Now everything works as expected.

I will prepare a pull request with an extended example document soon. It will probably need a bit of fine-tuning since I had to use non-standard fonts for the CJK characters, so I can't guarantee it will immediately work on your end.

**Comment by plk** [comment] 2017-10-22 21:54
I can't find a built-in font that includes all the glyphs on OSX but that's not so bad. It would be good if you could add comments in the file to say what is going on etc. so that we can refer to this doc?

**Comment by moewew** [comment] 2017-10-23 08:57
OK, I added a few comments. https://github.com/plk/biblatex/commit/b99b72bdd028b7e5f30573ee587be3fc68c06449

**Closed** 2017-10-23 18:15 UTC
Labels: enhancement
