### ISSUE TITLE
autolang=langname with lualatex

### ISSUE THREAD

**Issue by svenper** [plk/biblatex#777] opened 2018-08-03 19:22 UTC
With `autolang=langname`, biblatex or polyglossia has problems, but only when using `lualatex`.

[`lualatex` output](https://gist.githubusercontent.com/svenper/f8c5cd76b25b9b1f62960274f6edc341/raw)

[`xelatex` output](https://gist.githubusercontent.com/svenper/c344e4ea8d01cd91a708d73adfa4c9f6/raw)

M(N)WE:

```tex
\documentclass{article}
\usepackage{fontspec}
\setmainfont{Coelacanth}
\usepackage{polyglossia}
\setmainlanguage{french}
\setotherlanguage{english}
\usepackage{csquotes}
\usepackage[autolang=langname]{biblatex}
\addbibresource{biblatex-examples.bib}
\begin{document}
hello
\nocite{*}
\printbibliography
\end{document}
```

**Comment by moewew** [comment] 2018-08-03 20:24
This seems to be a `polyglossia` bug. The following MWE does what `biblatex` does with `autolang=langname` and reproduces the error without `biblatex`

```latex
\documentclass{article}
\usepackage{polyglossia}
\setmainlanguage{french}
\setotherlanguage{english}

\begin{document}
hello

\english[variant=british]foo\endenglish
\end{document}
```

I could make the error go away with `\setotherlanguage[variant=british]{english}`, but I'm not sure if that is what one should do (can I still get American hyphenation with `variant=american` in the same document?) and I can't explain why the behaviour is different for XeLaTeX and LuaLaTeX. Please take this to https://github.com/reutenauer/polyglossia/issues.

Keep in mind that `polyglossia` support in `biblatex` is shaky at best.

**Comment by svenper** [comment] 2018-08-04 10:59
Continued in reutenauer/polyglossia#208

**Comment by moewew** [comment] 2018-08-23 06:42
I'm closing this for now since it is a `polyglossia` issue.

**Closed by moewew** 2018-08-23 06:42 UTC
Labels: invalid, localisation
