### ISSUE TITLE
The season is not passed to the related "clone"

### ISSUE THREAD

**Issue by danielshub** [plk/biblatex#897] opened 2019-06-14 21:14 UTC
With the following MWE I would expect to see the season for the related entry. The season does not even show up in the bbl file
```
\documentclass{article}
\usepackage{biblatex}

\usepackage{filecontents}

\begin{filecontents}{\jobname.bib}
@article{main,
  author       = {Doe, John},
  title        = {My main title},
  journaltitle = {My main journal},
  related      = {rel1, rel2},
  relatedtype  = {reprintfrom},
}
@article{rel1,
  title        = {Related 1 title},
  journaltitle = {Related 1 journal},
  date         = {2019-21/2019-22},
}
@article{rel2,
  title        = {Related 2 title},
  journaltitle = {Related 2 journal},
  date         = {2019-01/2019-02},
}
\end{filecontents}

\addbibresource{\jobname.bib}

\begin{document}
\cite{main}
\printbibliography
\end{document}
```
I would expect to see the season in the cloned entry of the bbl file

    \entry{8c785927ea6e2b441c387b1610e7c4b3}{article}{dataonly}
      \field{sortinit}{R}
      \field{sortinithash}{da6b42bd3ab22fee61abed031ee405f7}
      \field{labeltitlesource}{title}
      \field{clonesourcekey}{rel1}
      \field{endyear}{2019}
      \field{journaltitle}{Related 1 journal}
      \field{title}{Related 1 title}
      \field{year}{2019}
      \warn{\item Datamodel: Entry '8c785927ea6e2b441c387b1610e7c4b3' (): Missing mandatory field 'author'}
    \endentry

**Comment by moewew** [comment] 2019-06-15 14:17
@plk This seems to be a Biber issue since the info is already gone in the `.bbl`. I suspected the `clone` function in `Entry.pm`, but I don't quite understand why it is dropping `season`. The extended MWE
```latex
\documentclass{article}
\usepackage{biblatex}

\usepackage{filecontents}

\begin{filecontents}{\jobname.bib}
@article{main,
  author       = {Doe, John},
  title        = {My main title},
  journaltitle = {My main journal},
  related      = {rel1, rel2},
  relatedtype  = {reprintfrom},
}
@article{rel1,
  title        = {Related 1 title},
  journaltitle = {Related 1 journal},
  date         = {2019-21/2019-22},
}
@article{rel2,
  title        = {Related 2 title},
  journaltitle = {Related 2 journal},
  date         = {-2019-01~/-2019-02?},
}
\end{filecontents}

\addbibresource{\jobname.bib}

\begin{document}
\cite{main,rel1,rel2}
\printbibliography
\end{document}
```

shows that other date info like `era`, `circa`, `uncertain` is also dropped.

**Comment by plk** [comment] 2019-06-15 15:33
Thank you for reporting - it was a bug - fixed in DEV on SF with regression tests in place.

**Comment by moewew** [comment] 2019-06-15 15:38
Thank you very much. The MWE works fine with the dev version.

**Comment by danielshub** [comment] 2019-06-15 16:21
Wow two bugs reported and closed in less than 24 hours. You two are good. Thanks a lot for fixing them.

**Comment by moewew** [comment] 2019-08-25 07:05
`biblatex` 3.13/Biber 2.13 with the fixes for this issue are available on CTAN now.

**Closed by moewew** 2019-08-25 07:05 UTC
Labels: bug
