### ISSUE TITLE
One extra frame added with some bib entries with option backend=bibtex

### ISSUE THREAD

**Issue by qqlovekerry** [plk/biblatex#517] opened 2016-11-27 03:11 UTC
Hello everyone,
I am new to biblatex, and I found something strange there when I use biblatex with beamer documentclass. My code is:
`\documentclass{beamer}

\hypersetup{pdfpagemode={FullScreen}}
\setbeamertemplate{navigation symbols}{}
\usepackage{graphicx}
\usepackage{animate}
\usepackage[backend=bibtex,sorting=none,hyperref=true]{biblatex}
%\usepackage[backend=biber,sorting=none,hyperref=true]{biblatex}
\addbibresource{ref/test.bib}

\title{\LaTeX Test}
\author{A Newbie}
\institute{Who Loves \LaTeX}
\date{\today}

\begin{document}
\begin{frame}
  \titlepage
\end{frame}
\begin{frame}
  \frametitle{\secname}
%  biblatex test\cite{Liu2012} \\
%  biblatex test\cite{Bringa2012_NL.12.3351} \\
%  biblatex test\footfullcite{Liu2012}
  biblatex test\footfullcite{Bringa2012_NL.12.3351} \\
%  biblatex test\footcite{Liu2012}
%  biblatex test\footcite{Bringa2012_NL.12.3351} \\
\end{frame}
\begin{frame}
  \frametitle{\secname}
  \printbibliography
\end{frame}
\end{document}
`

And my bib file is: 
`% Encoding: UTF-8

@Article{Bringa2012_NL.12.3351,
  author    = {Bringa, E. M. and Monk, J. D. and Caro, A. and Misra, A. and Zepeda-Ruiz, L. and Duchaineau, M. and Abraham, F. and Nastasi, M. and Picraux, S. T. and Wang, Y. Q. and Farkas, D.},
  title     = {Are Nanoporous Materials Radiation Resistant?},
  journal   = {Nano Letters},
  year      = {2012},
  volume    = {12},
  number    = {7},
  pages     = {3351-3355},
  note      = {PMID: 21651306},
  doi       = {10.1021/nl201383u},
  eprint    = {http://dx.doi.org/10.1021/nl201383u},
  file      = {:Are Nanoporous Materials Radiation Resistant_Nano Lett., 2012 12 (7) pp 3351–3355.pdf:PDF},
  groups    = {Nanowire irradiation, simulation},
  owner     = {Wenqiang},
  timestamp = {2014.09.22},
  url       = {http://dx.doi.org/10.1021/nl201383u},
}

@Article{Liu2012,
  author    = {Wenqiang Liu and Ling XU and Ni Liu and Yuanbao Liao and Dong Liu and Jun Xu and Zhongyuan Ma and Kunji Chen},
  title     = {Electron beam evaporation deposition and properties of Abrupt GST/Si heterojunction structure},
  journal   = {Vacuum},
  year      = {2012},
  volume    = {86},
  number    = {7},
  pages     = {804 - 807},
  note      = {Selected papers from the \{IUVSTA\} 18th International Vacuum Congress (IVC-18) held in Beijing, P.R.China, 23 -27 August 2010},
  abstract  = {The ternary alloy, Ge2Te2Sb5 is one of the most important compounds of the GeTe-Sb2Te3 pseudobinary systems. Ge2Te2Sb5 thin films of thickness of 100 nm–300 nm were deposited by electron beam evaporation. After annealing at different temperatures, we did X-ray diffraction measurement to characterize the structure transformation of the material. In-situ resistance measurement depending on the temperature shows that there is about three orders of magnitude change between the high resistance state (amorphous state) and the low resistance state (face-centered cubic state). To construct a heterojunction diode, we deposited Ge2Te2Sb5 thin films on n-type silicon wafers. Rectification effects were observed in voltage–current measurements of the abrupt heterojunctions. Traditional voltage–current relationship of p–n junctions and metal-semiconductor junctions are used to explain the characteristics of Ge2Te2Sb5/n-Si heterojunctions. },
  doi       = {http://dx.doi.org/10.1016/j.vacuum.2010.12.015},
  issn      = {0042-207X},
  keywords  = {Electron beam evaporation deposition},
  owner     = {mgqqlwq},
  timestamp = {2015.04.07},
  url       = {http://www.sciencedirect.com/science/article/pii/S0042207X1100011X},
}

@Comment{jabref-meta: databaseType:bibtex;}`

If I use the bibtex key Bringa2012_NL.12.3351, there is one extra frame added on the first page with no meaning. If I use another one Liu2012, everything seems OK. Furthermore, if I change the option to backend=biber, the result is OK with both of the bibtex key. Is there some minor bug with option backend=bibtex?

And I also have one more question, I hope it is not so unpolite to ask a question in an issue, but I did not find anything like a mailing list to post my questions. If there is any, please tell me.
In beamer, I want to use \footfullcite to cite a reference at current frame at foot line. My problem is, as you can see from my final pdf file, I feel too much information is given with \footfullcite. Is it possible to refine the style of \footfullcite? I hope the style could be something like [authors][title][journal][volume][year][pages].

My pdf file is the attachment. Any help would be much appreciated!
[biblatextest.pdf](https://github.com/plk/biblatex/files/614546/biblatextest.pdf)

**Comment by moewew** [comment] 2016-11-27 07:52
Your second question is probably better asked on [TeX.SX](http://tex.stackexchange.com/questions/tagged/biblatex), but please be aware that people have asked similar things before, with a bit of searching you should be able to find something similar.

I can't reproduce the issue with the rogue page appearing from your code above even with BibTeX. Can you try and minimise your code example further? (Is the `animate` package needed, do you need `\hypersetup{pdfpagemode={FullScreen}}`, the `\titlepage` etc.? Is it necessary to give the `abstract` in the `.bib` field to reproduce the issue?) Do you get any errors or warnings in the `.log` or `.blg` files?

(Note that the code markup in your question is messed up a bit, there are `\ `s appearing in a lot of weird places. Use three backticks to start code block mode.)

**Comment by qqlovekerry** [comment] 2016-11-27 09:37
@moewew Thank you very much! I will ask my second question on TeX.SX.
Sorry, my previous post may be a little messed up. I have tried to minimize my code as best as I can.
There are:
`\documentclass{beamer}
\usepackage[backend=bibtex]{biblatex}
%\usepackage[backend=biber]{biblatex}
\addbibresource{ref.bib}
\begin{document}
\begin{frame}
%  biblatex test\footfullcite{Liu2012}
  biblatex test\footfullcite{Bringa2012_NL.12.3351}
\end{frame}
\end{document}`
And my bib file ref.bib is:
`% Encoding: UTF-8

@Article{Bringa2012_NL.12.3351,
  author    = {Bringa, E. M. and Monk, J. D. and Caro, A. and Misra, A. and Zepeda-Ruiz, L. and Duchaineau, M. and Abraham, F. and Nastasi, M. and Picraux, S. T. and Wang, Y. Q. and Farkas, D.},
  title     = {Are Nanoporous Materials Radiation Resistant?},
  journal   = {Nano Letters},
  year      = {2012},
  volume    = {12},
  number    = {7},
  pages     = {3351-3355},
  note      = {PMID: 21651306},
  doi       = {10.1021/nl201383u},
  eprint    = {http://dx.doi.org/10.1021/nl201383u},
  file      = {:Are Nanoporous Materials Radiation Resistant_Nano Lett., 2012 12 (7) pp 3351–3355.pdf:PDF},
  groups    = {Nanowire irradiation, simulation},
  owner     = {Wenqiang},
  timestamp = {2014.09.22},
  url       = {http://dx.doi.org/10.1021/nl201383u},
}

@Article{Liu2012,
  author    = {Wenqiang Liu and Ling XU and Ni Liu and Yuanbao Liao and Dong Liu and Jun Xu and Zhongyuan Ma and Kunji Chen},
  title     = {Electron beam evaporation deposition and properties of Abrupt GST/Si heterojunction structure},
  journal   = {Vacuum},
  year      = {2012},
  volume    = {86},
  number    = {7},
  pages     = {804 - 807},
  doi       = {http://dx.doi.org/10.1016/j.vacuum.2010.12.015},
  issn      = {0042-207X},
  keywords  = {Electron beam evaporation deposition},
  owner     = {mgqqlwq},
  timestamp = {2015.04.07},
  url       = {http://www.sciencedirect.com/science/article/pii/S0042207X1100011X},
}

@Comment{jabref-meta: databaseType:bibtex;}`

Still, there is one extra frame on the top of the pdf, if I use bibtex key Bringa2012_NL.12.3351. 
But if I use another bibtexkey Liu2012 with backend=bibtex or backend=biber with both bibtex key, everything is OK. I am sorry I do not quite understand the lines in 

> log

 or blg file
. But there is no `error` or `warning` in the blg file.

[modified.pdf](https://github.com/plk/biblatex/files/614620/modified.pdf)

**Comment by moewew** [comment] 2016-11-27 10:45
Now your code is a bit too minimal, as you can tell if you try to run the snippet. I ran the following fully-self contained code in my PC without a problem.

_Caveat: this will overwrite a `.bib` file with the same name without warning, only run this in a separate test directory!_

```
\listfiles
\documentclass{beamer}
\usepackage[T1]{fontenc}
\usepackage[utf8]{inputenc}
\usepackage[backend=bibtex]{biblatex}
%\usepackage[backend=biber]{biblatex}

\usepackage{filecontents}
\begin{filecontents}{\jobname.bib}
@Article{Bringa2012_NL.12.3351,
  author    = {Bringa, E. M. and Monk, J. D. and Caro, A. and Misra, A. and Zepeda-Ruiz, L. and Duchaineau, M. and Abraham, F. and Nastasi, M. and Picraux, S. T. and Wang, Y. Q. and Farkas, D.},
  title     = {Are Nanoporous Materials Radiation Resistant?},
  journal   = {Nano Letters},
  year      = {2012},
  volume    = {12},
  number    = {7},
  pages     = {3351-3355},
  note      = {PMID: 21651306},
  doi       = {10.1021/nl201383u},
  eprint    = {http://dx.doi.org/10.1021/nl201383u},
  file      = {:Are Nanoporous Materials Radiation Resistant_Nano Lett., 2012 12 (7) pp 3351–3355.pdf:PDF},
  groups    = {Nanowire irradiation, simulation},
  owner     = {Wenqiang},
  timestamp = {2014.09.22},
  url       = {http://dx.doi.org/10.1021/nl201383u},
}

@Article{Liu2012,
  author    = {Wenqiang Liu and Ling XU and Ni Liu and Yuanbao Liao and Dong Liu and Jun Xu and Zhongyuan Ma and Kunji Chen},
  title     = {Electron beam evaporation deposition and properties of Abrupt GST/Si heterojunction structure},
  journal   = {Vacuum},
  year      = {2012},
  volume    = {86},
  number    = {7},
  pages     = {804 - 807},
  doi       = {http://dx.doi.org/10.1016/j.vacuum.2010.12.015},
  issn      = {0042-207X},
  keywords  = {Electron beam evaporation deposition},
  owner     = {mgqqlwq},
  timestamp = {2015.04.07},
  url       = {http://www.sciencedirect.com/science/article/pii/S0042207X1100011X},
}
\end{filecontents}
\addbibresource{\jobname.bib}

\begin{document}
\begin{frame}
%  biblatex test\footfullcite{Liu2012}
  biblatex test\footfullcite{Bringa2012_NL.12.3351}
\end{frame}
\end{document}
```

Please try to compile the exact code I posted here and show us the `.blg` and `.log` files after the usual TeX > BibTeX > TeX > TeX compile sequence.

**Comment by qqlovekerry** [comment] 2016-11-27 11:16
I copied your whole code to a new file named job.tex. I used XeLaTeX> BibTeX>XeLaTeX>XeLaTeX to compile the tex file. By the way, I am running TeXLive2016 on Ubuntu 14.04LTS. It seems I can not upload `blg` and `log` file directly, so I convert them to pdf files. Please see the attachments.
[job.blg.pdf](https://github.com/plk/biblatex/files/614658/job.blg.pdf)
[job.log.pdf](https://github.com/plk/biblatex/files/614659/job.log.pdf)

**Comment by moewew** [comment] 2016-11-27 14:17
You could upload your `.log`/`.blg` via https://gist.github.com/. Anyway, you are running `biblatex` 3.4, which is outdated with 3.6 being the current version. Do an update of the packages with `tlmgr`.

Other than that, all things look OK.

Do you get a similar problem if you use the `article` document class?
```
\documentclass{article}
\usepackage[backend=bibtex]{biblatex}
%\usepackage[backend=biber]{biblatex}

\usepackage{filecontents}
\begin{filecontents}{\jobname.bib}
@Article{Bringa2012_NL.12.3351,
  author    = {Bringa, E. M. and Monk, J. D. and Caro, A. and Misra, A. and Zepeda-Ruiz, L. and Duchaineau, M. and Abraham, F. and Nastasi, M. and Picraux, S. T. and Wang, Y. Q. and Farkas, D.},
  title     = {Are Nanoporous Materials Radiation Resistant?},
  journal   = {Nano Letters},
  year      = {2012},
  volume    = {12},
  number    = {7},
  pages     = {3351-3355},
  note      = {PMID: 21651306},
  doi       = {10.1021/nl201383u},
  eprint    = {http://dx.doi.org/10.1021/nl201383u},
  file      = {:Are Nanoporous Materials Radiation Resistant_Nano Lett., 2012 12 (7) pp 3351–3355.pdf:PDF},
  groups    = {Nanowire irradiation, simulation},
  owner     = {Wenqiang},
  timestamp = {2014.09.22},
  url       = {http://dx.doi.org/10.1021/nl201383u},
}

@Article{Liu2012,
  author    = {Wenqiang Liu and Ling XU and Ni Liu and Yuanbao Liao and Dong Liu and Jun Xu and Zhongyuan Ma and Kunji Chen},
  title     = {Electron beam evaporation deposition and properties of Abrupt GST/Si heterojunction structure},
  journal   = {Vacuum},
  year      = {2012},
  volume    = {86},
  number    = {7},
  pages     = {804 - 807},
  doi       = {http://dx.doi.org/10.1016/j.vacuum.2010.12.015},
  issn      = {0042-207X},
  keywords  = {Electron beam evaporation deposition},
  owner     = {mgqqlwq},
  timestamp = {2015.04.07},
  url       = {http://www.sciencedirect.com/science/article/pii/S0042207X1100011X},
}
\end{filecontents}
\addbibresource{\jobname.bib}

\begin{document}
Lorem
  biblatex test\footfullcite{Liu2012}
  biblatex test\footfullcite{Bringa2012_NL.12.3351}
\end{document}
```

**Comment by qqlovekerry** [comment] 2016-11-28 01:37
I think the `article` document class still has this problem. There is one extra line on the top of the article with a charactor `p`. 
[article.pdf](https://github.com/plk/biblatex/files/615196/article.pdf)
And I found some error when I tried to update:
`wenqiang@wenqiang-acer:~/Desktop/textest/ctexbeamer$ sudo tlmgr update biblatex
sudo：tlmgr: command not found
wenqiang@wenqiang-acer:~/Desktop/textest/ctexbeamer$ tlmgr update biblatex
tlmgr: package repository http://mirrors.tuna.tsinghua.edu.cn/CTAN/systems/texlive/tlnet (verified)
You don't have permission to change the installation in any way,
specifically, the directory /home/wenqiang/apps/texlive/2016/tlpkg/ is not writable.
Please run this program as administrator, or contact your local admin.
tlmgr: An error has occurred. See above messages. Exiting.`
How can I update biblatex correctly? Thanks!

**Comment by moewew** [comment] 2016-11-28 08:28
Brilliant, OK. So we have isolated the error in so far that it is not caused by a conflict with one of the many packages loaded by `beamer`. Could you try an isolate the problem even more? Delete fields from your `.bib` file, delete temporary files and recompile, until you find out which field in the entry `Bringa2012_NL.12.3351` causes the problem.

I'd have thought `sudo tlmgr` should give you the admin version of `tlmgr` on Ubuntu, but I'm not sure. If you have trouble updating your TeX distribution you should try and ask on a support forum such as TeX.SX, that is not something we can really help you with here.

**Comment by qqlovekerry** [comment] 2016-11-28 09:17
I followed your instruction and had some test. I though it caused by the following line in bib entry `Bringa2012_NL.12.3351`:
`file      = {:Are Nanoporous Materials Radiation Resistant_Nano Lett., 2012 12 (7) pp 3351–3355.pdf:PDF},`
If I delete this line, everything looks good. This line is added by JabRef if a pdf file is attached to this entry. I also test this in `beamer` document class, it gives the same result.

I will try to find how to use tlmgr to update my package. I re-installed my OS several weeks ago, maybe it caused some problem. By the way, I also have found some information about customizing the biblatex style. Thanks for your advise!

**Comment by moewew** [comment] 2016-11-28 17:22
Ah yes, indeed `file` could be the culprit. There was a problem with verbatim-type fields in a recent version of `biblatex` (it is fixed now). (Was it [Bibliography error: “Use of \blx@bbl@verbadd@i doesn't match its definition. \verb”](http://tex.stackexchange.com/q/311426/35864)? Maybe the work-around there can help you. But really you should get around to updating your distribution.)

**Comment by qqlovekerry** [comment] 2016-11-29 06:48
I am so glad the reason has been found. Thanks a bunch for all your helps!
It seems thing goes well with `backend=biber`, maybe I will use `biber` first and laterly I will try to update my 'biblatex` version.

**Comment by moewew** [comment] 2016-11-29 09:34
It is definitely recommended to use Biber instead of BibTeX anyway, so that is a good option. But in order to not run into any fixed errors updating is also important.

**Comment by qqlovekerry** [comment] 2016-11-29 12:31
Thanks!
However, I have one more question. How can I check the version of my `biblatex`? If I use `ls bib*` in my `~/texlive/2016/bin/x86_64-linux` directory. It only gives these items `bibdoiadd  biber  bibexport  bibtex  bibtex8  bibtexu  bibzbladd`. And if I type `biblatex --version` in my terminal, it gives and error that `biblatex` can not be found.
Maybe my questions are a little bothering, but I still hope you can help me there. Thanks in advance!

**Comment by moewew** [comment] 2016-11-29 17:11
`biblatex` is not an executable, it is a TeX package (a text file consumed and interpreted by TeX). You can find out the version of the packages you used in the `.log` file (that is why I asked for it). In your example (on p. 13) we find
```
(/home/wenqiang/apps/texlive/2016/texmf-dist/tex/latex/biblatex/biblatex.sty
Package: biblatex 2016/05/14 v3.4 programmable bibliographies (PK/JW/AB)
```

If you add `\listfiles` to your preamble (as you did), you will get a nice list of the packages used and their versions at the end of the `.log` file, where we have
```
biblatex.sty 2016/05/14 v3.4 programmable bibliographies (PK/JW/AB)
```

So you are running version 3.4, but the current version is 3.6.

You can find out about which `biblatex.sty`s there are on your machine with
```
kpsewhich biblatex.sty
```
The version information is in the first few lines of that file.

You can check the version of Biber (which is an executable in its own right) with
`biber --version`.

**Closed by moewew** 2016-11-29 17:11 UTC

**Comment by qqlovekerry** [comment] 2016-11-30 01:06
Thank you really very much! That is a very detailed explanation. And good news is I update my biblatex successfully now.
